# Yambda ClassBalance baseline

## 0. Imports and config

In [ ]:
import os
import json
import random
import itertools
import gc
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd
import polars as pl

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from tqdm import tqdm


def set_seed(seed: int = 0):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


CFG = {
    # Paths
    "data_dir": "../data",
    "interactions_file": "likes.parquet",
    "artist_file": "artist_item_mapping.parquet",
    "album_file": "album_item_mapping.parquet",

    # Debug/data filtering
    # None = all users; for debugging set 50_000 or 100_000
    "max_users": None,
    "min_user_interactions": 3,
    "min_item_interactions": 5,

    # Model
    "embed_dim": 64,
    "artist_emb_dim": 32,
    "album_emb_dim": 32,
    "tower_hidden": [256, 128, 64],
    "dropout": 0.0,

    # Training
    "batch_size": 4096,
    "grad_clip": 1.0,
    "lr": 1e-3,
    "weight_decay": 0.0,

    # Grid search
    "tune_fast": True,
    "tune_epochs": 3,
    "tune_val_fraction": 1.00,
    "skip_tune_if_cached": True,
    "cache_path": "best_hparams_yambda_likes_features.json",

    # Final training
    "final_epochs": 20,

    # Evaluation
    "eval_k": [10, 50],
    "eval_batch_users": 128,
    "eval_item_batch": 8192,
    "head_fraction": 0.20,

    # Reproducibility
    "seed": 0,
    "seeds": [0, 1, 2, 3, 4],
}

set_seed(CFG["seed"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)
print(f"Final: {len(CFG['seeds'])} seed(s) × {CFG['final_epochs']} epochs")

device: cpu
Final: 5 seed(s) × 20 epochs

## 1. Load data

In [ ]:
def find_file(data_dir: str | Path, name: str) -> Path:
    data_dir = Path(data_dir)
    candidates = [
        data_dir / name,
        data_dir / f"{name}.parquet",
    ]
    for p in candidates:
        if p.exists():
            return p
    raise FileNotFoundError(f"Could not find {name}. Tried: {candidates}")


def normalize_interaction_columns(df: pl.DataFrame) -> pl.DataFrame:
    rename = {}
    for c in df.columns:
        lc = c.lower()
        if lc in {"uid", "user_id", "userid", "user"}:
            rename[c] = "uid"
        elif lc in {"item_id", "itemid", "track_id", "trackid", "song_id"}:
            rename[c] = "item_id"
        elif lc in {"timestamp", "ts", "time", "event_timestamp", "datetime"}:
            rename[c] = "timestamp"
    return df.rename(rename)


def normalize_item_side_columns(df: pl.DataFrame) -> pl.DataFrame:
    rename = {}
    for c in df.columns:
        lc = c.lower()
        if lc in {"item_id", "itemid", "track_id", "trackid"}:
            rename[c] = "item_id"
        elif lc in {"artist_id", "artistid"}:
            rename[c] = "artist_id"
        elif lc in {"album_id", "albumid"}:
            rename[c] = "album_id"
    return df.rename(rename)


DATA_DIR = Path(CFG["data_dir"])
INTERACTIONS_PATH = find_file(DATA_DIR, CFG["interactions_file"])
ARTIST_PATH = find_file(DATA_DIR, CFG["artist_file"])
ALBUM_PATH = find_file(DATA_DIR, CFG["album_file"])

print("interactions:", INTERACTIONS_PATH)
print("artists:", ARTIST_PATH)
print("albums:", ALBUM_PATH)

interactions = pl.read_parquet(INTERACTIONS_PATH)
interactions = normalize_interaction_columns(interactions)

print("raw interactions:", interactions.shape)
print("columns:", interactions.columns)
print(interactions.head())

required = {"uid", "item_id"}
missing = required - set(interactions.columns)
assert not missing, f"Missing required columns {missing}. Available: {interactions.columns}"

if "timestamp" not in interactions.columns:
    print("[WARN] timestamp not found: using row index as timestamp")
    interactions = interactions.with_row_index("timestamp")

interactions = interactions.select(["uid", "item_id", "timestamp"])

# Deduplicate repeated likes by the same user for the same item.
interactions = (
    interactions
    .sort("timestamp")
    .unique(subset=["uid", "item_id"], keep="first")
)

print("after dedup:", interactions.shape)

interactions: data/likes.parquet
artists: data/artist_item_mapping.parquet
albums: data/album_item_mapping.parquet
raw interactions: (881456, 4)
columns: ['uid', 'timestamp', 'item_id', 'is_organic']
shape: (5, 4)
┌─────┬───────────┬─────────┬────────────┐
│ uid ┆ timestamp ┆ item_id ┆ is_organic │
│ --- ┆ ---       ┆ ---     ┆ ---        │
│ u32 ┆ u32       ┆ u32     ┆ u8         │
╞═════╪═══════════╪═════════╪════════════╡
│ 100 ┆ 44755     ┆ 732449  ┆ 1          │
│ 100 ┆ 1155860   ┆ 6568592 ┆ 0          │
│ 100 ┆ 1259125   ┆ 5411243 ┆ 1          │
│ 100 ┆ 1260005   ┆ 7371186 ┆ 0          │
│ 100 ┆ 1263935   ┆ 4943655 ┆ 0          │
└─────┴───────────┴─────────┴────────────┘
after dedup: (844690, 3)

## 2. Filtering

In [ ]:
# Item-core filter
item_counts = interactions.group_by("item_id").len().rename({"len": "cnt"})
good_items = item_counts.filter(pl.col("cnt") >= CFG["min_item_interactions"]).select("item_id")
interactions = interactions.join(good_items, on="item_id", how="semi")
print("after item-core:", interactions.shape)

# User-core filter
user_counts = interactions.group_by("uid").len().rename({"len": "cnt"})
good_users = user_counts.filter(pl.col("cnt") >= CFG["min_user_interactions"]).select("uid")
interactions = interactions.join(good_users, on="uid", how="semi")
print("after user-core:", interactions.shape)

# Optional debug subset by users. This does not break histories.
if CFG["max_users"] is not None:
    users_sub = (
        interactions
        .select("uid")
        .unique()
        .sample(n=int(CFG["max_users"]), seed=CFG["seed"])
    )
    interactions = interactions.join(users_sub, on="uid", how="semi")
    print(f"after max_users={CFG['max_users']}:", interactions.shape)

    # Repeat filters after subsampling.
    item_counts = interactions.group_by("item_id").len().rename({"len": "cnt"})
    good_items = item_counts.filter(pl.col("cnt") >= CFG["min_item_interactions"]).select("item_id")
    interactions = interactions.join(good_items, on="item_id", how="semi")

    user_counts = interactions.group_by("uid").len().rename({"len": "cnt"})
    good_users = user_counts.filter(pl.col("cnt") >= CFG["min_user_interactions"]).select("uid")
    interactions = interactions.join(good_users, on="uid", how="semi")

print("final filtered:", interactions.shape)
print("users:", interactions["uid"].n_unique())
print("items:", interactions["item_id"].n_unique())

after item-core: (621417, 3)
after user-core: (620105, 3)
final filtered: (620105, 3)
users: 7102
items: 33145

## 3. ID mapping and leave-one-out split

In [ ]:
# User/item ids -> contiguous indices.
user_mapping = interactions.select("uid").unique().sort("uid").with_row_index(name="u_idx")
item_mapping = interactions.select("item_id").unique().sort("item_id").with_row_index(name="i_idx")

inter = (
    interactions
    .join(user_mapping, on="uid", how="inner")
    .join(item_mapping, on="item_id", how="inner")
    .select(["u_idx", "i_idx", "timestamp"])
    .sort(["u_idx", "timestamp"])
)

NUM_USERS = user_mapping.height
NUM_ITEMS = item_mapping.height

inter = inter.with_columns([
    pl.arange(0, pl.len()).over("u_idx").alias("pos"),
    pl.len().over("u_idx").alias("hist_len"),
])

# Leave-one-out evaluation with validation:
# most recent item -> test, second most recent -> validation, rest -> train.
train_df = inter.filter(pl.col("pos") < pl.col("hist_len") - 2).select(["u_idx", "i_idx"])
val_df   = inter.filter(pl.col("pos") == pl.col("hist_len") - 2).select(["u_idx", "i_idx"])
test_df  = inter.filter(pl.col("pos") == pl.col("hist_len") - 1).select(["u_idx", "i_idx"])

train_pairs = train_df.to_numpy().astype(np.int64)
val_np = val_df.to_numpy().astype(np.int64)
test_np = test_df.to_numpy().astype(np.int64)

val_u, val_i = val_np[:, 0], val_np[:, 1]
test_u, test_i = test_np[:, 0], test_np[:, 1]

print(f"NUM_USERS={NUM_USERS:,}")
print(f"NUM_ITEMS={NUM_ITEMS:,}")
print(f"train={len(train_pairs):,} val={len(val_u):,} test={len(test_u):,}")
print(f"catalog share @50 = {50 / NUM_ITEMS:.6f}")

assert len(train_pairs) > 0
assert len(val_u) == NUM_USERS
assert len(test_u) == NUM_USERS

NUM_USERS=7,102
NUM_ITEMS=33,145
train=605,901 val=7,102 test=7,102
catalog share @50 = 0.001509

## 4. Build item features: artist_id and album_id

In [ ]:
# item_mapping contains original item_id and new i_idx.
# Features are built in i_idx order.
item_features_df = item_mapping.select(["item_id", "i_idx"])


# ---------- artist feature ----------
artists = pl.read_parquet(ARTIST_PATH)
artists = normalize_item_side_columns(artists)

print("artists shape:", artists.shape)
print("artists columns:", artists.columns)

if "item_id" not in artists.columns or "artist_id" not in artists.columns:
    raise ValueError(f"Bad artist mapping columns: {artists.columns}")

# If an item has multiple artists, take the first one for a simple baseline.
artists_one = (
    artists
    .select(["item_id", "artist_id"])
    .drop_nulls(["item_id", "artist_id"])
    .group_by("item_id")
    .agg(pl.col("artist_id").first())
)

item_features_df = item_features_df.join(artists_one, on="item_id", how="left")


# ---------- album feature ----------
albums = pl.read_parquet(ALBUM_PATH)
albums = normalize_item_side_columns(albums)

print("albums shape:", albums.shape)
print("albums columns:", albums.columns)

if "item_id" not in albums.columns or "album_id" not in albums.columns:
    raise ValueError(f"Bad album mapping columns: {albums.columns}")

# If an item has multiple albums, take the first one for a simple baseline.
albums_one = (
    albums
    .select(["item_id", "album_id"])
    .drop_nulls(["item_id", "album_id"])
    .group_by("item_id")
    .agg(pl.col("album_id").first())
)

item_features_df = item_features_df.join(albums_one, on="item_id", how="left")


# ---------- categorical encoding ----------
item_features_df = item_features_df.sort("i_idx")

# unknown = 0, real categories = 1..N
unique_artists = (
    item_features_df
    .select("artist_id")
    .drop_nulls()
    .unique()
    .sort("artist_id")
    .with_row_index(name="artist_idx", offset=1)
)

item_features_df = (
    item_features_df
    .join(unique_artists, on="artist_id", how="left")
    .with_columns(pl.col("artist_idx").fill_null(0).cast(pl.Int64))
)

unique_albums = (
    item_features_df
    .select("album_id")
    .drop_nulls()
    .unique()
    .sort("album_id")
    .with_row_index(name="album_idx", offset=1)
)

item_features_df = (
    item_features_df
    .join(unique_albums, on="album_id", how="left")
    .with_columns(pl.col("album_idx").fill_null(0).cast(pl.Int64))
)

ITEM_ARTIST = item_features_df["artist_idx"].to_numpy().astype(np.int64)
ITEM_ALBUM = item_features_df["album_idx"].to_numpy().astype(np.int64)

NUM_ARTISTS = int(ITEM_ARTIST.max()) + 1
NUM_ALBUMS = int(ITEM_ALBUM.max()) + 1

print("NUM_ITEMS:", NUM_ITEMS)
print("NUM_ARTISTS:", NUM_ARTISTS)
print("NUM_ALBUMS:", NUM_ALBUMS)
print("artist unknown share:", float((ITEM_ARTIST == 0).mean()))
print("album unknown share:", float((ITEM_ALBUM == 0).mean()))

item_artist_t = torch.from_numpy(ITEM_ARTIST).long().to(device)
item_album_t = torch.from_numpy(ITEM_ALBUM).long().to(device)

artists shape: (9271906, 2)
artists columns: ['artist_id', 'item_id']
albums shape: (9651644, 2)
albums columns: ['album_id', 'item_id']
NUM_ITEMS: 33145
NUM_ARTISTS: 9321
NUM_ALBUMS: 23839
artist unknown share: 0.0
album unknown share: 3.017046311660884e-05

## 5. Known items and head/tail split

In [ ]:
train_user_items = [set() for _ in range(NUM_USERS)]

for u, i in train_pairs:
    train_user_items[int(u)].add(int(i))

known_val = [set(s) for s in train_user_items]
known_test = [set(s) for s in train_user_items]

# For test, validation item is already known and should be masked.
for u, i in zip(val_u, val_i):
    known_test[int(u)].add(int(i))

# Head/tail is computed only from train frequencies.
item_freq = np.bincount(train_pairs[:, 1], minlength=NUM_ITEMS)
order = np.argsort(-item_freq)

n_head = max(1, int(NUM_ITEMS * CFG["head_fraction"]))
head_mask = np.zeros(NUM_ITEMS, dtype=bool)
head_mask[order[:n_head]] = True

print(f"head={head_mask.sum():,} tail={(~head_mask).sum():,}")
print(f"nonzero train items={np.sum(item_freq > 0):,}")
print(f"zero train items={np.sum(item_freq == 0):,}")
print(f"val true head share={head_mask[val_i].mean():.4f}")
print(f"test true head share={head_mask[test_i].mean():.4f}")

head=6,629 tail=26,516
nonzero train items=33,145
zero train items=0
val true head share=0.5624
test true head share=0.5373

## 6. Dataset and model

In [ ]:
class PairDataset(Dataset):
    def __init__(self, pairs: np.ndarray):
        self.pairs = pairs

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        u, i = self.pairs[idx]
        return int(u), int(i)


class MLP(nn.Module):
    def __init__(self, in_dim: int, hidden: list[int], dropout: float = 0.0):
        super().__init__()

        layers = []
        d = in_dim

        for h in hidden:
            layers.append(nn.Linear(d, h))
            layers.append(nn.ReLU())

            if dropout > 0:
                layers.append(nn.Dropout(dropout))

            d = h

        self.net = nn.Sequential(*layers)
        self.out_dim = d

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class TwoTower(nn.Module):
    """
    Two-Tower baseline:
      user tower: user_id -> MLP
      item tower: item_id + artist_id + album_id -> MLP
    """
    def __init__(
        self,
        num_users: int,
        num_items: int,
        num_artists: int,
        num_albums: int,
        embed_dim: int = 64,
        artist_emb_dim: int = 32,
        album_emb_dim: int = 32,
        hidden: list[int] = [256, 128, 64],
        dropout: float = 0.0,
    ):
        super().__init__()

        self.user_emb = nn.Embedding(num_users, embed_dim)

        self.item_emb = nn.Embedding(num_items, embed_dim)
        self.artist_emb = nn.Embedding(num_artists, artist_emb_dim)
        self.album_emb = nn.Embedding(num_albums, album_emb_dim)

        user_in_dim = embed_dim
        item_in_dim = embed_dim + artist_emb_dim + album_emb_dim

        self.user_mlp = MLP(user_in_dim, hidden, dropout)
        self.item_mlp = MLP(item_in_dim, hidden, dropout)

        self.user_ln = nn.LayerNorm(self.user_mlp.out_dim)
        self.item_ln = nn.LayerNorm(self.item_mlp.out_dim)

        self.init_weights()

    def init_weights(self):
        for emb in [self.user_emb, self.item_emb, self.artist_emb, self.album_emb]:
            nn.init.normal_(emb.weight, std=0.01)

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def user_vec(self, u: torch.Tensor) -> torch.Tensor:
        x = self.user_emb(u)
        x = self.user_mlp(x)
        x = self.user_ln(x)
        return x

    def item_vec(self, i: torch.Tensor) -> torch.Tensor:
        item_id_vec = self.item_emb(i)
        artist_vec = self.artist_emb(item_artist_t[i])
        album_vec = self.album_emb(item_album_t[i])

        x = torch.cat([item_id_vec, artist_vec, album_vec], dim=-1)
        x = self.item_mlp(x)
        x = self.item_ln(x)
        return x

    def forward(self, u: torch.Tensor, i: torch.Tensor) -> torch.Tensor:
        uv = F.normalize(self.user_vec(u), dim=-1, eps=1e-6)
        iv = F.normalize(self.item_vec(i), dim=-1, eps=1e-6)
        return (uv * iv).sum(dim=-1)


def inbatch_softmax_loss(user_vecs: torch.Tensor, item_vecs: torch.Tensor):
    u = F.normalize(user_vecs, dim=-1, eps=1e-6)
    v = F.normalize(item_vecs, dim=-1, eps=1e-6)

    logits = u @ v.T
    labels = torch.arange(logits.size(0), device=logits.device)

    return F.cross_entropy(logits, labels)


train_loader = DataLoader(
    PairDataset(train_pairs),
    batch_size=CFG["batch_size"],
    shuffle=True,
    drop_last=True,
    pin_memory=torch.cuda.is_available(),
)

model = TwoTower(
    NUM_USERS,
    NUM_ITEMS,
    NUM_ARTISTS,
    NUM_ALBUMS,
    embed_dim=CFG["embed_dim"],
    artist_emb_dim=CFG["artist_emb_dim"],
    album_emb_dim=CFG["album_emb_dim"],
    hidden=CFG["tower_hidden"],
    dropout=CFG["dropout"],
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=CFG["lr"],
    weight_decay=CFG["weight_decay"],
)

print(model)

TwoTower(
  (user_emb): Embedding(7102, 64)
  (item_emb): Embedding(33145, 64)
  (artist_emb): Embedding(9321, 32)
  (album_emb): Embedding(23839, 32)
  (user_mlp): MLP(
    (net): Sequential(
      (0): Linear(in_features=64, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=128, bias=True)
      (3): ReLU()
      (4): Linear(in_features=128, out_features=64, bias=True)
      (5): ReLU()
    )
  )
  (item_mlp): MLP(
    (net): Sequential(
      (0): Linear(in_features=128, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=128, bias=True)
      (3): ReLU()
      (4): Linear(in_features=128, out_features=64, bias=True)
      (5): ReLU()
    )
  )
  (user_ln): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
  (item_ln): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
)

## 7. Evaluation

In [ ]:
@torch.no_grad()
def evaluate_full_corpus(
    model: nn.Module,
    users: np.ndarray,
    true_items: np.ndarray,
    known_user_items: List[set],
    head_mask: np.ndarray,
    ks: List[int],
    item_freq: np.ndarray,
    user_batch_size: int = 128,
    item_batch_size: int = 8192,
):
    model.eval()

    ranks_all = []
    ranks_head = []
    ranks_tail = []

    max_k = max(ks)

    # Для coverage / popularity / personalization
    recommended_by_k = {k: [] for k in ks}

    # ============================================================
    # 1. Считаем вектора всех items один раз
    # ============================================================

    item_vectors = []

    for s in tqdm(
        range(0, NUM_ITEMS, item_batch_size),
        desc="item vectors",
        leave=False,
    ):
        e = min(s + item_batch_size, NUM_ITEMS)
        idx = torch.arange(s, e, device=device)

        v = model.item_vec(idx)
        v = F.normalize(v, dim=-1, eps=1e-6)

        if not torch.isfinite(v).all():
            raise RuntimeError(f"Non-finite item vectors on item batch {s}:{e}")

        item_vectors.append(v.cpu())

    item_vectors = torch.cat(item_vectors, dim=0).to(device)

    if not torch.isfinite(item_vectors).all():
        raise RuntimeError("Non-finite item vectors after concat")

    # ============================================================
    # 2. Идём по пользователям батчами
    # ============================================================

    for start in tqdm(
        range(0, len(users), user_batch_size),
        desc="eval users",
        leave=False,
    ):
        end = min(start + user_batch_size, len(users))

        bu = users[start:end]
        bi = true_items[start:end]

        ut = torch.tensor(bu, device=device, dtype=torch.long)

        uvec = model.user_vec(ut)
        uvec = F.normalize(uvec, dim=-1, eps=1e-6)

        if not torch.isfinite(uvec).all():
            raise RuntimeError(f"Non-finite user vectors on user batch {start}:{end}")

        scores = (uvec @ item_vectors.T).cpu().numpy()

        if not np.isfinite(scores).all():
            bad = np.sum(~np.isfinite(scores))
            raise RuntimeError(
                f"Non-finite scores in user batch {start}:{end}: {bad} bad values"
            )

        # ========================================================
        # 3. Для каждого пользователя считаем rank и top-K
        # ========================================================

        for row, (u, true_i) in enumerate(zip(bu, bi)):
            u = int(u)
            true_i = int(true_i)

            srow = scores[row].copy()

            if true_i < 0 or true_i >= NUM_ITEMS:
                raise RuntimeError(
                    f"true_i out of bounds: user={u}, true_i={true_i}, NUM_ITEMS={NUM_ITEMS}"
                )

            if not np.isfinite(srow[true_i]):
                raise RuntimeError(
                    f"Non-finite true item score: user={u}, item={true_i}"
                )

            # Маскируем уже известные items пользователя
            for it in known_user_items[u]:
                if it != true_i:
                    srow[it] = -1e9

            if not np.isfinite(srow[true_i]):
                raise RuntimeError(
                    f"True item was masked or became non-finite: user={u}, item={true_i}"
                )

            # ----------------------------------------------------
            # Rank true item
            # pessimistic tie handling:
            # если у многих items одинаковый score, true item НЕ считается первым
            # ----------------------------------------------------

            true_score = srow[true_i]
            eps = 1e-12

            num_greater = int((srow > true_score + eps).sum())
            num_tied = int((np.abs(srow - true_score) <= eps).sum())

            rank = num_greater + num_tied - 1

            ranks_all.append(rank)

            if head_mask[true_i]:
                ranks_head.append(rank)
            else:
                ranks_tail.append(rank)

            # ----------------------------------------------------
            # Top-K recommendations для coverage/popularity
            # ----------------------------------------------------

            if max_k < len(srow):
                top_unsorted = np.argpartition(-srow, max_k - 1)[:max_k]
                top_idx = top_unsorted[np.argsort(-srow[top_unsorted])]
            else:
                top_idx = np.argsort(-srow)

            for k in ks:
                recommended_by_k[k].append(top_idx[:k].astype(np.int64))

    # ============================================================
    # 4. Accuracy metrics: HR / NDCG
    # ============================================================

    def agg_accuracy(ranks: List[int]) -> Dict[str, float]:
        a = np.asarray(ranks, dtype=np.int64)
        out = {}

        for k in ks:
            if len(a) == 0:
                out[f"HR@{k}"] = np.nan
                out[f"NDCG@{k}"] = np.nan
            else:
                hits = a < k

                out[f"HR@{k}"] = 100.0 * hits.mean()

                out[f"NDCG@{k}"] = 100.0 * np.where(
                    hits,
                    1.0 / np.log2(a + 2),
                    0.0,
                ).mean()

        return out

    # ============================================================
    # 5. Long-tail / coverage metrics
    # ============================================================

    tail_mask = ~head_mask
    num_tail_items = int(tail_mask.sum())

    # item_freq нужен именно здесь
    popularity = np.log1p(item_freq.astype(np.float64))

    long_tail_metrics = {}

    for k in ks:
        recs = np.vstack(recommended_by_k[k])  # shape: (num_eval_users, k)

        unique_recs = np.unique(recs)

        # CatalogCoverage@K
        catalog_coverage = len(unique_recs) / NUM_ITEMS

        # TailCoverage@K
        if num_tail_items > 0:
            tail_coverage = np.sum(tail_mask[unique_recs]) / num_tail_items
        else:
            tail_coverage = np.nan

        # AvgPopularity@K
        avg_popularity = popularity[recs].mean()

        # TailRatio@K
        tail_ratio = tail_mask[recs].mean()

        # Personalization@K
        # 1 - average pairwise overlap / K
        # считаем эффективно через exposure counts
        n_users_eval = recs.shape[0]

        if n_users_eval <= 1:
            personalization = np.nan
        else:
            exposure_counts = np.bincount(
                recs.reshape(-1),
                minlength=NUM_ITEMS,
            )

            pairwise_intersections = np.sum(
                exposure_counts * (exposure_counts - 1) / 2
            )

            num_user_pairs = n_users_eval * (n_users_eval - 1) / 2
            avg_overlap = pairwise_intersections / num_user_pairs

            personalization = 1.0 - avg_overlap / k

        long_tail_metrics[f"CatalogCoverage@{k}"] = 100.0 * catalog_coverage
        long_tail_metrics[f"TailCoverage@{k}"] = 100.0 * tail_coverage
        long_tail_metrics[f"AvgPopularity@{k}"] = float(avg_popularity)
        long_tail_metrics[f"TailRatio@{k}"] = 100.0 * tail_ratio
        long_tail_metrics[f"Personalization@{k}"] = 100.0 * personalization

    return {
        "overall": agg_accuracy(ranks_all),
        "head": agg_accuracy(ranks_head),
        "tail": agg_accuracy(ranks_tail),
        "long_tail": long_tail_metrics,
        "counts": {
            "overall": len(ranks_all),
            "head": len(ranks_head),
            "tail": len(ranks_tail),
        },
    }


def print_metrics(metrics: Dict):
    print("counts:", metrics.get("counts", {}))

    for split in ["overall", "head", "tail"]:
        print(f"[{split}]", metrics[split])

    if "long_tail" in metrics:
        print("[long_tail]", metrics["long_tail"])

In [ ]:
def make_head_mask(item_freq: np.ndarray, head_fraction: float) -> np.ndarray:
    num_items = len(item_freq)
    n_head = max(1, int(num_items * head_fraction))

    order = np.argsort(-item_freq)

    current_head_mask = np.zeros(num_items, dtype=bool)
    current_head_mask[order[:n_head]] = True

    return current_head_mask


@torch.no_grad()
def evaluate_head_tail_sweep(
    model: nn.Module,
    method_name: str,
    seed: int,
    head_fractions: List[float],
    test_u: np.ndarray,
    test_i: np.ndarray,
    known_test: List[set],
    item_freq: np.ndarray,
    ks: List[int],
):
    rows = []

    model.eval()

    for hf in head_fractions:
        print("\n" + "=" * 80)
        print(f"{method_name} | seed={seed} | head_fraction={hf} ({100 * hf:.3f}%)")
        print("=" * 80)

        current_head_mask = make_head_mask(
            item_freq=item_freq,
            head_fraction=hf,
        )

        num_head_items = int(current_head_mask.sum())
        num_tail_items = int((~current_head_mask).sum())

        test_head_share = float(current_head_mask[test_i].mean())
        test_tail_share = float((~current_head_mask[test_i]).mean())

        print(f"num_head_items: {num_head_items:,}")
        print(f"num_tail_items: {num_tail_items:,}")
        print(f"test_head_share: {test_head_share:.4f}")
        print(f"test_tail_share: {test_tail_share:.4f}")

        metrics = evaluate_full_corpus(
            model=model,
            users=test_u,
            true_items=test_i,
            known_user_items=known_test,
            head_mask=current_head_mask,
            ks=ks,
            item_freq=item_freq,
            user_batch_size=CFG["eval_batch_users"],
            item_batch_size=CFG["eval_item_batch"],
        )

        print_metrics(metrics)

        row = {
            "method": method_name,
            "seed": seed,
            "head_fraction": hf,
            "head_percent": 100.0 * hf,
            "num_head_items": num_head_items,
            "num_tail_items": num_tail_items,
            "test_head_share": test_head_share,
            "test_tail_share": test_tail_share,
        }

        for split in ("overall", "head", "tail"):
            for key, value in metrics[split].items():
                row[f"{split}_{key}"] = value

        if "long_tail" in metrics:
            for key, value in metrics["long_tail"].items():
                row[key] = value

        if "counts" in metrics:
            for key, value in metrics["counts"].items():
                row[f"count_{key}"] = value

        rows.append(row)

    return rows

In [ ]:
# Override method-specific config
CFG["cache_path"] = "best_hparams_yambda_classbalance.json"
CFG["cb_beta"] = 0.9999

## 8. ClassBalance loss

In [ ]:
def build_classbalance_weights(item_freq: np.ndarray, beta: float = 0.9999) -> torch.Tensor:
    freq = item_freq.astype(np.float64)
    weights = np.zeros_like(freq, dtype=np.float64)
    seen = freq > 0

    weights[seen] = (1.0 - beta) / (1.0 - np.power(beta, freq[seen]))

    # Normalize so that average weight over train positives is close to 1.
    denom = np.sum(freq[seen] * weights[seen]) / np.sum(freq[seen])
    weights[seen] = weights[seen] / max(denom, 1e-12)

    return torch.from_numpy(weights.astype(np.float32))


cb_item_weights = build_classbalance_weights(item_freq, beta=CFG["cb_beta"]).to(device)

print("ClassBalance weights")
print("  beta:", CFG["cb_beta"])
print("  min seen:", float(cb_item_weights[cb_item_weights > 0].min().item()))
print("  max seen:", float(cb_item_weights.max().item()))
print("  mean over train positives:", float(cb_item_weights[torch.from_numpy(train_pairs[:, 1]).long().to(device)].mean().item()))


def classbalance_inbatch_softmax_loss(
    user_vecs: torch.Tensor,
    item_vecs: torch.Tensor,
    pos_items: torch.Tensor,
    item_weights: torch.Tensor,
):
    u = F.normalize(user_vecs, dim=-1, eps=1e-6)
    v = F.normalize(item_vecs, dim=-1, eps=1e-6)

    logits = u @ v.T
    labels = torch.arange(logits.size(0), device=logits.device)

    per_example_loss = F.cross_entropy(logits, labels, reduction="none")
    w = item_weights[pos_items].detach()

    return (per_example_loss * w).sum() / w.sum().clamp_min(1e-12)

ClassBalance weights
  beta: 0.9999
  min seen: 0.02537386119365692
  max seen: 18.264514923095703
  mean over train positives: 1.0

## 9. Grid search

In [ ]:
LR_GRID = [0.1, 0.01, 0.001, 0.0001]
DROPOUT_GRID = [0.1, 0.3, 0.5, 0.7, 0.9]
WD_GRID = [0.0, 0.1, 0.01, 0.001]

combos = list(itertools.product(LR_GRID, DROPOUT_GRID, WD_GRID))
k_main = CFG["eval_k"][-1]

cache_path = Path(CFG["cache_path"])
leaderboard_csv_path = cache_path.with_suffix(".leaderboard.csv")

if CFG["skip_tune_if_cached"] and cache_path.exists():
    best_hp = json.loads(cache_path.read_text())
    print(f"Loaded cached hparams: {best_hp}")
    leaderboard_df = pd.read_csv(leaderboard_csv_path) if leaderboard_csv_path.exists() else None
else:
    frac = float(CFG.get("tune_val_fraction", 1.0))
    if frac < 1.0 and CFG["tune_fast"]:
        n_tune = max(1, int(len(val_u) * frac))
        _idx = np.random.default_rng(42).choice(len(val_u), n_tune, replace=False)
        val_u_t, val_i_t = val_u[_idx], val_i[_idx]
    else:
        val_u_t, val_i_t = val_u, val_i

    tune_ep = CFG["tune_epochs"] if CFG["tune_fast"] else CFG["final_epochs"]

    print(f"Tuning ClassBalance {len(combos)} trials × {tune_ep} ep (val subset: {len(val_u_t):,}/{len(val_u):,})")

    best_hr = -1.0
    best_hp = None
    leaderboard = []

    for ti, (lr, dr, wd) in enumerate(combos, 1):
        set_seed(CFG["seed"])

        m = TwoTower(
            NUM_USERS, NUM_ITEMS, NUM_ARTISTS, NUM_ALBUMS,
            embed_dim=CFG["embed_dim"],
            artist_emb_dim=CFG["artist_emb_dim"],
            album_emb_dim=CFG["album_emb_dim"],
            hidden=CFG["tower_hidden"],
            dropout=dr,
        ).to(device)

        opt = torch.optim.Adam(m.parameters(), lr=lr, weight_decay=wd)

        status = "ok"
        error_message = ""
        avg_loss = np.nan
        met = None
        hr = -1.0

        try:
            for ep in range(1, tune_ep + 1):
                m.train()
                total_loss, total_n = 0.0, 0
                pbar = tqdm(train_loader, desc=f"CB trial{ti} {ep}/{tune_ep}", leave=False)

                for users_batch, items_batch in pbar:
                    users_batch = users_batch.to(device, non_blocking=True)
                    items_batch = items_batch.to(device, non_blocking=True)

                    user_vecs = m.user_vec(users_batch)
                    item_vecs = m.item_vec(items_batch)

                    loss = classbalance_inbatch_softmax_loss(
                        user_vecs=user_vecs,
                        item_vecs=item_vecs,
                        pos_items=items_batch,
                        item_weights=cb_item_weights,
                    )

                    if not torch.isfinite(loss):
                        raise RuntimeError(f"Non-finite loss: {loss.item()}")

                    opt.zero_grad(set_to_none=True)
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(m.parameters(), CFG["grad_clip"])
                    opt.step()

                    bs = users_batch.size(0)
                    total_loss += loss.item() * bs
                    total_n += bs
                    pbar.set_postfix(loss=f"{loss.item():.4f}")

                avg_loss = total_loss / max(total_n, 1)
                print(f"  CB trial{ti} ep{ep} loss={avg_loss:.4f}")

            met = evaluate_full_corpus(
                model=m,
                users=val_u_t,
                true_items=val_i_t,
                known_user_items=known_val,
                head_mask=head_mask,
                ks=CFG["eval_k"],
                item_freq=item_freq,
                user_batch_size=CFG["eval_batch_users"],
                item_batch_size=CFG["eval_item_batch"],
            )
            hr = met["overall"][f"HR@{k_main}"]
            if not np.isfinite(hr):
                raise RuntimeError(f"Non-finite HR: {hr}")
        except RuntimeError as e:
            status = "failed"
            error_message = str(e)
            print(f"  CB trial {ti} FAILED: {e}")

        row = {
            "trial": ti,
            "status": status,
            "error": error_message,
            "method": "ClassBalance",
            "lr": lr,
            "dropout": dr,
            "weight_decay": wd,
            "cb_beta": CFG["cb_beta"],
            "tune_epochs": tune_ep,
            "val_subset_size": len(val_u_t),
            "val_full_size": len(val_u),
            "final_train_loss": avg_loss,
            f"val_HR@{k_main}": hr,
        }

        if met is not None:
            for split in ("overall", "head", "tail"):
                for key, value in met[split].items():
                    row[f"val_{split}_{key}"] = value
            if "long_tail" in met:
                for key, value in met["long_tail"].items():
                    row[f"val_{key}"] = value
            if "counts" in met:
                for key, value in met["counts"].items():
                    row[f"val_count_{key}"] = value

        leaderboard.append(row)
        print(f"  CB trial {ti:3d}/{len(combos)} lr={lr:.0e} dr={dr} wd={wd:.0e} -> val HR@{k_main}={hr:.2f}%")

        if status == "ok" and hr > best_hr:
            best_hr = hr
            best_hp = {"lr": lr, "dropout": dr, "weight_decay": wd, "cb_beta": CFG["cb_beta"], f"val_HR@{k_main}": hr}

        del m, opt
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    leaderboard_df = pd.DataFrame(leaderboard).sort_values(f"val_HR@{k_main}", ascending=False, na_position="last")
    leaderboard_df.to_csv(leaderboard_csv_path, index=False)

    if best_hp is None:
        raise RuntimeError("No successful grid-search trial. Check leaderboard for errors.")

    cache_path.write_text(json.dumps(best_hp, indent=2))
    print(f"\nBest ClassBalance val HR@{k_main}={best_hr:.2f}% -> {best_hp}")
    print(f"Saved best hparams: {cache_path}")
    print(f"Saved leaderboard CSV: {leaderboard_csv_path}")

leaderboard_df.head(10) if leaderboard_df is not None else None

Tuning ClassBalance 60 trials × 3 ep (val subset: 7,102/7,102)

  CB trial1 ep1 loss=8.0800

  CB trial1 ep2 loss=7.9175

  CB trial1 ep3 loss=7.9044

  CB trial   1/60 lr=1e-04 dr=0.0 wd=0e+00 -> val HR@50=0.10%

  CB trial2 ep1 loss=8.0696

  CB trial2 ep2 loss=7.9183

  CB trial2 ep3 loss=7.9046

  CB trial   2/60 lr=1e-04 dr=0.0 wd=1e-04 -> val HR@50=0.17%

  CB trial3 ep1 loss=8.0696

  CB trial3 ep2 loss=7.9195

  CB trial3 ep3 loss=7.9106

  CB trial   3/60 lr=1e-04 dr=0.0 wd=1e-03 -> val HR@50=0.17%

  CB trial4 ep1 loss=8.1347

  CB trial4 ep2 loss=7.9642

  CB trial4 ep3 loss=7.9477

  CB trial   4/60 lr=1e-04 dr=0.1 wd=0e+00 -> val HR@50=0.06%

  CB trial5 ep1 loss=8.1256

  CB trial5 ep2 loss=7.9618

  CB trial5 ep3 loss=7.9453

  CB trial   5/60 lr=1e-04 dr=0.1 wd=1e-04 -> val HR@50=0.11%

  CB trial6 ep1 loss=8.1249

  CB trial6 ep2 loss=7.9609

  CB trial6 ep3 loss=7.9443

  CB trial   6/60 lr=1e-04 dr=0.1 wd=1e-03 -> val HR@50=0.07%

  CB trial7 ep1 loss=8.1843

  CB trial7 ep2 loss=8.0051

  CB trial7 ep3 loss=7.9821

  CB trial   7/60 lr=1e-04 dr=0.2 wd=0e+00 -> val HR@50=0.03%

  CB trial8 ep1 loss=8.1767

  CB trial8 ep2 loss=8.0034

  CB trial8 ep3 loss=7.9811

  CB trial   8/60 lr=1e-04 dr=0.2 wd=1e-04 -> val HR@50=0.06%

  CB trial9 ep1 loss=8.1752

  CB trial9 ep2 loss=8.0021

  CB trial9 ep3 loss=7.9819

  CB trial   9/60 lr=1e-04 dr=0.2 wd=1e-03 -> val HR@50=0.08%

  CB trial10 ep1 loss=8.2433

  CB trial10 ep2 loss=8.0572

  CB trial10 ep3 loss=8.0256

  CB trial  10/60 lr=1e-04 dr=0.3 wd=0e+00 -> val HR@50=0.11%

  CB trial11 ep1 loss=8.2341

  CB trial11 ep2 loss=8.0566

  CB trial11 ep3 loss=8.0248

  CB trial  11/60 lr=1e-04 dr=0.3 wd=1e-04 -> val HR@50=0.08%

  CB trial12 ep1 loss=8.2325

  CB trial12 ep2 loss=8.0539

  CB trial12 ep3 loss=8.0256

  CB trial  12/60 lr=1e-04 dr=0.3 wd=1e-03 -> val HR@50=0.08%

  CB trial13 ep1 loss=8.3185

  CB trial13 ep2 loss=8.2361

  CB trial13 ep3 loss=8.1307

  CB trial  13/60 lr=1e-04 dr=0.5 wd=0e+00 -> val HR@50=0.08%

  CB trial14 ep1 loss=8.3180

  CB trial14 ep2 loss=8.2169

  CB trial14 ep3 loss=8.1273

  CB trial  14/60 lr=1e-04 dr=0.5 wd=1e-04 -> val HR@50=0.07%

  CB trial15 ep1 loss=8.3179

  CB trial15 ep2 loss=8.2088

  CB trial15 ep3 loss=8.1224

  CB trial  15/60 lr=1e-04 dr=0.5 wd=1e-03 -> val HR@50=0.11%

  CB trial16 ep1 loss=7.9551

  CB trial16 ep2 loss=7.8267

  CB trial16 ep3 loss=7.7400

  CB trial  16/60 lr=1e-03 dr=0.0 wd=0e+00 -> val HR@50=0.25%

  CB trial17 ep1 loss=7.9498

  CB trial17 ep2 loss=7.8331

  CB trial17 ep3 loss=7.7466

  CB trial  17/60 lr=1e-03 dr=0.0 wd=1e-04 -> val HR@50=0.28%

  CB trial18 ep1 loss=7.9573

  CB trial18 ep2 loss=7.9167

  CB trial18 ep3 loss=7.9199

  CB trial  18/60 lr=1e-03 dr=0.0 wd=1e-03 -> val HR@50=0.04%

  CB trial19 ep1 loss=7.9881

  CB trial19 ep2 loss=7.9260

  CB trial19 ep3 loss=7.8557

  CB trial  19/60 lr=1e-03 dr=0.1 wd=0e+00 -> val HR@50=0.11%

  CB trial20 ep1 loss=7.9840

  CB trial20 ep2 loss=7.9305

  CB trial20 ep3 loss=7.8589

  CB trial  20/60 lr=1e-03 dr=0.1 wd=1e-04 -> val HR@50=0.08%

  CB trial21 ep1 loss=7.9901

  CB trial21 ep2 loss=7.9429

  CB trial21 ep3 loss=7.9411

  CB trial  21/60 lr=1e-03 dr=0.1 wd=1e-03 -> val HR@50=0.07%

  CB trial22 ep1 loss=8.0274

  CB trial22 ep2 loss=7.9604

  CB trial22 ep3 loss=7.9501

  CB trial  22/60 lr=1e-03 dr=0.2 wd=0e+00 -> val HR@50=0.11%

  CB trial23 ep1 loss=8.0218

  CB trial23 ep2 loss=7.9614

  CB trial23 ep3 loss=7.9516

  CB trial  23/60 lr=1e-03 dr=0.2 wd=1e-04 -> val HR@50=0.07%

  CB trial24 ep1 loss=8.0266

  CB trial24 ep2 loss=7.9700

  CB trial24 ep3 loss=7.9608

  CB trial  24/60 lr=1e-03 dr=0.2 wd=1e-03 -> val HR@50=0.13%

  CB trial25 ep1 loss=8.0716

  CB trial25 ep2 loss=7.9985

  CB trial25 ep3 loss=7.9813

  CB trial  25/60 lr=1e-03 dr=0.3 wd=0e+00 -> val HR@50=0.06%

  CB trial26 ep1 loss=8.0650

  CB trial26 ep2 loss=7.9998

  CB trial26 ep3 loss=7.9840

  CB trial  26/60 lr=1e-03 dr=0.3 wd=1e-04 -> val HR@50=0.08%

  CB trial27 ep1 loss=8.0712

  CB trial27 ep2 loss=8.0165

  CB trial27 ep3 loss=7.9916

  CB trial  27/60 lr=1e-03 dr=0.3 wd=1e-03 -> val HR@50=0.08%

  CB trial28 ep1 loss=8.1682

  CB trial28 ep2 loss=8.0771

  CB trial28 ep3 loss=8.0558

  CB trial  28/60 lr=1e-03 dr=0.5 wd=0e+00 -> val HR@50=0.08%

  CB trial29 ep1 loss=8.1504

  CB trial29 ep2 loss=8.0724

  CB trial29 ep3 loss=8.0482

  CB trial  29/60 lr=1e-03 dr=0.5 wd=1e-04 -> val HR@50=0.11%

  CB trial30 ep1 loss=8.1547

  CB trial30 ep2 loss=8.0901

  CB trial30 ep3 loss=8.0683

  CB trial  30/60 lr=1e-03 dr=0.5 wd=1e-03 -> val HR@50=0.00%

  CB trial31 ep1 loss=7.9310

  CB trial31 ep2 loss=7.7848

  CB trial31 ep3 loss=7.7260

  CB trial  31/60 lr=3e-03 dr=0.0 wd=0e+00 -> val HR@50=0.24%

  CB trial32 ep1 loss=7.9402

  CB trial32 ep2 loss=7.8206

  CB trial32 ep3 loss=7.7497

  CB trial  32/60 lr=3e-03 dr=0.0 wd=1e-04 -> val HR@50=0.24%

  CB trial33 ep1 loss=7.9584

  CB trial33 ep2 loss=7.9213

  CB trial33 ep3 loss=7.9259

  CB trial  33/60 lr=3e-03 dr=0.0 wd=1e-03 -> val HR@50=0.08%

  CB trial34 ep1 loss=7.9700

  CB trial34 ep2 loss=7.9131

  CB trial34 ep3 loss=7.8391

  CB trial  34/60 lr=3e-03 dr=0.1 wd=0e+00 -> val HR@50=0.13%

  CB trial35 ep1 loss=7.9698

  CB trial35 ep2 loss=7.9286

  CB trial35 ep3 loss=7.9168

  CB trial  35/60 lr=3e-03 dr=0.1 wd=1e-04 -> val HR@50=0.13%

  CB trial36 ep1 loss=7.9857

  CB trial36 ep2 loss=7.9409

  CB trial36 ep3 loss=7.9324

  CB trial  36/60 lr=3e-03 dr=0.1 wd=1e-03 -> val HR@50=0.03%

  CB trial37 ep1 loss=8.0065

  CB trial37 ep2 loss=7.9490

  CB trial37 ep3 loss=7.9333

  CB trial  37/60 lr=3e-03 dr=0.2 wd=0e+00 -> val HR@50=0.06%

  CB trial38 ep1 loss=8.0038

  CB trial38 ep2 loss=7.9520

  CB trial38 ep3 loss=7.9257

  CB trial  38/60 lr=3e-03 dr=0.2 wd=1e-04 -> val HR@50=0.10%

  CB trial39 ep1 loss=8.0165

  CB trial39 ep2 loss=7.9589

  CB trial39 ep3 loss=7.9309

  CB trial  39/60 lr=3e-03 dr=0.2 wd=1e-03 -> val HR@50=0.08%

  CB trial40 ep1 loss=8.0540

  CB trial40 ep2 loss=7.9804

  CB trial40 ep3 loss=7.9325

  CB trial  40/60 lr=3e-03 dr=0.3 wd=0e+00 -> val HR@50=0.10%

  CB trial41 ep1 loss=8.0504

  CB trial41 ep2 loss=7.9733

  CB trial41 ep3 loss=7.9314

  CB trial  41/60 lr=3e-03 dr=0.3 wd=1e-04 -> val HR@50=0.04%

  CB trial42 ep1 loss=8.0613

  CB trial42 ep2 loss=8.0098

  CB trial42 ep3 loss=7.9500

  CB trial  42/60 lr=3e-03 dr=0.3 wd=1e-03 -> val HR@50=0.08%

  CB trial43 ep1 loss=8.1278

  CB trial43 ep2 loss=8.0411

  CB trial43 ep3 loss=7.9923

  CB trial  43/60 lr=3e-03 dr=0.5 wd=0e+00 -> val HR@50=0.03%

  CB trial44 ep1 loss=8.1243

  CB trial44 ep2 loss=8.0441

  CB trial44 ep3 loss=7.9621

  CB trial  44/60 lr=3e-03 dr=0.5 wd=1e-04 -> val HR@50=0.07%

  CB trial45 ep1 loss=8.1389

  CB trial45 ep2 loss=8.0352

  CB trial45 ep3 loss=7.9757

  CB trial  45/60 lr=3e-03 dr=0.5 wd=1e-03 -> val HR@50=0.00%

  CB trial46 ep1 loss=7.9333

  CB trial46 ep2 loss=7.8307

  CB trial46 ep3 loss=7.7433

  CB trial  46/60 lr=1e-02 dr=0.0 wd=0e+00 -> val HR@50=0.18%

  CB trial47 ep1 loss=7.9512

  CB trial47 ep2 loss=7.9162

  CB trial47 ep3 loss=7.9110

  CB trial  47/60 lr=1e-02 dr=0.0 wd=1e-04 -> val HR@50=0.11%

  CB trial48 ep1 loss=8.0101

  CB trial48 ep2 loss=7.9468

  CB trial48 ep3 loss=7.9390

  CB trial  48/60 lr=1e-02 dr=0.0 wd=1e-03 -> val HR@50=0.07%

  CB trial49 ep1 loss=7.9618

  CB trial49 ep2 loss=7.9063

  CB trial49 ep3 loss=7.8406

  CB trial  49/60 lr=1e-02 dr=0.1 wd=0e+00 -> val HR@50=0.11%

  CB trial50 ep1 loss=7.9778

  CB trial50 ep2 loss=7.9288

  CB trial50 ep3 loss=7.9191

  CB trial  50/60 lr=1e-02 dr=0.1 wd=1e-04 -> val HR@50=0.13%

  CB trial51 ep1 loss=8.0057

  CB trial51 ep2 loss=7.9472

  CB trial51 ep3 loss=7.9429

  CB trial  51/60 lr=1e-02 dr=0.1 wd=1e-03 -> val HR@50=0.06%

  CB trial52 ep1 loss=7.9922

  CB trial52 ep2 loss=7.9204

  CB trial52 ep3 loss=7.9112

  CB trial  52/60 lr=1e-02 dr=0.2 wd=0e+00 -> val HR@50=0.13%

  CB trial53 ep1 loss=7.9956

  CB trial53 ep2 loss=7.9344

  CB trial53 ep3 loss=7.9258

  CB trial  53/60 lr=1e-02 dr=0.2 wd=1e-04 -> val HR@50=0.11%

  CB trial54 ep1 loss=8.0181

  CB trial54 ep2 loss=7.9521

  CB trial54 ep3 loss=7.9547

  CB trial  54/60 lr=1e-02 dr=0.2 wd=1e-03 -> val HR@50=0.04%

  CB trial55 ep1 loss=8.0246

  CB trial55 ep2 loss=7.9257

  CB trial55 ep3 loss=7.9168

  CB trial  55/60 lr=1e-02 dr=0.3 wd=0e+00 -> val HR@50=0.10%

  CB trial56 ep1 loss=8.0254

  CB trial56 ep2 loss=7.9421

  CB trial56 ep3 loss=7.9358

  CB trial  56/60 lr=1e-02 dr=0.3 wd=1e-04 -> val HR@50=0.08%

  CB trial57 ep1 loss=8.0471

  CB trial57 ep2 loss=7.9607

  CB trial57 ep3 loss=7.9551

  CB trial  57/60 lr=1e-02 dr=0.3 wd=1e-03 -> val HR@50=0.06%

  CB trial58 ep1 loss=8.0829

  CB trial58 ep2 loss=7.9516

  CB trial58 ep3 loss=7.9304

  CB trial  58/60 lr=1e-02 dr=0.5 wd=0e+00 -> val HR@50=0.03%

  CB trial59 ep1 loss=8.0843

  CB trial59 ep2 loss=7.9641

  CB trial59 ep3 loss=7.9532

  CB trial  59/60 lr=1e-02 dr=0.5 wd=1e-04 -> val HR@50=0.07%

  CB trial60 ep1 loss=8.0893

  CB trial60 ep2 loss=7.9812

  CB trial60 ep3 loss=7.9679

  CB trial  60/60 lr=1e-02 dr=0.5 wd=1e-03 -> val HR@50=0.10%

Best ClassBalance val HR@50=0.28% -> {'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0001, 'cb_beta': 0.9999, 'val_HR@50': 0.28161081385525205}
Saved best hparams: best_hparams_yambda_classbalance.json
Saved leaderboard CSV: best_hparams_yambda_classbalance.leaderboard.csv

,trial,status,error,method,lr,dropout,weight_decay,cb_beta,tune_epochs,val_subset_size,...,val_TailRatio@10,val_Personalization@10,val_CatalogCoverage@50,val_TailCoverage@50,val_AvgPopularity@50,val_TailRatio@50,val_Personalization@50,val_count_overall,val_count_head,val_count_tail
16,17,ok,,ClassBalance,0.0010,0.0,0.0001,0.9999,3,7102,...,99.957758,99.729453,51.446674,63.701162,2.002934,99.951845,99.456669,7102,3994,3108
15,16,ok,,ClassBalance,0.0010,0.0,0.0000,0.9999,3,7102,...,98.945368,99.819792,55.269271,65.681098,2.016496,98.980287,99.569755,7102,3994,3108
30,31,ok,,ClassBalance,0.0030,0.0,0.0000,0.9999,3,7102,...,98.165306,99.887235,64.757882,73.619701,2.056689,98.104478,99.664914,7102,3994,3108
31,32,ok,,ClassBalance,0.0030,0.0,0.0001,0.9999,3,7102,...,100.000000,99.768900,49.099412,61.370493,2.017005,99.999155,99.433509,7102,3994,3108
45,46,ok,,ClassBalance,0.0100,0.0,0.0000,0.9999,3,7102,...,97.036046,99.899280,81.921859,89.821240,2.124879,97.048437,99.672195,7102,3994,3108
1,2,ok,,ClassBalance,0.0001,0.0,0.0001,0.9999,3,7102,...,100.000000,99.431126,35.130487,43.913109,1.839768,100.000000,98.186943,7102,3994,3108
2,3,ok,,ClassBalance,0.0001,0.0,0.0010,0.9999,3,7102,...,100.000000,79.908504,8.894253,11.117816,1.763032,100.000000,72.690608,7102,3994,3108
23,24,ok,,ClassBalance,0.0010,0.2,0.0010,0.9999,3,7102,...,100.000000,0.251873,0.165938,0.207422,2.136078,100.000000,0.215909,7102,3994,3108
34,35,ok,,ClassBalance,0.0030,0.1,0.0001,0.9999,3,7102,...,100.000000,0.145908,0.171972,0.214965,1.898152,100.000000,0.312806,7102,3994,3108
33,34,ok,,ClassBalance,0.0030,0.1,0.0000,0.9999,3,7102,...,99.964799,95.102690,28.622718,35.454065,1.981086,99.947902,94.662199,7102,3994,3108

## 10. Final training over seeds + head/tail sweep

In [13]:

HEAD_FRACTIONS = [0.001, 0.005, 0.01, 0.05, 0.20]

all_rows = []
all_test = []
all_sweep_rows = []

print("Using best_hp:", best_hp)

for seed in CFG["seeds"]:
    print("\n" + "=" * 80)
    print(f"ClassBalance seed {seed}")
    print("=" * 80)

    set_seed(seed)

    model = TwoTower(
        NUM_USERS, NUM_ITEMS, NUM_ARTISTS, NUM_ALBUMS,
        embed_dim=CFG["embed_dim"],
        artist_emb_dim=CFG["artist_emb_dim"],
        album_emb_dim=CFG["album_emb_dim"],
        hidden=CFG["tower_hidden"],
        dropout=best_hp["dropout"],
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=best_hp["lr"], weight_decay=best_hp["weight_decay"])

    best_val_hr50 = -1.0
    best_state = None

    for epoch in range(1, CFG["final_epochs"] + 1):
        model.train()
        total_loss, total_n = 0.0, 0
        pbar = tqdm(train_loader, desc=f"CB seed {seed} train {epoch}/{CFG['final_epochs']}", leave=False)

        for users_batch, items_batch in pbar:
            users_batch = users_batch.to(device, non_blocking=True)
            items_batch = items_batch.to(device, non_blocking=True)

            user_vecs = model.user_vec(users_batch)
            item_vecs = model.item_vec(items_batch)

            loss = classbalance_inbatch_softmax_loss(user_vecs, item_vecs, items_batch, cb_item_weights)

            if not torch.isfinite(loss):
                raise RuntimeError(f"Non-finite loss at seed={seed}, epoch={epoch}: {loss.item()}")

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), CFG["grad_clip"])
            optimizer.step()

            bs = users_batch.size(0)
            total_loss += loss.item() * bs
            total_n += bs
            pbar.set_postfix(loss=f"{loss.item():.4f}")

        avg_loss = total_loss / max(total_n, 1)
        print(f"seed {seed} epoch {epoch}: train loss = {avg_loss:.4f}")

        val_metrics = evaluate_full_corpus(
            model=model,
            users=val_u,
            true_items=val_i,
            known_user_items=known_val,
            head_mask=head_mask,
            ks=CFG["eval_k"],
            item_freq=item_freq,
            user_batch_size=CFG["eval_batch_users"],
            item_batch_size=CFG["eval_item_batch"],
        )

        hr50 = val_metrics["overall"].get("HR@50", -1.0)
        if hr50 > best_val_hr50:
            best_val_hr50 = hr50
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            print(f"new best val HR@50 = {best_val_hr50:.4f}")

    assert best_state is not None
    model.load_state_dict(best_state)
    model.to(device)
    model.eval()

    test_metrics = evaluate_full_corpus(
        model=model,
        users=test_u,
        true_items=test_i,
        known_user_items=known_test,
        head_mask=head_mask,
        ks=CFG["eval_k"],
        item_freq=item_freq,
        user_batch_size=CFG["eval_batch_users"],
        item_batch_size=CFG["eval_item_batch"],
    )

    print("TEST METRICS")
    print_metrics(test_metrics)
    all_test.append(test_metrics)

    row = {
        "method": "ClassBalance",
        "seed": seed,
        "lr": best_hp["lr"],
        "dropout": best_hp["dropout"],
        "weight_decay": best_hp["weight_decay"],
        "cb_beta": best_hp.get("cb_beta", CFG["cb_beta"]),
        "best_val_HR@50": best_val_hr50,
    }
    for split in ("overall", "head", "tail"):
        for key, value in test_metrics[split].items():
            row[f"test_{split}_{key}"] = value
    if "long_tail" in test_metrics:
        for key, value in test_metrics["long_tail"].items():
            row[f"test_{key}"] = value
    if "counts" in test_metrics:
        for key, value in test_metrics["counts"].items():
            row[f"test_count_{key}"] = value
    all_rows.append(row)

    sweep_rows_seed = evaluate_head_tail_sweep(
        model=model,
        method_name="ClassBalance",
        seed=seed,
        head_fractions=HEAD_FRACTIONS,
        test_u=test_u,
        test_i=test_i,
        known_test=known_test,
        item_freq=item_freq,
        ks=CFG["eval_k"],
    )
    all_sweep_rows.extend(sweep_rows_seed)

    del model
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

metrics_df = pd.DataFrame(all_rows)
sweep_df = pd.DataFrame(all_sweep_rows)
metrics_df

Using best_hp: {'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0001, 'cb_beta': 0.9999, 'val_HR@50': 0.28161081385525205}

================================================================================
ClassBalance seed 0
================================================================================

seed 0 epoch 1: train loss = 7.9498

new best val HR@50 = 0.0845

seed 0 epoch 2: train loss = 7.8331

new best val HR@50 = 0.1830

seed 0 epoch 3: train loss = 7.7466

new best val HR@50 = 0.2816

seed 0 epoch 4: train loss = 7.7168

seed 0 epoch 5: train loss = 7.6981

seed 0 epoch 6: train loss = 7.6857

new best val HR@50 = 0.3661

seed 0 epoch 7: train loss = 7.6759

seed 0 epoch 8: train loss = 7.6687

seed 0 epoch 9: train loss = 7.6638

seed 0 epoch 10: train loss = 7.6603

seed 0 epoch 11: train loss = 7.6575

new best val HR@50 = 0.3802

seed 0 epoch 12: train loss = 7.6556

seed 0 epoch 13: train loss = 7.6542

seed 0 epoch 14: train loss = 7.6528

new best val HR@50 = 0.4083

seed 0 epoch 15: train loss = 7.6516

seed 0 epoch 16: train loss = 7.6507

seed 0 epoch 17: train loss = 7.6505

seed 0 epoch 18: train loss = 7.6498

seed 0 epoch 19: train loss = 7.6489

seed 0 epoch 20: train loss = 7.6482

TEST METRICS
counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.01769588128201261, 'HR@50': 0.29569135454801465, 'NDCG@50': 0.06742320074230533}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.026205450733752623, 'NDCG@50': 0.005340541066313055}
[tail] {'HR@10': 0.12172854534388314, 'NDCG@10': 0.03824593696434984, 'HR@50': 0.6086427267194157, 'NDCG@50': 0.13951919262410278}
[long_tail] {'CatalogCoverage@10': 65.65092774174084, 'TailCoverage@10': 76.92713833157339, 'AvgPopularity@10': 2.1338541470379813, 'TailRatio@10': 97.54716981132076, 'Personalization@10': 99.93666274965497, 'CatalogCoverage@50': 90.37562226580178, 'TailCoverage@50': 98.62347262030472, 'AvgPopularity@50': 2.1333007060188818, 'TailRatio@50': 97.55308363841172, 'Personalization@50': 99.74428857696357}

================================================================================
ClassBalance | seed=0 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0262
test_tail_share: 0.9738

counts: {'overall': 7102, 'head': 186, 'tail': 6916}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.01769588128201261, 'HR@50': 0.29569135454801465, 'NDCG@50': 0.06742320074230533}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.057836899942163095, 'NDCG@10': 0.018171797117532328, 'HR@50': 0.30364372469635625, 'NDCG@50': 0.06923649098783291}
[long_tail] {'CatalogCoverage@10': 65.65092774174084, 'TailCoverage@10': 65.7163566078763, 'AvgPopularity@10': 2.1338541470379813, 'TailRatio@10': 100.0, 'Personalization@10': 99.93666274965497, 'CatalogCoverage@50': 90.37562226580178, 'TailCoverage@50': 90.46569219618266, 'AvgPopularity@50': 2.1333007060188818, 'TailRatio@50': 100.0, 'Personalization@50': 99.74428857696357}

================================================================================
ClassBalance | seed=0 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0631
test_tail_share: 0.9369

counts: {'overall': 7102, 'head': 448, 'tail': 6654}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.01769588128201261, 'HR@50': 0.29569135454801465, 'NDCG@50': 0.06742320074230533}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.06011421701232341, 'NDCG@10': 0.018887308215337174, 'HR@50': 0.3155996393146979, 'NDCG@50': 0.07196266481392431}
[long_tail] {'CatalogCoverage@10': 65.65092774174084, 'TailCoverage@10': 65.97634930260764, 'AvgPopularity@10': 2.1338541470379813, 'TailRatio@10': 99.99859194593073, 'Personalization@10': 99.93666274965497, 'CatalogCoverage@50': 90.37562226580178, 'TailCoverage@50': 90.80654942389327, 'AvgPopularity@50': 2.1333007060188818, 'TailRatio@50': 99.99802872430301, 'Personalization@50': 99.74428857696357}

================================================================================
ClassBalance | seed=0 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1021
test_tail_share: 0.8979

counts: {'overall': 7102, 'head': 725, 'tail': 6377}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.01769588128201261, 'HR@50': 0.29569135454801465, 'NDCG@50': 0.06742320074230533}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.06272541947624274, 'NDCG@10': 0.01970772288926667, 'HR@50': 0.3293084522502744, 'NDCG@50': 0.07508853248735337}
[long_tail] {'CatalogCoverage@10': 65.65092774174084, 'TailCoverage@10': 66.30706405802401, 'AvgPopularity@10': 2.1338541470379813, 'TailRatio@10': 99.99718389186145, 'Personalization@10': 99.93666274965497, 'CatalogCoverage@50': 90.37562226580178, 'TailCoverage@50': 91.22021088559761, 'AvgPopularity@50': 2.1333007060188818, 'TailRatio@50': 99.99155167558435, 'Personalization@50': 99.74428857696357}

================================================================================
ClassBalance | seed=0 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2867
test_tail_share: 0.7133

counts: {'overall': 7102, 'head': 2036, 'tail': 5066}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.01769588128201261, 'HR@50': 0.29569135454801465, 'NDCG@50': 0.06742320074230533}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.04911591355599214, 'NDCG@50': 0.01000957991603665}
[tail] {'HR@10': 0.07895775759968417, 'NDCG@10': 0.024807767245332325, 'HR@50': 0.3947887879984209, 'NDCG@50': 0.09049744709095967}
[long_tail] {'CatalogCoverage@10': 65.65092774174084, 'TailCoverage@10': 68.70871443089432, 'AvgPopularity@10': 2.1338541470379813, 'TailRatio@10': 99.80146437623205, 'Personalization@10': 99.93666274965497, 'CatalogCoverage@50': 90.37562226580178, 'TailCoverage@50': 93.73094512195121, 'AvgPopularity@50': 2.1333007060188818, 'TailRatio@50': 99.82174035482963, 'Personalization@50': 99.74428857696357}

================================================================================
ClassBalance | seed=0 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5373
test_tail_share: 0.4627

counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.01769588128201261, 'HR@50': 0.29569135454801465, 'NDCG@50': 0.06742320074230533}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.026205450733752623, 'NDCG@50': 0.005340541066313055}
[tail] {'HR@10': 0.12172854534388314, 'NDCG@10': 0.03824593696434984, 'HR@50': 0.6086427267194157, 'NDCG@50': 0.13951919262410278}
[long_tail] {'CatalogCoverage@10': 65.65092774174084, 'TailCoverage@10': 76.92713833157339, 'AvgPopularity@10': 2.1338541470379813, 'TailRatio@10': 97.54716981132076, 'Personalization@10': 99.93666274965497, 'CatalogCoverage@50': 90.37562226580178, 'TailCoverage@50': 98.62347262030472, 'AvgPopularity@50': 2.1333007060188818, 'TailRatio@50': 97.55308363841172, 'Personalization@50': 99.74428857696357}

================================================================================
ClassBalance seed 1
================================================================================

seed 1 epoch 1: train loss = 7.9487

new best val HR@50 = 0.0845

seed 1 epoch 2: train loss = 7.8075

new best val HR@50 = 0.0986

seed 1 epoch 3: train loss = 7.7363

new best val HR@50 = 0.2253

seed 1 epoch 4: train loss = 7.7048

new best val HR@50 = 0.3239

seed 1 epoch 5: train loss = 7.6864

seed 1 epoch 6: train loss = 7.6749

new best val HR@50 = 0.3379

seed 1 epoch 7: train loss = 7.6668

new best val HR@50 = 0.3943

seed 1 epoch 8: train loss = 7.6586

seed 1 epoch 9: train loss = 7.6463

seed 1 epoch 10: train loss = 7.6402

new best val HR@50 = 0.4647

seed 1 epoch 11: train loss = 7.6377

new best val HR@50 = 0.6477

seed 1 epoch 12: train loss = 7.6356

seed 1 epoch 13: train loss = 7.6343

new best val HR@50 = 0.6759

seed 1 epoch 14: train loss = 7.6332

seed 1 epoch 15: train loss = 7.6321

seed 1 epoch 16: train loss = 7.6310

seed 1 epoch 17: train loss = 7.6300

seed 1 epoch 18: train loss = 7.6292

seed 1 epoch 19: train loss = 7.6288

seed 1 epoch 20: train loss = 7.6281

new best val HR@50 = 0.7603

TEST METRICS
counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.22528865108420162, 'NDCG@10': 0.09008706531947035, 'HR@50': 0.8448324415657561, 'NDCG@50': 0.22076890060415172}
[head] {'HR@10': 0.026205450733752623, 'NDCG@10': 0.016533798573675512, 'HR@50': 0.07861635220125787, 'NDCG@50': 0.028706194318415906}
[tail] {'HR@10': 0.4564820450395618, 'NDCG@10': 0.17550376218555466, 'HR@50': 1.7346317711503345, 'NDCG@50': 0.4438094627424255}
[long_tail] {'CatalogCoverage@10': 71.01523608387389, 'TailCoverage@10': 81.3131694071504, 'AvgPopularity@10': 2.1425828072352107, 'TailRatio@10': 96.23767952689384, 'Personalization@10': 99.94460305625265, 'CatalogCoverage@50': 94.12882787750792, 'TailCoverage@50': 99.2117966510786, 'AvgPopularity@50': 2.141131324547154, 'TailRatio@50': 96.20923683469445, 'Personalization@50': 99.75451888987517}

================================================================================
ClassBalance | seed=1 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0262
test_tail_share: 0.9738

counts: {'overall': 7102, 'head': 186, 'tail': 6916}
[overall] {'HR@10': 0.22528865108420162, 'NDCG@10': 0.09008706531947035, 'HR@50': 0.8448324415657561, 'NDCG@50': 0.22076890060415172}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.23134759976865238, 'NDCG@10': 0.09250988113054921, 'HR@50': 0.8675534991324465, 'NDCG@50': 0.2267062944029331}
[long_tail] {'CatalogCoverage@10': 71.01523608387389, 'TailCoverage@10': 71.08601111379559, 'AvgPopularity@10': 2.1425828072352107, 'TailRatio@10': 100.0, 'Personalization@10': 99.94460305625265, 'CatalogCoverage@50': 94.12882787750792, 'TailCoverage@50': 94.2135781589756, 'AvgPopularity@50': 2.141131324547154, 'TailRatio@50': 99.99915516755843, 'Personalization@50': 99.75451888987517}

================================================================================
ClassBalance | seed=1 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0631
test_tail_share: 0.9369

counts: {'overall': 7102, 'head': 448, 'tail': 6654}
[overall] {'HR@10': 0.22528865108420162, 'NDCG@10': 0.09008706531947035, 'HR@50': 0.8448324415657561, 'NDCG@50': 0.22076890060415172}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.24045686804929364, 'NDCG@10': 0.09615244032144249, 'HR@50': 0.9017132551848512, 'NDCG@50': 0.23563281215670057}
[long_tail] {'CatalogCoverage@10': 71.01523608387389, 'TailCoverage@10': 71.36446331109764, 'AvgPopularity@10': 2.1425828072352107, 'TailRatio@10': 99.99718389186145, 'Personalization@10': 99.94460305625265, 'CatalogCoverage@50': 94.12882787750792, 'TailCoverage@50': 94.55124317768345, 'AvgPopularity@50': 2.141131324547154, 'TailRatio@50': 99.99549422697832, 'Personalization@50': 99.75451888987517}

================================================================================
ClassBalance | seed=1 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1021
test_tail_share: 0.8979

counts: {'overall': 7102, 'head': 725, 'tail': 6377}
[overall] {'HR@10': 0.22528865108420162, 'NDCG@10': 0.09008706531947035, 'HR@50': 0.8448324415657561, 'NDCG@50': 0.22076890060415172}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.250901677904971, 'NDCG@10': 0.1003290478122751, 'HR@50': 0.9408812921436412, 'NDCG@50': 0.24586807779374084}
[long_tail] {'CatalogCoverage@10': 71.01523608387389, 'TailCoverage@10': 71.71024562686658, 'AvgPopularity@10': 2.1425828072352107, 'TailRatio@10': 99.99014362151507, 'Personalization@10': 99.94460305625265, 'CatalogCoverage@50': 94.12882787750792, 'TailCoverage@50': 94.93813616139452, 'AvgPopularity@50': 2.141131324547154, 'TailRatio@50': 99.9862010701211, 'Personalization@50': 99.75451888987517}

================================================================================
ClassBalance | seed=1 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2867
test_tail_share: 0.7133

counts: {'overall': 7102, 'head': 2036, 'tail': 5066}
[overall] {'HR@10': 0.22528865108420162, 'NDCG@10': 0.09008706531947035, 'HR@50': 0.8448324415657561, 'NDCG@50': 0.22076890060415172}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.31583103039873667, 'NDCG@10': 0.12629260519125116, 'HR@50': 1.1843663639952624, 'NDCG@50': 0.30949481486195923}
[long_tail] {'CatalogCoverage@10': 71.01523608387389, 'TailCoverage@10': 74.24733231707317, 'AvgPopularity@10': 2.1425828072352107, 'TailRatio@10': 99.75922275415377, 'Personalization@10': 99.94460305625265, 'CatalogCoverage@50': 94.12882787750792, 'TailCoverage@50': 96.86229674796748, 'AvgPopularity@50': 2.141131324547154, 'TailRatio@50': 99.70712475359053, 'Personalization@50': 99.75451888987517}

================================================================================
ClassBalance | seed=1 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5373
test_tail_share: 0.4627

counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.22528865108420162, 'NDCG@10': 0.09008706531947035, 'HR@50': 0.8448324415657561, 'NDCG@50': 0.22076890060415172}
[head] {'HR@10': 0.026205450733752623, 'NDCG@10': 0.016533798573675512, 'HR@50': 0.07861635220125787, 'NDCG@50': 0.028706194318415906}
[tail] {'HR@10': 0.4564820450395618, 'NDCG@10': 0.17550376218555466, 'HR@50': 1.7346317711503345, 'NDCG@50': 0.4438094627424255}
[long_tail] {'CatalogCoverage@10': 71.01523608387389, 'TailCoverage@10': 81.3131694071504, 'AvgPopularity@10': 2.1425828072352107, 'TailRatio@10': 96.23767952689384, 'Personalization@10': 99.94460305625265, 'CatalogCoverage@50': 94.12882787750792, 'TailCoverage@50': 99.2117966510786, 'AvgPopularity@50': 2.141131324547154, 'TailRatio@50': 96.20923683469445, 'Personalization@50': 99.75451888987517}

================================================================================
ClassBalance seed 2
================================================================================

seed 2 epoch 1: train loss = 7.9411

new best val HR@50 = 0.0422

seed 2 epoch 2: train loss = 7.8100

new best val HR@50 = 0.2253

seed 2 epoch 3: train loss = 7.7347

seed 2 epoch 4: train loss = 7.6962

new best val HR@50 = 0.3520

seed 2 epoch 5: train loss = 7.6733

seed 2 epoch 6: train loss = 7.6655

seed 2 epoch 7: train loss = 7.6619

seed 2 epoch 8: train loss = 7.6591

seed 2 epoch 9: train loss = 7.6572

seed 2 epoch 10: train loss = 7.6561

seed 2 epoch 11: train loss = 7.6546

seed 2 epoch 12: train loss = 7.6534

new best val HR@50 = 0.3943

seed 2 epoch 13: train loss = 7.6522

seed 2 epoch 14: train loss = 7.6514

seed 2 epoch 15: train loss = 7.6506

new best val HR@50 = 0.4083

seed 2 epoch 16: train loss = 7.6501

seed 2 epoch 17: train loss = 7.6494

seed 2 epoch 18: train loss = 7.6487

seed 2 epoch 19: train loss = 7.6484

seed 2 epoch 20: train loss = 7.6480

TEST METRICS
counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.07040270346381301, 'NDCG@10': 0.02927891963462193, 'HR@50': 0.22528865108420162, 'NDCG@50': 0.06259911555267388}
[head] {'HR@10': 0.026205450733752623, 'NDCG@10': 0.016533798573675512, 'HR@50': 0.026205450733752623, 'NDCG@50': 0.016533798573675512}
[tail] {'HR@10': 0.12172854534388314, 'NDCG@10': 0.04407970538281778, 'HR@50': 0.4564820450395618, 'NDCG@50': 0.11609432236699455}
[long_tail] {'CatalogCoverage@10': 63.925177251470814, 'TailCoverage@10': 75.66375018856539, 'AvgPopularity@10': 2.1063789052506734, 'TailRatio@10': 98.01745987045902, 'Personalization@10': 99.93736707412393, 'CatalogCoverage@50': 87.40684869512747, 'TailCoverage@50': 97.0810076934681, 'AvgPopularity@50': 2.1075663197719443, 'TailRatio@50': 98.04196001126442, 'Personalization@50': 99.71666636724945}

================================================================================
ClassBalance | seed=2 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0262
test_tail_share: 0.9738

counts: {'overall': 7102, 'head': 186, 'tail': 6916}
[overall] {'HR@10': 0.07040270346381301, 'NDCG@10': 0.02927891963462193, 'HR@50': 0.22528865108420162, 'NDCG@50': 0.06259911555267388}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.07229612492770388, 'NDCG@10': 0.030066351539196783, 'HR@50': 0.23134759976865238, 'NDCG@50': 0.06428266608662375}
[long_tail] {'CatalogCoverage@10': 63.925177251470814, 'TailCoverage@10': 63.98586615124427, 'AvgPopularity@10': 2.1063789052506734, 'TailRatio@10': 99.99859194593073, 'Personalization@10': 99.93736707412393, 'CatalogCoverage@50': 87.40684869512747, 'TailCoverage@50': 87.46375936216478, 'AvgPopularity@50': 2.1075663197719443, 'TailRatio@50': 99.99605744860602, 'Personalization@50': 99.71666636724945}

================================================================================
ClassBalance | seed=2 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0631
test_tail_share: 0.9369

counts: {'overall': 7102, 'head': 448, 'tail': 6654}
[overall] {'HR@10': 0.07040270346381301, 'NDCG@10': 0.02927891963462193, 'HR@50': 0.22528865108420162, 'NDCG@50': 0.06259911555267388}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.07514277126540427, 'NDCG@10': 0.031250208482880217, 'HR@50': 0.24045686804929364, 'NDCG@50': 0.06681378398784038}
[long_tail] {'CatalogCoverage@10': 63.925177251470814, 'TailCoverage@10': 64.22680412371135, 'AvgPopularity@10': 2.1063789052506734, 'TailRatio@10': 99.99155167558435, 'Personalization@10': 99.93736707412393, 'CatalogCoverage@50': 87.40684869512747, 'TailCoverage@50': 87.72892662219527, 'AvgPopularity@50': 2.1075663197719443, 'TailRatio@50': 99.98817234581809, 'Personalization@50': 99.71666636724945}

================================================================================
ClassBalance | seed=2 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1021
test_tail_share: 0.8979

counts: {'overall': 7102, 'head': 725, 'tail': 6377}
[overall] {'HR@10': 0.07040270346381301, 'NDCG@10': 0.02927891963462193, 'HR@50': 0.22528865108420162, 'NDCG@50': 0.06259911555267388}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.07840677434530344, 'NDCG@10': 0.03260763481967774, 'HR@50': 0.250901677904971, 'NDCG@50': 0.06971599790733729}
[long_tail] {'CatalogCoverage@10': 63.925177251470814, 'TailCoverage@10': 64.5364783324191, 'AvgPopularity@10': 2.1063789052506734, 'TailRatio@10': 99.98451140523797, 'Personalization@10': 99.93736707412393, 'CatalogCoverage@50': 87.40684869512747, 'TailCoverage@50': 88.05387944170171, 'AvgPopularity@50': 2.1075663197719443, 'TailRatio@50': 99.97634469163616, 'Personalization@50': 99.71666636724945}

================================================================================
ClassBalance | seed=2 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2867
test_tail_share: 0.7133

counts: {'overall': 7102, 'head': 2036, 'tail': 5066}
[overall] {'HR@10': 0.07040270346381301, 'NDCG@10': 0.02927891963462193, 'HR@50': 0.22528865108420162, 'NDCG@50': 0.06259911555267388}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.09869719699960522, 'NDCG@10': 0.04104597063661369, 'HR@50': 0.31583103039873667, 'NDCG@50': 0.08775738623274573}
[long_tail] {'CatalogCoverage@10': 63.925177251470814, 'TailCoverage@10': 67.02235772357723, 'AvgPopularity@10': 2.1063789052506734, 'TailRatio@10': 99.87890735004224, 'Personalization@10': 99.93736707412393, 'CatalogCoverage@50': 87.40684869512747, 'TailCoverage@50': 90.76473577235772, 'AvgPopularity@50': 2.1075663197719443, 'TailRatio@50': 99.87383835539285, 'Personalization@50': 99.71666636724945}

================================================================================
ClassBalance | seed=2 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5373
test_tail_share: 0.4627

counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.07040270346381301, 'NDCG@10': 0.02927891963462193, 'HR@50': 0.22528865108420162, 'NDCG@50': 0.06259911555267388}
[head] {'HR@10': 0.026205450733752623, 'NDCG@10': 0.016533798573675512, 'HR@50': 0.026205450733752623, 'NDCG@50': 0.016533798573675512}
[tail] {'HR@10': 0.12172854534388314, 'NDCG@10': 0.04407970538281778, 'HR@50': 0.4564820450395618, 'NDCG@50': 0.11609432236699455}
[long_tail] {'CatalogCoverage@10': 63.925177251470814, 'TailCoverage@10': 75.66375018856539, 'AvgPopularity@10': 2.1063789052506734, 'TailRatio@10': 98.01745987045902, 'Personalization@10': 99.93736707412393, 'CatalogCoverage@50': 87.40684869512747, 'TailCoverage@50': 97.0810076934681, 'AvgPopularity@50': 2.1075663197719443, 'TailRatio@50': 98.04196001126442, 'Personalization@50': 99.71666636724945}

================================================================================
ClassBalance seed 3
================================================================================

seed 3 epoch 1: train loss = 7.9411

new best val HR@50 = 0.0704

seed 3 epoch 2: train loss = 7.8044

new best val HR@50 = 0.1267

seed 3 epoch 3: train loss = 7.7350

new best val HR@50 = 0.2534

seed 3 epoch 4: train loss = 7.7041

seed 3 epoch 5: train loss = 7.6833

new best val HR@50 = 0.2816

seed 3 epoch 6: train loss = 7.6620

new best val HR@50 = 0.5491

seed 3 epoch 7: train loss = 7.6472

new best val HR@50 = 0.8308

seed 3 epoch 8: train loss = 7.6419

seed 3 epoch 9: train loss = 7.6393

seed 3 epoch 10: train loss = 7.6372

seed 3 epoch 11: train loss = 7.6358

seed 3 epoch 12: train loss = 7.6345

seed 3 epoch 13: train loss = 7.6336

seed 3 epoch 14: train loss = 7.6323

seed 3 epoch 15: train loss = 7.6318

seed 3 epoch 16: train loss = 7.6307

seed 3 epoch 17: train loss = 7.6299

seed 3 epoch 18: train loss = 7.6294

seed 3 epoch 19: train loss = 7.6289

seed 3 epoch 20: train loss = 7.6284

TEST METRICS
counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.09856378484933823, 'NDCG@10': 0.041030771570631216, 'HR@50': 0.6899464939453674, 'NDCG@50': 0.16290354674375268}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.2130249543517955, 'NDCG@10': 0.0886794095236223, 'HR@50': 1.4911746804625685, 'NDCG@50': 0.35208185909133644}
[long_tail] {'CatalogCoverage@10': 57.55015839493136, 'TailCoverage@10': 70.27832252225072, 'AvgPopularity@10': 2.034056791248323, 'TailRatio@10': 99.23683469445227, 'Personalization@10': 99.90368164597456, 'CatalogCoverage@50': 76.43385125961683, 'TailCoverage@50': 89.32342736461004, 'AvgPopularity@50': 2.0353169012311625, 'TailRatio@50': 99.20275978597579, 'Personalization@50': 99.64608877240568}

================================================================================
ClassBalance | seed=3 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0262
test_tail_share: 0.9738

counts: {'overall': 7102, 'head': 186, 'tail': 6916}
[overall] {'HR@10': 0.09856378484933823, 'NDCG@10': 0.041030771570631216, 'HR@50': 0.6899464939453674, 'NDCG@50': 0.16290354674375268}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.10121457489878542, 'NDCG@10': 0.04213425964352557, 'HR@50': 0.708502024291498, 'NDCG@50': 0.16728470054571015}
[long_tail] {'CatalogCoverage@10': 57.55015839493136, 'TailCoverage@10': 57.6075138922445, 'AvgPopularity@10': 2.034056791248323, 'TailRatio@10': 100.0, 'Personalization@10': 99.90368164597456, 'CatalogCoverage@50': 76.43385125961683, 'TailCoverage@50': 76.51002657646775, 'AvgPopularity@50': 2.0353169012311625, 'TailRatio@50': 100.0, 'Personalization@50': 99.64608877240568}

================================================================================
ClassBalance | seed=3 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0631
test_tail_share: 0.9369

counts: {'overall': 7102, 'head': 448, 'tail': 6654}
[overall] {'HR@10': 0.09856378484933823, 'NDCG@10': 0.041030771570631216, 'HR@50': 0.6899464939453674, 'NDCG@50': 0.16290354674375268}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.10519987977156597, 'NDCG@10': 0.0437932882017768, 'HR@50': 0.7363991584009618, 'NDCG@50': 0.17387150420410752}
[long_tail] {'CatalogCoverage@10': 57.55015839493136, 'TailCoverage@10': 57.838083687083085, 'AvgPopularity@10': 2.034056791248323, 'TailRatio@10': 100.0, 'Personalization@10': 99.90368164597456, 'CatalogCoverage@50': 76.43385125961683, 'TailCoverage@50': 76.81625227410552, 'AvgPopularity@50': 2.0353169012311625, 'TailRatio@50': 100.0, 'Personalization@50': 99.64608877240568}

================================================================================
ClassBalance | seed=3 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1021
test_tail_share: 0.8979

counts: {'overall': 7102, 'head': 725, 'tail': 6377}
[overall] {'HR@10': 0.09856378484933823, 'NDCG@10': 0.041030771570631216, 'HR@50': 0.6899464939453674, 'NDCG@50': 0.16290354674375268}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.10976948408342481, 'NDCG@10': 0.045695552719871864, 'HR@50': 0.7683863885839737, 'NDCG@50': 0.18142402210665384}
[long_tail] {'CatalogCoverage@10': 57.55015839493136, 'TailCoverage@10': 58.13067593100506, 'AvgPopularity@10': 2.034056791248323, 'TailRatio@10': 100.0, 'Personalization@10': 99.90368164597456, 'CatalogCoverage@50': 76.43385125961683, 'TailCoverage@50': 77.20485158773694, 'AvgPopularity@50': 2.0353169012311625, 'TailRatio@50': 100.0, 'Personalization@50': 99.64608877240568}

================================================================================
ClassBalance | seed=3 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2867
test_tail_share: 0.7133

counts: {'overall': 7102, 'head': 2036, 'tail': 5066}
[overall] {'HR@10': 0.09856378484933823, 'NDCG@10': 0.041030771570631216, 'HR@50': 0.6899464939453674, 'NDCG@50': 0.16290354674375268}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.1381760757994473, 'NDCG@10': 0.05752083294406294, 'HR@50': 0.9672325305961311, 'NDCG@50': 0.2283736654113959}
[long_tail] {'CatalogCoverage@10': 57.55015839493136, 'TailCoverage@10': 60.537347560975604, 'AvgPopularity@10': 2.034056791248323, 'TailRatio@10': 99.9816952970994, 'Personalization@10': 99.90368164597456, 'CatalogCoverage@50': 76.43385125961683, 'TailCoverage@50': 80.24009146341463, 'AvgPopularity@50': 2.0353169012311625, 'TailRatio@50': 99.98085046465785, 'Personalization@50': 99.64608877240568}

================================================================================
ClassBalance | seed=3 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5373
test_tail_share: 0.4627

counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.09856378484933823, 'NDCG@10': 0.041030771570631216, 'HR@50': 0.6899464939453674, 'NDCG@50': 0.16290354674375268}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.2130249543517955, 'NDCG@10': 0.0886794095236223, 'HR@50': 1.4911746804625685, 'NDCG@50': 0.35208185909133644}
[long_tail] {'CatalogCoverage@10': 57.55015839493136, 'TailCoverage@10': 70.27832252225072, 'AvgPopularity@10': 2.034056791248323, 'TailRatio@10': 99.23683469445227, 'Personalization@10': 99.90368164597456, 'CatalogCoverage@50': 76.43385125961683, 'TailCoverage@50': 89.32342736461004, 'AvgPopularity@50': 2.0353169012311625, 'TailRatio@50': 99.20275978597579, 'Personalization@50': 99.64608877240568}

================================================================================
ClassBalance seed 4
================================================================================

seed 4 epoch 1: train loss = 7.9439

new best val HR@50 = 0.0282

seed 4 epoch 2: train loss = 7.8207

new best val HR@50 = 0.1830

seed 4 epoch 3: train loss = 7.7381

new best val HR@50 = 0.2816

seed 4 epoch 4: train loss = 7.7100

seed 4 epoch 5: train loss = 7.6931

new best val HR@50 = 0.3661

seed 4 epoch 6: train loss = 7.6811

seed 4 epoch 7: train loss = 7.6724

seed 4 epoch 8: train loss = 7.6667

seed 4 epoch 9: train loss = 7.6625

seed 4 epoch 10: train loss = 7.6594

seed 4 epoch 11: train loss = 7.6569

seed 4 epoch 12: train loss = 7.6554

seed 4 epoch 13: train loss = 7.6539

new best val HR@50 = 0.3943

seed 4 epoch 14: train loss = 7.6527

seed 4 epoch 15: train loss = 7.6516

seed 4 epoch 16: train loss = 7.6506

seed 4 epoch 17: train loss = 7.6501

seed 4 epoch 18: train loss = 7.6495

seed 4 epoch 19: train loss = 7.6488

seed 4 epoch 20: train loss = 7.6482

TEST METRICS
counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.02760823557042578, 'HR@50': 0.26753027316248945, 'NDCG@50': 0.07126050164367496}
[head] {'HR@10': 0.026205450733752623, 'NDCG@10': 0.008266899286837756, 'HR@50': 0.026205450733752623, 'NDCG@50': 0.008266899286837756}
[tail] {'HR@10': 0.09129640900791236, 'NDCG@10': 0.050069142222334447, 'HR@50': 0.5477784540474742, 'NDCG@50': 0.1444143624451633}
[long_tail] {'CatalogCoverage@10': 66.82455875697691, 'TailCoverage@10': 77.56826067280133, 'AvgPopularity@10': 2.1414490493494656, 'TailRatio@10': 97.17262742889326, 'Personalization@10': 99.94252537838504, 'CatalogCoverage@50': 92.35782169256298, 'TailCoverage@50': 98.26896967868457, 'AvgPopularity@50': 2.14372035556028, 'TailRatio@50': 97.15939172064208, 'Personalization@50': 99.75511938993762}

================================================================================
ClassBalance | seed=4 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0262
test_tail_share: 0.9738

counts: {'overall': 7102, 'head': 186, 'tail': 6916}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.02760823557042578, 'HR@50': 0.26753027316248945, 'NDCG@50': 0.07126050164367496}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.057836899942163095, 'NDCG@10': 0.028350735833019648, 'HR@50': 0.27472527472527475, 'NDCG@50': 0.07317699286775296}
[long_tail] {'CatalogCoverage@10': 66.82455875697691, 'TailCoverage@10': 66.8911572843682, 'AvgPopularity@10': 2.1414490493494656, 'TailRatio@10': 100.0, 'Personalization@10': 99.94252537838504, 'CatalogCoverage@50': 92.35782169256298, 'TailCoverage@50': 92.44986711766127, 'AvgPopularity@50': 2.14372035556028, 'TailRatio@50': 100.0, 'Personalization@50': 99.75511938993762}

================================================================================
ClassBalance | seed=4 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0631
test_tail_share: 0.9369

counts: {'overall': 7102, 'head': 448, 'tail': 6654}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.02760823557042578, 'HR@50': 0.26753027316248945, 'NDCG@50': 0.07126050164367496}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.06011421701232341, 'NDCG@10': 0.029467040730562652, 'HR@50': 0.28554253080853625, 'NDCG@50': 0.07605832321511564}
[long_tail] {'CatalogCoverage@10': 66.82455875697691, 'TailCoverage@10': 67.13462704669496, 'AvgPopularity@10': 2.1414490493494656, 'TailRatio@10': 99.98732751337651, 'Personalization@10': 99.94252537838504, 'CatalogCoverage@50': 92.35782169256298, 'TailCoverage@50': 92.71679805942996, 'AvgPopularity@50': 2.14372035556028, 'TailRatio@50': 99.98732751337651, 'Personalization@50': 99.75511938993762}

================================================================================
ClassBalance | seed=4 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1021
test_tail_share: 0.8979

counts: {'overall': 7102, 'head': 725, 'tail': 6377}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.02760823557042578, 'HR@50': 0.26753027316248945, 'NDCG@50': 0.07126050164367496}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.06272541947624274, 'NDCG@10': 0.03074701098026719, 'HR@50': 0.29794574251215306, 'NDCG@50': 0.07936209544823264}
[long_tail] {'CatalogCoverage@10': 66.82455875697691, 'TailCoverage@10': 67.43463155970014, 'AvgPopularity@10': 2.1414490493494656, 'TailRatio@10': 99.96761475640665, 'Personalization@10': 99.94252537838504, 'CatalogCoverage@50': 92.35782169256298, 'TailCoverage@50': 93.00603400987384, 'AvgPopularity@50': 2.14372035556028, 'TailRatio@50': 99.96676992396509, 'Personalization@50': 99.75511938993762}

================================================================================
ClassBalance | seed=4 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2867
test_tail_share: 0.7133

counts: {'overall': 7102, 'head': 2036, 'tail': 5066}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.02760823557042578, 'HR@50': 0.26753027316248945, 'NDCG@50': 0.07126050164367496}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[tail] {'HR@10': 0.07895775759968417, 'NDCG@10': 0.03870384702352229, 'HR@50': 0.3750493485984998, 'NDCG@50': 0.09989973996711006}
[long_tail] {'CatalogCoverage@10': 66.82455875697691, 'TailCoverage@10': 69.8901168699187, 'AvgPopularity@10': 2.1414490493494656, 'TailRatio@10': 99.78597578147, 'Personalization@10': 99.94252537838504, 'CatalogCoverage@50': 92.35782169256298, 'TailCoverage@50': 95.22357723577237, 'AvgPopularity@50': 2.14372035556028, 'TailRatio@50': 99.76738946775556, 'Personalization@50': 99.75511938993762}

================================================================================
ClassBalance | seed=4 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5373
test_tail_share: 0.4627

counts: {'overall': 7102, 'head': 3816, 'tail': 3286}
[overall] {'HR@10': 0.056322162771050406, 'NDCG@10': 0.02760823557042578, 'HR@50': 0.26753027316248945, 'NDCG@50': 0.07126050164367496}
[head] {'HR@10': 0.026205450733752623, 'NDCG@10': 0.008266899286837756, 'HR@50': 0.026205450733752623, 'NDCG@50': 0.008266899286837756}
[tail] {'HR@10': 0.09129640900791236, 'NDCG@10': 0.050069142222334447, 'HR@50': 0.5477784540474742, 'NDCG@50': 0.1444143624451633}
[long_tail] {'CatalogCoverage@10': 66.82455875697691, 'TailCoverage@10': 77.56826067280133, 'AvgPopularity@10': 2.1414490493494656, 'TailRatio@10': 97.17262742889326, 'Personalization@10': 99.94252537838504, 'CatalogCoverage@50': 92.35782169256298, 'TailCoverage@50': 98.26896967868457, 'AvgPopularity@50': 2.14372035556028, 'TailRatio@50': 97.15939172064208, 'Personalization@50': 99.75511938993762}

,method,seed,lr,dropout,weight_decay,cb_beta,best_val_HR@50,test_overall_HR@10,test_overall_NDCG@10,test_overall_HR@50,...,test_TailRatio@10,test_Personalization@10,test_CatalogCoverage@50,test_TailCoverage@50,test_AvgPopularity@50,test_TailRatio@50,test_Personalization@50,test_count_overall,test_count_head,test_count_tail
0,ClassBalance,0,0.001,0.0,0.0001,0.9999,0.408336,0.056322,0.017696,0.295691,...,97.547170,99.936663,90.375622,98.623473,2.133301,97.553084,99.744289,7102,3816,3286
1,ClassBalance,1,0.001,0.0,0.0001,0.9999,0.760349,0.225289,0.090087,0.844832,...,96.237680,99.944603,94.128828,99.211797,2.141131,96.209237,99.754519,7102,3816,3286
2,ClassBalance,2,0.001,0.0,0.0001,0.9999,0.408336,0.070403,0.029279,0.225289,...,98.017460,99.937367,87.406849,97.081008,2.107566,98.041960,99.716666,7102,3816,3286
3,ClassBalance,3,0.001,0.0,0.0001,0.9999,0.830752,0.098564,0.041031,0.689946,...,99.236835,99.903682,76.433851,89.323427,2.035317,99.202760,99.646089,7102,3816,3286
4,ClassBalance,4,0.001,0.0,0.0001,0.9999,0.394255,0.056322,0.027608,0.267530,...,97.172627,99.942525,92.357822,98.268970,2.143720,97.159392,99.755119,7102,3816,3286

## 11. Compact final table

In [ ]:

def make_final_summary_table(
    metrics_df: pd.DataFrame,
    sweep_df: pd.DataFrame,
    method_name: str,
    save_path: str | None = None,
) -> pd.DataFrame:
    """
    One compact final table: one row = method × head_fraction.
    Metrics are aggregated over seeds as mean ± std.
    """
    if len(sweep_df) == 0:
        raise ValueError("sweep_df is empty")

    selected_metrics = [
        "overall_HR@50",
        "overall_NDCG@50",
        "head_HR@50",
        "head_NDCG@50",
        "tail_HR@50",
        "tail_NDCG@50",
        "CatalogCoverage@50",
        "TailCoverage@50",
        "AvgPopularity@50",
        "TailRatio@50",
        "Personalization@50",
    ]

    rows = []

    for head_fraction, group in sweep_df.groupby("head_fraction"):
        group = group.copy()

        row = {
            "method": method_name,
            "head_share": f"{100 * float(head_fraction):.3f}%",
            "head_fraction": float(head_fraction),
            "num_seeds": group["seed"].nunique() if "seed" in group.columns else len(group),
            "num_head_items": int(group["num_head_items"].iloc[0]) if "num_head_items" in group.columns else np.nan,
            "num_tail_items": int(group["num_tail_items"].iloc[0]) if "num_tail_items" in group.columns else np.nan,
        }

        if "test_head_share" in group.columns:
            row["test_head_share"] = f"{100 * float(group['test_head_share'].mean()):.2f}%"

        if "test_tail_share" in group.columns:
            row["test_tail_share"] = f"{100 * float(group['test_tail_share'].mean()):.2f}%"

        if metrics_df is not None and len(metrics_df) > 0:
            for hp_col in ["lr", "dropout", "weight_decay", "logq_weight", "cb_beta"]:
                if hp_col in metrics_df.columns:
                    vals = metrics_df[hp_col].dropna().unique()
                    if len(vals) == 1:
                        row[hp_col] = vals[0]
                    elif len(vals) > 1:
                        row[hp_col] = ", ".join(map(str, vals))

            if "best_val_HR@50" in metrics_df.columns:
                vals = metrics_df["best_val_HR@50"].dropna().to_numpy(dtype=float)
                if len(vals) > 0:
                    mean = float(np.mean(vals))
                    std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
                    row["best_val_HR@50"] = f"{mean:.2f} ± {std:.2f}"

        for metric in selected_metrics:
            if metric not in group.columns:
                continue

            vals = group[metric].dropna().to_numpy(dtype=float)

            if len(vals) == 0:
                row[metric] = "nan"
                continue

            mean = float(np.mean(vals))
            std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0

            if "AvgPopularity" in metric:
                row[metric] = f"{mean:.4f} ± {std:.4f}"
            else:
                row[metric] = f"{mean:.2f} ± {std:.2f}"

        rows.append(row)

    summary_df = pd.DataFrame(rows).sort_values("head_fraction").reset_index(drop=True)

    first_cols = [
        "method",
        "head_share",
        "head_fraction",
        "num_seeds",
        "num_head_items",
        "num_tail_items",
        "test_head_share",
        "test_tail_share",
        "lr",
        "dropout",
        "weight_decay",
        "logq_weight",
        "cb_beta",
        "best_val_HR@50",
    ]

    metric_cols = selected_metrics
    ordered_cols = [c for c in first_cols + metric_cols if c in summary_df.columns]
    other_cols = [c for c in summary_df.columns if c not in ordered_cols]
    summary_df = summary_df[ordered_cols + other_cols]

    if save_path is not None:
        summary_df.to_csv(save_path, index=False)
        print(f"saved: {save_path}")

    return summary_df

saved: classbalance_summary.csv

,method,head_share,head_fraction,num_seeds,num_head_items,num_tail_items,test_head_share,test_tail_share,lr,dropout,...,overall_NDCG@50,head_HR@50,head_NDCG@50,tail_HR@50,tail_NDCG@50,CatalogCoverage@50,TailCoverage@50,AvgPopularity@50,TailRatio@50,Personalization@50
0,ClassBalance,0.100%,0.001,5,33,33112,2.62%,97.38%,0.001,0.0,...,0.12 ± 0.07,0.00 ± 0.00,0.00 ± 0.00,0.48 ± 0.29,0.12 ± 0.07,88.14 ± 7.00,88.22 ± 7.01,2.1122 ± 0.0453,100.00 ± 0.00,99.72 ± 0.05
1,ClassBalance,0.500%,0.005,5,165,32980,6.31%,93.69%,0.001,0.0,...,0.12 ± 0.07,0.00 ± 0.00,0.00 ± 0.00,0.50 ± 0.30,0.12 ± 0.08,88.14 ± 7.00,88.52 ± 7.01,2.1122 ± 0.0453,99.99 ± 0.01,99.72 ± 0.05
2,ClassBalance,1.000%,0.010,5,331,32814,10.21%,89.79%,0.001,0.0,...,0.12 ± 0.07,0.00 ± 0.00,0.00 ± 0.00,0.52 ± 0.31,0.13 ± 0.08,88.14 ± 7.00,88.88 ± 7.00,2.1122 ± 0.0453,99.98 ± 0.01,99.72 ± 0.05
3,ClassBalance,5.000%,0.050,5,1657,31488,28.67%,71.33%,0.001,0.0,...,0.12 ± 0.07,0.01 ± 0.02,0.00 ± 0.00,0.65 ± 0.40,0.16 ± 0.10,88.14 ± 7.00,91.36 ± 6.61,2.1122 ± 0.0453,99.83 ± 0.10,99.72 ± 0.05
4,ClassBalance,20.000%,0.200,5,6629,26516,53.73%,46.27%,0.001,0.0,...,0.12 ± 0.07,0.03 ± 0.03,0.01 ± 0.01,0.97 ± 0.60,0.24 ± 0.15,88.14 ± 7.00,96.50 ± 4.09,2.1122 ± 0.0453,97.63 ± 1.11,99.72 ± 0.05

In [ ]:
summary_df = make_final_summary_table(metrics_df, sweep_df, method_name="ClassBalance", save_path="yambda_classbalance_summary.csv")
summary_df