# Yambda LogQ baseline

Этот ноутбук использует тот же preprocessing/split/features, что и Two-Tower, но меняет loss на in-batch softmax с LogQ correction.

Сохраняются только:
- `best_hparams_yambda_logq.json`
- `best_hparams_yambda_logq.leaderboard.csv`
- `logq_summary.csv`

!/usr/bin/env python
coding: utf-8

# Yambda 50M likes — CDN-style Two-Tower baseline

Ноутбук делает baseline под постановку из CDN paper:

- `data/likes.parquet` — positive interactions;
- `data/artist_item_mapping` — item → artist feature;
- `data/album_item_mapping` — item → album feature;
- split: leave-one-out по пользователю:
  - последний interaction → test;
  - предпоследний interaction → validation;
  - остальные → train;
- model: Two-Tower с `user_id`, `item_id`, `artist_id`, `album_id`;
- grid search: `LR × Dropout × Weight Decay`;
- `seed = 0`;
- `num_workers = 1`.

Ожидаемая структура:

```text
data/
    likes.parquet
    album_item_mapping
    artist_item_mapping
```

Если mapping-файлы лежат как `.parquet`, код тоже их найдёт.

## 0. Imports and config

In [1]:


# !pip install -q polars pyarrow torch tqdm numpy pandas

import os
import json
import random
import itertools
import gc
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd
import polars as pl

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from tqdm import tqdm


def set_seed(seed: int = 0):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


CFG = {
    # Paths
    "data_dir": "data",
    "interactions_file": "likes.parquet",
    "artist_file": "artist_item_mapping.parquet",
    "album_file": "album_item_mapping.parquet",

    # Debug/data filtering
    # None = all users; for debugging set 50_000 or 100_000
    "max_users": None,
    "min_user_interactions": 3,
    "min_item_interactions": 5,

    # Model
    "embed_dim": 64,
    "artist_emb_dim": 32,
    "album_emb_dim": 32,
    "tower_hidden": [256, 128, 64],
    "dropout": 0.0,

    # Training
    "batch_size": 4096,
    "grad_clip": 1.0,
    "lr": 1e-3,
    "weight_decay": 0.0,

    # Grid search
    "full_grid": True,
    "tune_fast": True,
    "tune_epochs": 3,
    "tune_val_fraction": 1.00,
    "skip_tune_if_cached": True,
    "cache_path": "best_hparams_yambda_likes_features.json",

    # Final training
    "final_epochs": 20,

    # Evaluation
    "eval_k": [10, 50],
    "eval_batch_users": 128,
    "eval_item_batch": 8192,
    "head_fraction": 0.20,

    # Reproducibility
    "seed": 0,
    "seeds": [0, 1, 2, 3, 4],
}

set_seed(CFG["seed"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)
print(f"Final: {len(CFG['seeds'])} seed(s) × {CFG['final_epochs']} epochs")

device: cuda
Final: 5 seed(s) × 20 epochs

## 1. Load data

In [2]:


def find_file(data_dir: str | Path, name: str) -> Path:
    data_dir = Path(data_dir)
    candidates = [
        data_dir / name,
        data_dir / f"{name}.parquet",
    ]
    for p in candidates:
        if p.exists():
            return p
    raise FileNotFoundError(f"Could not find {name}. Tried: {candidates}")


def normalize_interaction_columns(df: pl.DataFrame) -> pl.DataFrame:
    rename = {}
    for c in df.columns:
        lc = c.lower()
        if lc in {"uid", "user_id", "userid", "user"}:
            rename[c] = "uid"
        elif lc in {"item_id", "itemid", "track_id", "trackid", "song_id"}:
            rename[c] = "item_id"
        elif lc in {"timestamp", "ts", "time", "event_timestamp", "datetime"}:
            rename[c] = "timestamp"
    return df.rename(rename)


def normalize_item_side_columns(df: pl.DataFrame) -> pl.DataFrame:
    rename = {}
    for c in df.columns:
        lc = c.lower()
        if lc in {"item_id", "itemid", "track_id", "trackid"}:
            rename[c] = "item_id"
        elif lc in {"artist_id", "artistid"}:
            rename[c] = "artist_id"
        elif lc in {"album_id", "albumid"}:
            rename[c] = "album_id"
    return df.rename(rename)


DATA_DIR = Path(CFG["data_dir"])
INTERACTIONS_PATH = find_file(DATA_DIR, CFG["interactions_file"])
ARTIST_PATH = find_file(DATA_DIR, CFG["artist_file"])
ALBUM_PATH = find_file(DATA_DIR, CFG["album_file"])

print("interactions:", INTERACTIONS_PATH)
print("artists:", ARTIST_PATH)
print("albums:", ALBUM_PATH)

interactions = pl.read_parquet(INTERACTIONS_PATH)
interactions = normalize_interaction_columns(interactions)

print("raw interactions:", interactions.shape)
print("columns:", interactions.columns)
print(interactions.head())

required = {"uid", "item_id"}
missing = required - set(interactions.columns)
assert not missing, f"Missing required columns {missing}. Available: {interactions.columns}"

if "timestamp" not in interactions.columns:
    print("[WARN] timestamp not found: using row index as timestamp")
    interactions = interactions.with_row_index("timestamp")

interactions = interactions.select(["uid", "item_id", "timestamp"])

# Deduplicate repeated likes by the same user for the same item.
interactions = (
    interactions
    .sort("timestamp")
    .unique(subset=["uid", "item_id"], keep="first")
)

print("after dedup:", interactions.shape)

interactions: data/likes.parquet
artists: data/artist_item_mapping.parquet
albums: data/album_item_mapping.parquet
raw interactions: (881456, 4)
columns: ['uid', 'timestamp', 'item_id', 'is_organic']
shape: (5, 4)
┌─────┬───────────┬─────────┬────────────┐
│ uid ┆ timestamp ┆ item_id ┆ is_organic │
│ --- ┆ ---       ┆ ---     ┆ ---        │
│ u32 ┆ u32       ┆ u32     ┆ u8         │
╞═════╪═══════════╪═════════╪════════════╡
│ 100 ┆ 44755     ┆ 732449  ┆ 1          │
│ 100 ┆ 1155860   ┆ 6568592 ┆ 0          │
│ 100 ┆ 1259125   ┆ 5411243 ┆ 1          │
│ 100 ┆ 1260005   ┆ 7371186 ┆ 0          │
│ 100 ┆ 1263935   ┆ 4943655 ┆ 0          │
└─────┴───────────┴─────────┴────────────┘
after dedup: (844690, 3)

## 2. Filtering

In [3]:


# Item-core filter
item_counts = interactions.group_by("item_id").len().rename({"len": "cnt"})
good_items = item_counts.filter(pl.col("cnt") >= CFG["min_item_interactions"]).select("item_id")
interactions = interactions.join(good_items, on="item_id", how="semi")
print("after item-core:", interactions.shape)

# User-core filter
user_counts = interactions.group_by("uid").len().rename({"len": "cnt"})
good_users = user_counts.filter(pl.col("cnt") >= CFG["min_user_interactions"]).select("uid")
interactions = interactions.join(good_users, on="uid", how="semi")
print("after user-core:", interactions.shape)

# Optional debug subset by users. This does not break histories.
if CFG["max_users"] is not None:
    users_sub = (
        interactions
        .select("uid")
        .unique()
        .sample(n=int(CFG["max_users"]), seed=CFG["seed"])
    )
    interactions = interactions.join(users_sub, on="uid", how="semi")
    print(f"after max_users={CFG['max_users']}:", interactions.shape)

    # Repeat filters after subsampling.
    item_counts = interactions.group_by("item_id").len().rename({"len": "cnt"})
    good_items = item_counts.filter(pl.col("cnt") >= CFG["min_item_interactions"]).select("item_id")
    interactions = interactions.join(good_items, on="item_id", how="semi")

    user_counts = interactions.group_by("uid").len().rename({"len": "cnt"})
    good_users = user_counts.filter(pl.col("cnt") >= CFG["min_user_interactions"]).select("uid")
    interactions = interactions.join(good_users, on="uid", how="semi")

print("final filtered:", interactions.shape)
print("users:", interactions["uid"].n_unique())
print("items:", interactions["item_id"].n_unique())

after item-core: (621417, 3)
after user-core: (620105, 3)
final filtered: (620105, 3)
users: 7102
items: 33145

## 3. ID mapping and leave-one-out split

In [4]:


# User/item ids -> contiguous indices.
user_mapping = interactions.select("uid").unique().sort("uid").with_row_index(name="u_idx")
item_mapping = interactions.select("item_id").unique().sort("item_id").with_row_index(name="i_idx")

inter = (
    interactions
    .join(user_mapping, on="uid", how="inner")
    .join(item_mapping, on="item_id", how="inner")
    .select(["u_idx", "i_idx", "timestamp"])
    .sort(["u_idx", "timestamp"])
)

NUM_USERS = user_mapping.height
NUM_ITEMS = item_mapping.height

inter = inter.with_columns([
    pl.arange(0, pl.len()).over("u_idx").alias("pos"),
    pl.len().over("u_idx").alias("hist_len"),
])

# Leave-one-out evaluation with validation:
# most recent item -> test, second most recent -> validation, rest -> train.
train_df = inter.filter(pl.col("pos") < pl.col("hist_len") - 2).select(["u_idx", "i_idx"])
val_df   = inter.filter(pl.col("pos") == pl.col("hist_len") - 2).select(["u_idx", "i_idx"])
test_df  = inter.filter(pl.col("pos") == pl.col("hist_len") - 1).select(["u_idx", "i_idx"])

train_pairs = train_df.to_numpy().astype(np.int64)
val_np = val_df.to_numpy().astype(np.int64)
test_np = test_df.to_numpy().astype(np.int64)

val_u, val_i = val_np[:, 0], val_np[:, 1]
test_u, test_i = test_np[:, 0], test_np[:, 1]

print(f"NUM_USERS={NUM_USERS:,}")
print(f"NUM_ITEMS={NUM_ITEMS:,}")
print(f"train={len(train_pairs):,} val={len(val_u):,} test={len(test_u):,}")
print(f"catalog share @50 = {50 / NUM_ITEMS:.6f}")

assert len(train_pairs) > 0
assert len(val_u) == NUM_USERS
assert len(test_u) == NUM_USERS

NUM_USERS=7,102
NUM_ITEMS=33,145
train=605,901 val=7,102 test=7,102
catalog share @50 = 0.001509

## 4. Build item features: artist_id and album_id

In [5]:


# item_mapping contains original item_id and new i_idx.
# Features are built in i_idx order.
item_features_df = item_mapping.select(["item_id", "i_idx"])


# ---------- artist feature ----------
artists = pl.read_parquet(ARTIST_PATH)
artists = normalize_item_side_columns(artists)

print("artists shape:", artists.shape)
print("artists columns:", artists.columns)

if "item_id" not in artists.columns or "artist_id" not in artists.columns:
    raise ValueError(f"Bad artist mapping columns: {artists.columns}")

# If an item has multiple artists, take the first one for a simple baseline.
artists_one = (
    artists
    .select(["item_id", "artist_id"])
    .drop_nulls(["item_id", "artist_id"])
    .group_by("item_id")
    .agg(pl.col("artist_id").first())
)

item_features_df = item_features_df.join(artists_one, on="item_id", how="left")


# ---------- album feature ----------
albums = pl.read_parquet(ALBUM_PATH)
albums = normalize_item_side_columns(albums)

print("albums shape:", albums.shape)
print("albums columns:", albums.columns)

if "item_id" not in albums.columns or "album_id" not in albums.columns:
    raise ValueError(f"Bad album mapping columns: {albums.columns}")

# If an item has multiple albums, take the first one for a simple baseline.
albums_one = (
    albums
    .select(["item_id", "album_id"])
    .drop_nulls(["item_id", "album_id"])
    .group_by("item_id")
    .agg(pl.col("album_id").first())
)

item_features_df = item_features_df.join(albums_one, on="item_id", how="left")


# ---------- categorical encoding ----------
item_features_df = item_features_df.sort("i_idx")

# unknown = 0, real categories = 1..N
unique_artists = (
    item_features_df
    .select("artist_id")
    .drop_nulls()
    .unique()
    .sort("artist_id")
    .with_row_index(name="artist_idx", offset=1)
)

item_features_df = (
    item_features_df
    .join(unique_artists, on="artist_id", how="left")
    .with_columns(pl.col("artist_idx").fill_null(0).cast(pl.Int64))
)

unique_albums = (
    item_features_df
    .select("album_id")
    .drop_nulls()
    .unique()
    .sort("album_id")
    .with_row_index(name="album_idx", offset=1)
)

item_features_df = (
    item_features_df
    .join(unique_albums, on="album_id", how="left")
    .with_columns(pl.col("album_idx").fill_null(0).cast(pl.Int64))
)

ITEM_ARTIST = item_features_df["artist_idx"].to_numpy().astype(np.int64)
ITEM_ALBUM = item_features_df["album_idx"].to_numpy().astype(np.int64)

NUM_ARTISTS = int(ITEM_ARTIST.max()) + 1
NUM_ALBUMS = int(ITEM_ALBUM.max()) + 1

print("NUM_ITEMS:", NUM_ITEMS)
print("NUM_ARTISTS:", NUM_ARTISTS)
print("NUM_ALBUMS:", NUM_ALBUMS)
print("artist unknown share:", float((ITEM_ARTIST == 0).mean()))
print("album unknown share:", float((ITEM_ALBUM == 0).mean()))

item_artist_t = torch.from_numpy(ITEM_ARTIST).long().to(device)
item_album_t = torch.from_numpy(ITEM_ALBUM).long().to(device)

artists shape: (9271906, 2)
artists columns: ['artist_id', 'item_id']
albums shape: (9651644, 2)
albums columns: ['album_id', 'item_id']
NUM_ITEMS: 33145
NUM_ARTISTS: 9321
NUM_ALBUMS: 23839
artist unknown share: 0.0
album unknown share: 3.017046311660884e-05

## 5. Known items and head/tail split

In [6]:


train_user_items = [set() for _ in range(NUM_USERS)]

for u, i in train_pairs:
    train_user_items[int(u)].add(int(i))

known_val = [set(s) for s in train_user_items]
known_test = [set(s) for s in train_user_items]

# For test, validation item is already known and should be masked.
for u, i in zip(val_u, val_i):
    known_test[int(u)].add(int(i))

# Head/tail is computed only from train frequencies.
item_freq = np.bincount(train_pairs[:, 1], minlength=NUM_ITEMS)
order = np.argsort(-item_freq)

n_head = max(1, int(NUM_ITEMS * CFG["head_fraction"]))
head_mask = np.zeros(NUM_ITEMS, dtype=bool)
head_mask[order[:n_head]] = True

print(f"head={head_mask.sum():,} tail={(~head_mask).sum():,}")
print(f"nonzero train items={np.sum(item_freq > 0):,}")
print(f"zero train items={np.sum(item_freq == 0):,}")
print(f"val true head share={head_mask[val_i].mean():.4f}")
print(f"test true head share={head_mask[test_i].mean():.4f}")

head=6,629 tail=26,516
nonzero train items=33,145
zero train items=0
val true head share=0.5601
test true head share=0.5356

## 6. Dataset and model

In [7]:


class PairDataset(Dataset):
    def __init__(self, pairs: np.ndarray):
        self.pairs = pairs

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        u, i = self.pairs[idx]
        return int(u), int(i)


class MLP(nn.Module):
    def __init__(self, in_dim: int, hidden: list[int], dropout: float = 0.0):
        super().__init__()

        layers = []
        d = in_dim

        for h in hidden:
            layers.append(nn.Linear(d, h))
            layers.append(nn.ReLU())

            if dropout > 0:
                layers.append(nn.Dropout(dropout))

            d = h

        self.net = nn.Sequential(*layers)
        self.out_dim = d

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class TwoTower(nn.Module):
    """
    Two-Tower baseline:
      user tower: user_id -> MLP
      item tower: item_id + artist_id + album_id -> MLP
    """
    def __init__(
        self,
        num_users: int,
        num_items: int,
        num_artists: int,
        num_albums: int,
        embed_dim: int = 64,
        artist_emb_dim: int = 32,
        album_emb_dim: int = 32,
        hidden: list[int] = [256, 128, 64],
        dropout: float = 0.0,
    ):
        super().__init__()

        self.user_emb = nn.Embedding(num_users, embed_dim)

        self.item_emb = nn.Embedding(num_items, embed_dim)
        self.artist_emb = nn.Embedding(num_artists, artist_emb_dim)
        self.album_emb = nn.Embedding(num_albums, album_emb_dim)

        user_in_dim = embed_dim
        item_in_dim = embed_dim + artist_emb_dim + album_emb_dim

        self.user_mlp = MLP(user_in_dim, hidden, dropout)
        self.item_mlp = MLP(item_in_dim, hidden, dropout)

        self.user_ln = nn.LayerNorm(self.user_mlp.out_dim)
        self.item_ln = nn.LayerNorm(self.item_mlp.out_dim)

        self.init_weights()

    def init_weights(self):
        for emb in [self.user_emb, self.item_emb, self.artist_emb, self.album_emb]:
            nn.init.normal_(emb.weight, std=0.01)

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def user_vec(self, u: torch.Tensor) -> torch.Tensor:
        x = self.user_emb(u)
        x = self.user_mlp(x)
        x = self.user_ln(x)
        return x

    def item_vec(self, i: torch.Tensor) -> torch.Tensor:
        item_id_vec = self.item_emb(i)
        artist_vec = self.artist_emb(item_artist_t[i])
        album_vec = self.album_emb(item_album_t[i])

        x = torch.cat([item_id_vec, artist_vec, album_vec], dim=-1)
        x = self.item_mlp(x)
        x = self.item_ln(x)
        return x

    def forward(self, u: torch.Tensor, i: torch.Tensor) -> torch.Tensor:
        uv = F.normalize(self.user_vec(u), dim=-1, eps=1e-6)
        iv = F.normalize(self.item_vec(i), dim=-1, eps=1e-6)
        return (uv * iv).sum(dim=-1)


def inbatch_softmax_loss(user_vecs: torch.Tensor, item_vecs: torch.Tensor):
    u = F.normalize(user_vecs, dim=-1, eps=1e-6)
    v = F.normalize(item_vecs, dim=-1, eps=1e-6)

    logits = u @ v.T
    labels = torch.arange(logits.size(0), device=logits.device)

    return F.cross_entropy(logits, labels)


train_loader = DataLoader(
    PairDataset(train_pairs),
    batch_size=CFG["batch_size"],
    shuffle=True,
    drop_last=True,
    pin_memory=torch.cuda.is_available(),
)

model = TwoTower(
    NUM_USERS,
    NUM_ITEMS,
    NUM_ARTISTS,
    NUM_ALBUMS,
    embed_dim=CFG["embed_dim"],
    artist_emb_dim=CFG["artist_emb_dim"],
    album_emb_dim=CFG["album_emb_dim"],
    hidden=CFG["tower_hidden"],
    dropout=CFG["dropout"],
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=CFG["lr"],
    weight_decay=CFG["weight_decay"],
)

print(model)

TwoTower(
  (user_emb): Embedding(7102, 64)
  (item_emb): Embedding(33145, 64)
  (artist_emb): Embedding(9321, 32)
  (album_emb): Embedding(23839, 32)
  (user_mlp): MLP(
    (net): Sequential(
      (0): Linear(in_features=64, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=128, bias=True)
      (3): ReLU()
      (4): Linear(in_features=128, out_features=64, bias=True)
      (5): ReLU()
    )
  )
  (item_mlp): MLP(
    (net): Sequential(
      (0): Linear(in_features=128, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=128, bias=True)
      (3): ReLU()
      (4): Linear(in_features=128, out_features=64, bias=True)
      (5): ReLU()
    )
  )
  (user_ln): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
  (item_ln): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
)

## 7. Evaluation

In [8]:


@torch.no_grad()
def evaluate_full_corpus(
    model: nn.Module,
    users: np.ndarray,
    true_items: np.ndarray,
    known_user_items: List[set],
    head_mask: np.ndarray,
    ks: List[int],
    item_freq: np.ndarray,
    user_batch_size: int = 128,
    item_batch_size: int = 8192,
):
    model.eval()

    ranks_all = []
    ranks_head = []
    ranks_tail = []

    max_k = max(ks)

    # Для coverage / popularity / personalization
    recommended_by_k = {k: [] for k in ks}

    # ============================================================
    # 1. Считаем вектора всех items один раз
    # ============================================================

    item_vectors = []

    for s in tqdm(
        range(0, NUM_ITEMS, item_batch_size),
        desc="item vectors",
        leave=False,
    ):
        e = min(s + item_batch_size, NUM_ITEMS)
        idx = torch.arange(s, e, device=device)

        v = model.item_vec(idx)
        v = F.normalize(v, dim=-1, eps=1e-6)

        if not torch.isfinite(v).all():
            raise RuntimeError(f"Non-finite item vectors on item batch {s}:{e}")

        item_vectors.append(v.cpu())

    item_vectors = torch.cat(item_vectors, dim=0).to(device)

    if not torch.isfinite(item_vectors).all():
        raise RuntimeError("Non-finite item vectors after concat")

    # ============================================================
    # 2. Идём по пользователям батчами
    # ============================================================

    for start in tqdm(
        range(0, len(users), user_batch_size),
        desc="eval users",
        leave=False,
    ):
        end = min(start + user_batch_size, len(users))

        bu = users[start:end]
        bi = true_items[start:end]

        ut = torch.tensor(bu, device=device, dtype=torch.long)

        uvec = model.user_vec(ut)
        uvec = F.normalize(uvec, dim=-1, eps=1e-6)

        if not torch.isfinite(uvec).all():
            raise RuntimeError(f"Non-finite user vectors on user batch {start}:{end}")

        scores = (uvec @ item_vectors.T).cpu().numpy()

        if not np.isfinite(scores).all():
            bad = np.sum(~np.isfinite(scores))
            raise RuntimeError(
                f"Non-finite scores in user batch {start}:{end}: {bad} bad values"
            )

        # ========================================================
        # 3. Для каждого пользователя считаем rank и top-K
        # ========================================================

        for row, (u, true_i) in enumerate(zip(bu, bi)):
            u = int(u)
            true_i = int(true_i)

            srow = scores[row].copy()

            if true_i < 0 or true_i >= NUM_ITEMS:
                raise RuntimeError(
                    f"true_i out of bounds: user={u}, true_i={true_i}, NUM_ITEMS={NUM_ITEMS}"
                )

            if not np.isfinite(srow[true_i]):
                raise RuntimeError(
                    f"Non-finite true item score: user={u}, item={true_i}"
                )

            # Маскируем уже известные items пользователя
            for it in known_user_items[u]:
                if it != true_i:
                    srow[it] = -1e9

            if not np.isfinite(srow[true_i]):
                raise RuntimeError(
                    f"True item was masked or became non-finite: user={u}, item={true_i}"
                )

            # ----------------------------------------------------
            # Rank true item
            # pessimistic tie handling:
            # если у многих items одинаковый score, true item НЕ считается первым
            # ----------------------------------------------------

            true_score = srow[true_i]
            eps = 1e-12

            num_greater = int((srow > true_score + eps).sum())
            num_tied = int((np.abs(srow - true_score) <= eps).sum())

            rank = num_greater + num_tied - 1

            ranks_all.append(rank)

            if head_mask[true_i]:
                ranks_head.append(rank)
            else:
                ranks_tail.append(rank)

            # ----------------------------------------------------
            # Top-K recommendations для coverage/popularity
            # ----------------------------------------------------

            if max_k < len(srow):
                top_unsorted = np.argpartition(-srow, max_k - 1)[:max_k]
                top_idx = top_unsorted[np.argsort(-srow[top_unsorted])]
            else:
                top_idx = np.argsort(-srow)

            for k in ks:
                recommended_by_k[k].append(top_idx[:k].astype(np.int64))

    # ============================================================
    # 4. Accuracy metrics: HR / NDCG
    # ============================================================

    def agg_accuracy(ranks: List[int]) -> Dict[str, float]:
        a = np.asarray(ranks, dtype=np.int64)
        out = {}

        for k in ks:
            if len(a) == 0:
                out[f"HR@{k}"] = np.nan
                out[f"NDCG@{k}"] = np.nan
            else:
                hits = a < k

                out[f"HR@{k}"] = 100.0 * hits.mean()

                out[f"NDCG@{k}"] = 100.0 * np.where(
                    hits,
                    1.0 / np.log2(a + 2),
                    0.0,
                ).mean()

        return out

    # ============================================================
    # 5. Long-tail / coverage metrics
    # ============================================================

    tail_mask = ~head_mask
    num_tail_items = int(tail_mask.sum())

    # item_freq нужен именно здесь
    popularity = np.log1p(item_freq.astype(np.float64))

    long_tail_metrics = {}

    for k in ks:
        recs = np.vstack(recommended_by_k[k])  # shape: (num_eval_users, k)

        unique_recs = np.unique(recs)

        # CatalogCoverage@K
        catalog_coverage = len(unique_recs) / NUM_ITEMS

        # TailCoverage@K
        if num_tail_items > 0:
            tail_coverage = np.sum(tail_mask[unique_recs]) / num_tail_items
        else:
            tail_coverage = np.nan

        # AvgPopularity@K
        avg_popularity = popularity[recs].mean()

        # TailRatio@K
        tail_ratio = tail_mask[recs].mean()

        # Personalization@K
        # 1 - average pairwise overlap / K
        # считаем эффективно через exposure counts
        n_users_eval = recs.shape[0]

        if n_users_eval <= 1:
            personalization = np.nan
        else:
            exposure_counts = np.bincount(
                recs.reshape(-1),
                minlength=NUM_ITEMS,
            )

            pairwise_intersections = np.sum(
                exposure_counts * (exposure_counts - 1) / 2
            )

            num_user_pairs = n_users_eval * (n_users_eval - 1) / 2
            avg_overlap = pairwise_intersections / num_user_pairs

            personalization = 1.0 - avg_overlap / k

        long_tail_metrics[f"CatalogCoverage@{k}"] = 100.0 * catalog_coverage
        long_tail_metrics[f"TailCoverage@{k}"] = 100.0 * tail_coverage
        long_tail_metrics[f"AvgPopularity@{k}"] = float(avg_popularity)
        long_tail_metrics[f"TailRatio@{k}"] = 100.0 * tail_ratio
        long_tail_metrics[f"Personalization@{k}"] = 100.0 * personalization

    return {
        "overall": agg_accuracy(ranks_all),
        "head": agg_accuracy(ranks_head),
        "tail": agg_accuracy(ranks_tail),
        "long_tail": long_tail_metrics,
        "counts": {
            "overall": len(ranks_all),
            "head": len(ranks_head),
            "tail": len(ranks_tail),
        },
    }


def print_metrics(metrics: Dict):
    print("counts:", metrics.get("counts", {}))

    for split in ["overall", "head", "tail"]:
        print(f"[{split}]", metrics[split])

    if "long_tail" in metrics:
        print("[long_tail]", metrics["long_tail"])

In [9]:


def make_head_mask(item_freq: np.ndarray, head_fraction: float) -> np.ndarray:
    num_items = len(item_freq)
    n_head = max(1, int(num_items * head_fraction))

    order = np.argsort(-item_freq)

    current_head_mask = np.zeros(num_items, dtype=bool)
    current_head_mask[order[:n_head]] = True

    return current_head_mask


@torch.no_grad()
def evaluate_head_tail_sweep(
    model: nn.Module,
    method_name: str,
    seed: int,
    head_fractions: List[float],
    test_u: np.ndarray,
    test_i: np.ndarray,
    known_test: List[set],
    item_freq: np.ndarray,
    ks: List[int],
):
    rows = []

    model.eval()

    for hf in head_fractions:
        print("\n" + "=" * 80)
        print(f"{method_name} | seed={seed} | head_fraction={hf} ({100 * hf:.3f}%)")
        print("=" * 80)

        current_head_mask = make_head_mask(
            item_freq=item_freq,
            head_fraction=hf,
        )

        num_head_items = int(current_head_mask.sum())
        num_tail_items = int((~current_head_mask).sum())

        test_head_share = float(current_head_mask[test_i].mean())
        test_tail_share = float((~current_head_mask[test_i]).mean())

        print(f"num_head_items: {num_head_items:,}")
        print(f"num_tail_items: {num_tail_items:,}")
        print(f"test_head_share: {test_head_share:.4f}")
        print(f"test_tail_share: {test_tail_share:.4f}")

        metrics = evaluate_full_corpus(
            model=model,
            users=test_u,
            true_items=test_i,
            known_user_items=known_test,
            head_mask=current_head_mask,
            ks=ks,
            item_freq=item_freq,
            user_batch_size=CFG["eval_batch_users"],
            item_batch_size=CFG["eval_item_batch"],
        )

        print_metrics(metrics)

        row = {
            "method": method_name,
            "seed": seed,
            "head_fraction": hf,
            "head_percent": 100.0 * hf,
            "num_head_items": num_head_items,
            "num_tail_items": num_tail_items,
            "test_head_share": test_head_share,
            "test_tail_share": test_tail_share,
        }

        for split in ("overall", "head", "tail"):
            for key, value in metrics[split].items():
                row[f"{split}_{key}"] = value

        if "long_tail" in metrics:
            for key, value in metrics["long_tail"].items():
                row[key] = value

        if "counts" in metrics:
            for key, value in metrics["counts"].items():
                row[f"count_{key}"] = value

        rows.append(row)

    return rows

In [10]:
# Override method-specific config
CFG["cache_path"] = "best_hparams_yambda_logq.json"
CFG["logq_weight"] = 1.0

## 8. LogQ loss

In [11]:

def build_logq_from_item_freq(item_freq: np.ndarray, eps: float = 1e-12) -> torch.Tensor:
    freq = item_freq.astype(np.float64)
    q = freq / max(freq.sum(), 1.0)
    q = np.maximum(q, eps)
    return torch.from_numpy(np.log(q).astype(np.float32))


logq_t = build_logq_from_item_freq(item_freq).to(device)

print("LogQ stats")
print("  min logq:", float(logq_t.min().item()))
print("  max logq:", float(logq_t.max().item()))
print("  mean logq:", float(logq_t.mean().item()))


def logq_inbatch_softmax_loss(
    user_vecs: torch.Tensor,
    item_vecs: torch.Tensor,
    pos_items: torch.Tensor,
    logq: torch.Tensor,
    logq_weight: float = 1.0,
):
    u = F.normalize(user_vecs, dim=-1, eps=1e-6)
    v = F.normalize(item_vecs, dim=-1, eps=1e-6)

    logits = u @ v.T

    # Column-wise correction for candidate items from the batch.
    corr = logq[pos_items].view(1, -1)
    logits = logits - logq_weight * corr

    labels = torch.arange(logits.size(0), device=logits.device)
    return F.cross_entropy(logits, labels)

LogQ stats
  min logq: -13.314472198486328
  max logq: -6.701087474822998
  mean logq: -10.867216110229492

## 9. Grid search

In [12]:

if CFG["full_grid"]:
    LR_GRID          = [1e-4, 1e-3, 3e-3, 1e-2]
    DROPOUT_GRID     = [0.0, 0.1, 0.2, 0.3, 0.5]
    WD_GRID          = [0.0, 1e-4, 1e-3]
    LOGQ_WEIGHT_GRID = [0.1, 1.0, 10.0]
else:
    LR_GRID          = [1e-3, 1e-2]
    DROPOUT_GRID     = [0.0, 0.3]
    WD_GRID          = [0.0, 1e-4]
    LOGQ_WEIGHT_GRID = [0.1, 1.0]

combos = list(itertools.product(LR_GRID, DROPOUT_GRID, WD_GRID, LOGQ_WEIGHT_GRID))
k_main = CFG["eval_k"][-1]

cache_path = Path(CFG["cache_path"])
leaderboard_csv_path = cache_path.with_suffix(".leaderboard.csv")

if CFG["skip_tune_if_cached"] and cache_path.exists():
    best_hp = json.loads(cache_path.read_text())
    print(f"Loaded cached hparams: {best_hp}")
    leaderboard_df = pd.read_csv(leaderboard_csv_path) if leaderboard_csv_path.exists() else None
else:
    frac = float(CFG.get("tune_val_fraction", 1.0))
    if frac < 1.0 and CFG["tune_fast"]:
        n_tune = max(1, int(len(val_u) * frac))
        _idx = np.random.default_rng(42).choice(len(val_u), n_tune, replace=False)
        val_u_t, val_i_t = val_u[_idx], val_i[_idx]
    else:
        val_u_t, val_i_t = val_u, val_i

    tune_ep = CFG["tune_epochs"] if CFG["tune_fast"] else CFG["final_epochs"]

    print(f"Tuning LogQ {len(combos)} trials × {tune_ep} ep (val subset: {len(val_u_t):,}/{len(val_u):,})")

    best_hr = -1.0
    best_hp = None
    leaderboard = []

    for ti, (lr, dr, wd, logq_weight) in enumerate(combos, 1):
        set_seed(CFG["seed"])

        m = TwoTower(
            NUM_USERS, NUM_ITEMS, NUM_ARTISTS, NUM_ALBUMS,
            embed_dim=CFG["embed_dim"],
            artist_emb_dim=CFG["artist_emb_dim"],
            album_emb_dim=CFG["album_emb_dim"],
            hidden=CFG["tower_hidden"],
            dropout=dr,
        ).to(device)

        opt = torch.optim.Adam(m.parameters(), lr=lr, weight_decay=wd)

        status = "ok"
        error_message = ""
        avg_loss = np.nan
        met = None
        hr = -1.0

        try:
            for ep in range(1, tune_ep + 1):
                m.train()
                total_loss, total_n = 0.0, 0
                pbar = tqdm(train_loader, desc=f"LogQ trial{ti} {ep}/{tune_ep}", leave=False)

                for users_batch, items_batch in pbar:
                    users_batch = users_batch.to(device, non_blocking=True)
                    items_batch = items_batch.to(device, non_blocking=True)

                    user_vecs = m.user_vec(users_batch)
                    item_vecs = m.item_vec(items_batch)

                    loss = logq_inbatch_softmax_loss(user_vecs, item_vecs, items_batch, logq_t, logq_weight)

                    if not torch.isfinite(loss):
                        raise RuntimeError(f"Non-finite loss: {loss.item()}")

                    opt.zero_grad(set_to_none=True)
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(m.parameters(), CFG["grad_clip"])
                    opt.step()

                    bs = users_batch.size(0)
                    total_loss += loss.item() * bs
                    total_n += bs
                    pbar.set_postfix(loss=f"{loss.item():.4f}")

                avg_loss = total_loss / max(total_n, 1)
                print(f"  LogQ trial{ti} ep{ep} loss={avg_loss:.4f}")

            met = evaluate_full_corpus(
                model=m,
                users=val_u_t,
                true_items=val_i_t,
                known_user_items=known_val,
                head_mask=head_mask,
                ks=CFG["eval_k"],
                item_freq=item_freq,
                user_batch_size=CFG["eval_batch_users"],
                item_batch_size=CFG["eval_item_batch"],
            )
            hr = met["overall"][f"HR@{k_main}"]
            if not np.isfinite(hr):
                raise RuntimeError(f"Non-finite HR: {hr}")
        except RuntimeError as e:
            status = "failed"
            error_message = str(e)
            print(f"  LogQ trial {ti} FAILED: {e}")

        row = {
            "trial": ti,
            "status": status,
            "error": error_message,
            "method": "LogQ",
            "lr": lr,
            "dropout": dr,
            "weight_decay": wd,
            "logq_weight": logq_weight,
            "tune_epochs": tune_ep,
            "val_subset_size": len(val_u_t),
            "val_full_size": len(val_u),
            "final_train_loss": avg_loss,
            f"val_HR@{k_main}": hr,
        }

        if met is not None:
            for split in ("overall", "head", "tail"):
                for key, value in met[split].items():
                    row[f"val_{split}_{key}"] = value
            if "long_tail" in met:
                for key, value in met["long_tail"].items():
                    row[f"val_{key}"] = value
            if "counts" in met:
                for key, value in met["counts"].items():
                    row[f"val_count_{key}"] = value

        leaderboard.append(row)
        print(f"  LogQ trial {ti:3d}/{len(combos)} lr={lr:.0e} dr={dr} wd={wd:.0e} logq_w={logq_weight:g} -> val HR@{k_main}={hr:.2f}%")

        if status == "ok" and hr > best_hr:
            best_hr = hr
            best_hp = {"lr": lr, "dropout": dr, "weight_decay": wd, "logq_weight": logq_weight, f"val_HR@{k_main}": hr}

        del m, opt
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    leaderboard_df = pd.DataFrame(leaderboard).sort_values(f"val_HR@{k_main}", ascending=False, na_position="last")
    leaderboard_df.to_csv(leaderboard_csv_path, index=False)

    if best_hp is None:
        raise RuntimeError("No successful grid-search trial. Check leaderboard for errors.")

    cache_path.write_text(json.dumps(best_hp, indent=2))
    print(f"\nBest LogQ val HR@{k_main}={best_hr:.2f}% -> {best_hp}")
    print(f"Saved best hparams: {cache_path}")
    print(f"Saved leaderboard CSV: {leaderboard_csv_path}")

leaderboard_df.head(10) if leaderboard_df is not None else None

Tuning LogQ 180 trials × 3 ep (val subset: 7,102/7,102)

  LogQ trial1 ep1 loss=8.3229

  LogQ trial1 ep2 loss=8.2550

  LogQ trial1 ep3 loss=8.1191

  LogQ trial   1/180 lr=1e-04 dr=0.0 wd=0e+00 logq_w=0.1 -> val HR@50=0.83%

  LogQ trial2 ep1 loss=8.6397

  LogQ trial2 ep2 loss=8.4381

  LogQ trial2 ep3 loss=8.4234

  LogQ trial   2/180 lr=1e-04 dr=0.0 wd=0e+00 logq_w=1 -> val HR@50=2.42%

  LogQ trial3 ep1 loss=24.9391

  LogQ trial3 ep2 loss=23.9155

  LogQ trial3 ep3 loss=23.7374

  LogQ trial   3/180 lr=1e-04 dr=0.0 wd=0e+00 logq_w=10 -> val HR@50=1.30%

  LogQ trial4 ep1 loss=8.3222

  LogQ trial4 ep2 loss=8.2410

  LogQ trial4 ep3 loss=8.1026

  LogQ trial   4/180 lr=1e-04 dr=0.0 wd=1e-04 logq_w=0.1 -> val HR@50=0.77%

  LogQ trial5 ep1 loss=8.6179

  LogQ trial5 ep2 loss=8.4270

  LogQ trial5 ep3 loss=8.4178

  LogQ trial   5/180 lr=1e-04 dr=0.0 wd=1e-04 logq_w=1 -> val HR@50=2.80%

  LogQ trial6 ep1 loss=24.8594

  LogQ trial6 ep2 loss=23.8179

  LogQ trial6 ep3 loss=23.7249

  LogQ trial   6/180 lr=1e-04 dr=0.0 wd=1e-04 logq_w=10 -> val HR@50=1.38%

  LogQ trial7 ep1 loss=8.3216

  LogQ trial7 ep2 loss=8.2292

  LogQ trial7 ep3 loss=8.0870

  LogQ trial   7/180 lr=1e-04 dr=0.0 wd=1e-03 logq_w=0.1 -> val HR@50=0.83%

  LogQ trial8 ep1 loss=8.6169

  LogQ trial8 ep2 loss=8.4332

  LogQ trial8 ep3 loss=8.4248

  LogQ trial   8/180 lr=1e-04 dr=0.0 wd=1e-03 logq_w=1 -> val HR@50=2.60%

  LogQ trial9 ep1 loss=24.9007

  LogQ trial9 ep2 loss=23.8969

  LogQ trial9 ep3 loss=23.7692

  LogQ trial   9/180 lr=1e-04 dr=0.0 wd=1e-03 logq_w=10 -> val HR@50=0.82%

  LogQ trial10 ep1 loss=8.3250

  LogQ trial10 ep2 loss=8.3205

  LogQ trial10 ep3 loss=8.2569

  LogQ trial  10/180 lr=1e-04 dr=0.1 wd=0e+00 logq_w=0.1 -> val HR@50=0.48%

  LogQ trial11 ep1 loss=8.6986

  LogQ trial11 ep2 loss=8.4921

  LogQ trial11 ep3 loss=8.4720

  LogQ trial  11/180 lr=1e-04 dr=0.1 wd=0e+00 logq_w=1 -> val HR@50=1.90%

  LogQ trial12 ep1 loss=25.1436

  LogQ trial12 ep2 loss=24.2911

  LogQ trial12 ep3 loss=24.0372

  LogQ trial  12/180 lr=1e-04 dr=0.1 wd=0e+00 logq_w=10 -> val HR@50=1.14%

  LogQ trial13 ep1 loss=8.3247

  LogQ trial13 ep2 loss=8.3179

  LogQ trial13 ep3 loss=8.2330

  LogQ trial  13/180 lr=1e-04 dr=0.1 wd=1e-04 logq_w=0.1 -> val HR@50=0.66%

  LogQ trial14 ep1 loss=8.6855

  LogQ trial14 ep2 loss=8.4845

  LogQ trial14 ep3 loss=8.4694

  LogQ trial  14/180 lr=1e-04 dr=0.1 wd=1e-04 logq_w=1 -> val HR@50=1.79%

  LogQ trial15 ep1 loss=25.0828

  LogQ trial15 ep2 loss=24.1813

  LogQ trial15 ep3 loss=24.0219

  LogQ trial  15/180 lr=1e-04 dr=0.1 wd=1e-04 logq_w=10 -> val HR@50=1.11%

  LogQ trial16 ep1 loss=8.3243

  LogQ trial16 ep2 loss=8.3102

  LogQ trial16 ep3 loss=8.2095

  LogQ trial  16/180 lr=1e-04 dr=0.1 wd=1e-03 logq_w=0.1 -> val HR@50=0.63%

  LogQ trial17 ep1 loss=8.6825

  LogQ trial17 ep2 loss=8.4826

  LogQ trial17 ep3 loss=8.4679

  LogQ trial  17/180 lr=1e-04 dr=0.1 wd=1e-03 logq_w=1 -> val HR@50=1.68%

  LogQ trial18 ep1 loss=25.1120

  LogQ trial18 ep2 loss=24.2612

  LogQ trial18 ep3 loss=24.0547

  LogQ trial  18/180 lr=1e-04 dr=0.1 wd=1e-03 logq_w=10 -> val HR@50=0.27%

  LogQ trial19 ep1 loss=8.3256

  LogQ trial19 ep2 loss=8.3241

  LogQ trial19 ep3 loss=8.3226

  LogQ trial  19/180 lr=1e-04 dr=0.2 wd=0e+00 logq_w=0.1 -> val HR@50=3.38%

  LogQ trial20 ep1 loss=8.7640

  LogQ trial20 ep2 loss=8.5500

  LogQ trial20 ep3 loss=8.5222

  LogQ trial  20/180 lr=1e-04 dr=0.2 wd=0e+00 logq_w=1 -> val HR@50=1.91%

  LogQ trial21 ep1 loss=25.3041

  LogQ trial21 ep2 loss=24.6495

  LogQ trial21 ep3 loss=24.3432

  LogQ trial  21/180 lr=1e-04 dr=0.2 wd=0e+00 logq_w=10 -> val HR@50=0.23%

  LogQ trial22 ep1 loss=8.3254

  LogQ trial22 ep2 loss=8.3235

  LogQ trial22 ep3 loss=8.3203

  LogQ trial  22/180 lr=1e-04 dr=0.2 wd=1e-04 logq_w=0.1 -> val HR@50=3.45%

  LogQ trial23 ep1 loss=8.7545

  LogQ trial23 ep2 loss=8.5429

  LogQ trial23 ep3 loss=8.5187

  LogQ trial  23/180 lr=1e-04 dr=0.2 wd=1e-04 logq_w=1 -> val HR@50=1.34%

  LogQ trial24 ep1 loss=25.2724

  LogQ trial24 ep2 loss=24.5493

  LogQ trial24 ep3 loss=24.2889

  LogQ trial  24/180 lr=1e-04 dr=0.2 wd=1e-04 logq_w=10 -> val HR@50=0.13%

  LogQ trial25 ep1 loss=8.3252

  LogQ trial25 ep2 loss=8.3215

  LogQ trial25 ep3 loss=8.3056

  LogQ trial  25/180 lr=1e-04 dr=0.2 wd=1e-03 logq_w=0.1 -> val HR@50=1.80%

  LogQ trial26 ep1 loss=8.7498

  LogQ trial26 ep2 loss=8.5386

  LogQ trial26 ep3 loss=8.5163

  LogQ trial  26/180 lr=1e-04 dr=0.2 wd=1e-03 logq_w=1 -> val HR@50=1.97%

  LogQ trial27 ep1 loss=25.2789

  LogQ trial27 ep2 loss=24.5874

  LogQ trial27 ep3 loss=24.3716

  LogQ trial  27/180 lr=1e-04 dr=0.2 wd=1e-03 logq_w=10 -> val HR@50=0.01%

  LogQ trial28 ep1 loss=8.3262

  LogQ trial28 ep2 loss=8.3246

  LogQ trial28 ep3 loss=8.3244

  LogQ trial  28/180 lr=1e-04 dr=0.3 wd=0e+00 logq_w=0.1 -> val HR@50=1.94%

  LogQ trial29 ep1 loss=8.8306

  LogQ trial29 ep2 loss=8.6133

  LogQ trial29 ep3 loss=8.5752

  LogQ trial  29/180 lr=1e-04 dr=0.3 wd=0e+00 logq_w=1 -> val HR@50=0.59%

  LogQ trial30 ep1 loss=25.4258

  LogQ trial30 ep2 loss=24.9343

  LogQ trial30 ep3 loss=24.6012

  LogQ trial  30/180 lr=1e-04 dr=0.3 wd=0e+00 logq_w=10 -> val HR@50=0.06%

  LogQ trial31 ep1 loss=8.3260

  LogQ trial31 ep2 loss=8.3245

  LogQ trial31 ep3 loss=8.3236

  LogQ trial  31/180 lr=1e-04 dr=0.3 wd=1e-04 logq_w=0.1 -> val HR@50=3.34%

  LogQ trial32 ep1 loss=8.8183

  LogQ trial32 ep2 loss=8.5959

  LogQ trial32 ep3 loss=8.5573

  LogQ trial  32/180 lr=1e-04 dr=0.3 wd=1e-04 logq_w=1 -> val HR@50=1.72%

  LogQ trial33 ep1 loss=25.3969

  LogQ trial33 ep2 loss=24.8632

  LogQ trial33 ep3 loss=24.5712

  LogQ trial  33/180 lr=1e-04 dr=0.3 wd=1e-04 logq_w=10 -> val HR@50=0.13%

  LogQ trial34 ep1 loss=8.3259

  LogQ trial34 ep2 loss=8.3232

  LogQ trial34 ep3 loss=8.3198

  LogQ trial  34/180 lr=1e-04 dr=0.3 wd=1e-03 logq_w=0.1 -> val HR@50=3.41%

  LogQ trial35 ep1 loss=8.8079

  LogQ trial35 ep2 loss=8.5563

  LogQ trial35 ep3 loss=8.5234

  LogQ trial  35/180 lr=1e-04 dr=0.3 wd=1e-03 logq_w=1 -> val HR@50=2.52%

  LogQ trial36 ep1 loss=25.4057

  LogQ trial36 ep2 loss=24.8678

  LogQ trial36 ep3 loss=24.5888

  LogQ trial  36/180 lr=1e-04 dr=0.3 wd=1e-03 logq_w=10 -> val HR@50=0.08%

  LogQ trial37 ep1 loss=8.3277

  LogQ trial37 ep2 loss=8.3251

  LogQ trial37 ep3 loss=8.3247

  LogQ trial  37/180 lr=1e-04 dr=0.5 wd=0e+00 logq_w=0.1 -> val HR@50=0.23%

  LogQ trial38 ep1 loss=8.8973

  LogQ trial38 ep2 loss=8.8483

  LogQ trial38 ep3 loss=8.7052

  LogQ trial  38/180 lr=1e-04 dr=0.5 wd=0e+00 logq_w=1 -> val HR@50=1.17%

  LogQ trial39 ep1 loss=25.4935

  LogQ trial39 ep2 loss=25.4058

  LogQ trial39 ep3 loss=25.1860

  LogQ trial  39/180 lr=1e-04 dr=0.5 wd=0e+00 logq_w=10 -> val HR@50=0.45%

  LogQ trial40 ep1 loss=8.3275

  LogQ trial40 ep2 loss=8.3250

  LogQ trial40 ep3 loss=8.3246

  LogQ trial  40/180 lr=1e-04 dr=0.5 wd=1e-04 logq_w=0.1 -> val HR@50=0.65%

  LogQ trial41 ep1 loss=8.8934

  LogQ trial41 ep2 loss=8.7650

  LogQ trial41 ep3 loss=8.6145

  LogQ trial  41/180 lr=1e-04 dr=0.5 wd=1e-04 logq_w=1 -> val HR@50=1.80%

  LogQ trial42 ep1 loss=25.4856

  LogQ trial42 ep2 loss=25.3562

  LogQ trial42 ep3 loss=25.0871

  LogQ trial  42/180 lr=1e-04 dr=0.5 wd=1e-04 logq_w=10 -> val HR@50=0.61%

  LogQ trial43 ep1 loss=8.3273

  LogQ trial43 ep2 loss=8.3246

  LogQ trial43 ep3 loss=8.3236

  LogQ trial  43/180 lr=1e-04 dr=0.5 wd=1e-03 logq_w=0.1 -> val HR@50=2.90%

  LogQ trial44 ep1 loss=8.8880

  LogQ trial44 ep2 loss=8.7092

  LogQ trial44 ep3 loss=8.6284

  LogQ trial  44/180 lr=1e-04 dr=0.5 wd=1e-03 logq_w=1 -> val HR@50=2.21%

  LogQ trial45 ep1 loss=25.4882

  LogQ trial45 ep2 loss=25.3644

  LogQ trial45 ep3 loss=25.0958

  LogQ trial  45/180 lr=1e-04 dr=0.5 wd=1e-03 logq_w=10 -> val HR@50=0.31%

  LogQ trial46 ep1 loss=8.1875

  LogQ trial46 ep2 loss=7.9156

  LogQ trial46 ep3 loss=7.8792

  LogQ trial  46/180 lr=1e-03 dr=0.0 wd=0e+00 logq_w=0.1 -> val HR@50=1.70%

  LogQ trial47 ep1 loss=8.4732

  LogQ trial47 ep2 loss=8.3930

  LogQ trial47 ep3 loss=8.3223

  LogQ trial  47/180 lr=1e-03 dr=0.0 wd=0e+00 logq_w=1 -> val HR@50=1.87%

  LogQ trial48 ep1 loss=24.0780

  LogQ trial48 ep2 loss=23.7309

  LogQ trial48 ep3 loss=23.7303

  LogQ trial  48/180 lr=1e-03 dr=0.0 wd=0e+00 logq_w=10 -> val HR@50=0.92%

  LogQ trial49 ep1 loss=8.1787

  LogQ trial49 ep2 loss=7.9162

  LogQ trial49 ep3 loss=7.8726

  LogQ trial  49/180 lr=1e-03 dr=0.0 wd=1e-04 logq_w=0.1 -> val HR@50=2.08%

  LogQ trial50 ep1 loss=8.4709

  LogQ trial50 ep2 loss=8.3959

  LogQ trial50 ep3 loss=8.3277

  LogQ trial  50/180 lr=1e-03 dr=0.0 wd=1e-04 logq_w=1 -> val HR@50=1.72%

  LogQ trial51 ep1 loss=24.0694

  LogQ trial51 ep2 loss=23.7673

  LogQ trial51 ep3 loss=23.7714

  LogQ trial  51/180 lr=1e-03 dr=0.0 wd=1e-04 logq_w=10 -> val HR@50=0.07%

  LogQ trial52 ep1 loss=8.2352

  LogQ trial52 ep2 loss=8.0577

  LogQ trial52 ep3 loss=8.0513

  LogQ trial  52/180 lr=1e-03 dr=0.0 wd=1e-03 logq_w=0.1 -> val HR@50=0.23%

  LogQ trial53 ep1 loss=8.4768

  LogQ trial53 ep2 loss=8.4304

  LogQ trial53 ep3 loss=8.4310

  LogQ trial  53/180 lr=1e-03 dr=0.0 wd=1e-03 logq_w=1 -> val HR@50=3.17%

  LogQ trial54 ep1 loss=24.2336

  LogQ trial54 ep2 loss=23.9641

  LogQ trial54 ep3 loss=23.8215

  LogQ trial  54/180 lr=1e-03 dr=0.0 wd=1e-03 logq_w=10 -> val HR@50=0.08%

  LogQ trial55 ep1 loss=8.2776

  LogQ trial55 ep2 loss=8.0851

  LogQ trial55 ep3 loss=7.9845

  LogQ trial  55/180 lr=1e-03 dr=0.1 wd=0e+00 logq_w=0.1 -> val HR@50=0.97%

  LogQ trial56 ep1 loss=8.5206

  LogQ trial56 ep2 loss=8.4526

  LogQ trial56 ep3 loss=8.4374

  LogQ trial  56/180 lr=1e-03 dr=0.1 wd=0e+00 logq_w=1 -> val HR@50=1.15%

  LogQ trial57 ep1 loss=24.3115

  LogQ trial57 ep2 loss=23.9559

  LogQ trial57 ep3 loss=23.9119

  LogQ trial  57/180 lr=1e-03 dr=0.1 wd=0e+00 logq_w=10 -> val HR@50=0.18%

  LogQ trial58 ep1 loss=8.2625

  LogQ trial58 ep2 loss=8.0972

  LogQ trial58 ep3 loss=8.0007

  LogQ trial  58/180 lr=1e-03 dr=0.1 wd=1e-04 logq_w=0.1 -> val HR@50=1.14%

  LogQ trial59 ep1 loss=8.5127

  LogQ trial59 ep2 loss=8.4534

  LogQ trial59 ep3 loss=8.4402

  LogQ trial  59/180 lr=1e-03 dr=0.1 wd=1e-04 logq_w=1 -> val HR@50=1.08%

  LogQ trial60 ep1 loss=24.2864

  LogQ trial60 ep2 loss=23.9879

  LogQ trial60 ep3 loss=23.9671

  LogQ trial  60/180 lr=1e-03 dr=0.1 wd=1e-04 logq_w=10 -> val HR@50=0.10%

  LogQ trial61 ep1 loss=8.2845

  LogQ trial61 ep2 loss=8.1642

  LogQ trial61 ep3 loss=8.1502

  LogQ trial  61/180 lr=1e-03 dr=0.1 wd=1e-03 logq_w=0.1 -> val HR@50=0.44%

  LogQ trial62 ep1 loss=8.5195

  LogQ trial62 ep2 loss=8.4600

  LogQ trial62 ep3 loss=8.4620

  LogQ trial  62/180 lr=1e-03 dr=0.1 wd=1e-03 logq_w=1 -> val HR@50=1.82%

  LogQ trial63 ep1 loss=24.3877

  LogQ trial63 ep2 loss=24.1302

  LogQ trial63 ep3 loss=24.0259

  LogQ trial  63/180 lr=1e-03 dr=0.1 wd=1e-03 logq_w=10 -> val HR@50=0.06%

  LogQ trial64 ep1 loss=8.3111

  LogQ trial64 ep2 loss=8.1586

  LogQ trial64 ep3 loss=8.0948

  LogQ trial  64/180 lr=1e-03 dr=0.2 wd=0e+00 logq_w=0.1 -> val HR@50=0.54%

  LogQ trial65 ep1 loss=8.5711

  LogQ trial65 ep2 loss=8.4937

  LogQ trial65 ep3 loss=8.4753

  LogQ trial  65/180 lr=1e-03 dr=0.2 wd=0e+00 logq_w=1 -> val HR@50=0.82%

  LogQ trial66 ep1 loss=24.5521

  LogQ trial66 ep2 loss=24.1660

  LogQ trial66 ep3 loss=24.0214

  LogQ trial  66/180 lr=1e-03 dr=0.2 wd=0e+00 logq_w=10 -> val HR@50=0.13%

  LogQ trial67 ep1 loss=8.2955

  LogQ trial67 ep2 loss=8.1474

  LogQ trial67 ep3 loss=8.0899

  LogQ trial  67/180 lr=1e-03 dr=0.2 wd=1e-04 logq_w=0.1 -> val HR@50=0.63%

  LogQ trial68 ep1 loss=8.5624

  LogQ trial68 ep2 loss=8.4937

  LogQ trial68 ep3 loss=8.4687

  LogQ trial  68/180 lr=1e-03 dr=0.2 wd=1e-04 logq_w=1 -> val HR@50=0.92%

  LogQ trial69 ep1 loss=24.5629

  LogQ trial69 ep2 loss=24.2086

  LogQ trial69 ep3 loss=24.1029

  LogQ trial  69/180 lr=1e-03 dr=0.2 wd=1e-04 logq_w=10 -> val HR@50=0.14%

  LogQ trial70 ep1 loss=8.3215

  LogQ trial70 ep2 loss=8.2472

  LogQ trial70 ep3 loss=8.1665

  LogQ trial  70/180 lr=1e-03 dr=0.2 wd=1e-03 logq_w=0.1 -> val HR@50=0.25%

  LogQ trial71 ep1 loss=8.5659

  LogQ trial71 ep2 loss=8.4957

  LogQ trial71 ep3 loss=8.4836

  LogQ trial  71/180 lr=1e-03 dr=0.2 wd=1e-03 logq_w=1 -> val HR@50=1.69%

  LogQ trial72 ep1 loss=24.6473

  LogQ trial72 ep2 loss=24.3212

  LogQ trial72 ep3 loss=24.2132

  LogQ trial  72/180 lr=1e-03 dr=0.2 wd=1e-03 logq_w=10 -> val HR@50=0.51%

  LogQ trial73 ep1 loss=8.3234

  LogQ trial73 ep2 loss=8.2527

  LogQ trial73 ep3 loss=8.1535

  LogQ trial  73/180 lr=1e-03 dr=0.3 wd=0e+00 logq_w=0.1 -> val HR@50=0.90%

  LogQ trial74 ep1 loss=8.6302

  LogQ trial74 ep2 loss=8.5367

  LogQ trial74 ep3 loss=8.5133

  LogQ trial  74/180 lr=1e-03 dr=0.3 wd=0e+00 logq_w=1 -> val HR@50=0.89%

  LogQ trial75 ep1 loss=24.7611

  LogQ trial75 ep2 loss=24.3213

  LogQ trial75 ep3 loss=24.1347

  LogQ trial  75/180 lr=1e-03 dr=0.3 wd=0e+00 logq_w=10 -> val HR@50=0.07%

  LogQ trial76 ep1 loss=8.3193

  LogQ trial76 ep2 loss=8.2131

  LogQ trial76 ep3 loss=8.1379

  LogQ trial  76/180 lr=1e-03 dr=0.3 wd=1e-04 logq_w=0.1 -> val HR@50=0.46%

  LogQ trial77 ep1 loss=8.6133

  LogQ trial77 ep2 loss=8.5339

  LogQ trial77 ep3 loss=8.4852

  LogQ trial  77/180 lr=1e-03 dr=0.3 wd=1e-04 logq_w=1 -> val HR@50=1.28%

  LogQ trial78 ep1 loss=24.7580

  LogQ trial78 ep2 loss=24.3602

  LogQ trial78 ep3 loss=24.1849

  LogQ trial  78/180 lr=1e-03 dr=0.3 wd=1e-04 logq_w=10 -> val HR@50=0.10%

  LogQ trial79 ep1 loss=8.3223

  LogQ trial79 ep2 loss=8.3201

  LogQ trial79 ep3 loss=8.3198

  LogQ trial  79/180 lr=1e-03 dr=0.3 wd=1e-03 logq_w=0.1 -> val HR@50=3.75%

  LogQ trial80 ep1 loss=8.6139

  LogQ trial80 ep2 loss=8.5272

  LogQ trial80 ep3 loss=8.5049

  LogQ trial  80/180 lr=1e-03 dr=0.3 wd=1e-03 logq_w=1 -> val HR@50=0.49%

  LogQ trial81 ep1 loss=24.8216

  LogQ trial81 ep2 loss=24.4316

  LogQ trial81 ep3 loss=24.2730

  LogQ trial  81/180 lr=1e-03 dr=0.3 wd=1e-03 logq_w=10 -> val HR@50=0.00%

  LogQ trial82 ep1 loss=8.3251

  LogQ trial82 ep2 loss=8.3242

  LogQ trial82 ep3 loss=8.3188

  LogQ trial  82/180 lr=1e-03 dr=0.5 wd=0e+00 logq_w=0.1 -> val HR@50=1.63%

  LogQ trial83 ep1 loss=8.7533

  LogQ trial83 ep2 loss=8.6221

  LogQ trial83 ep3 loss=8.5846

  LogQ trial  83/180 lr=1e-03 dr=0.5 wd=0e+00 logq_w=1 -> val HR@50=1.07%

  LogQ trial84 ep1 loss=25.1366

  LogQ trial84 ep2 loss=24.6857

  LogQ trial84 ep3 loss=24.3654

  LogQ trial  84/180 lr=1e-03 dr=0.5 wd=0e+00 logq_w=10 -> val HR@50=0.10%

  LogQ trial85 ep1 loss=8.3247

  LogQ trial85 ep2 loss=8.3201

  LogQ trial85 ep3 loss=8.3026

  LogQ trial  85/180 lr=1e-03 dr=0.5 wd=1e-04 logq_w=0.1 -> val HR@50=1.70%

  LogQ trial86 ep1 loss=8.6919

  LogQ trial86 ep2 loss=8.5615

  LogQ trial86 ep3 loss=8.5287

  LogQ trial  86/180 lr=1e-03 dr=0.5 wd=1e-04 logq_w=1 -> val HR@50=1.25%

  LogQ trial87 ep1 loss=25.0852

  LogQ trial87 ep2 loss=24.6147

  LogQ trial87 ep3 loss=24.3433

  LogQ trial  87/180 lr=1e-03 dr=0.5 wd=1e-04 logq_w=10 -> val HR@50=0.08%

  LogQ trial88 ep1 loss=8.3250

  LogQ trial88 ep2 loss=8.3245

  LogQ trial88 ep3 loss=8.3245

  LogQ trial  88/180 lr=1e-03 dr=0.5 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial89 ep1 loss=8.6881

  LogQ trial89 ep2 loss=8.5896

  LogQ trial89 ep3 loss=8.5886

  LogQ trial  89/180 lr=1e-03 dr=0.5 wd=1e-03 logq_w=1 -> val HR@50=0.49%

  LogQ trial90 ep1 loss=25.1492

  LogQ trial90 ep2 loss=24.7452

  LogQ trial90 ep3 loss=24.4544

  LogQ trial  90/180 lr=1e-03 dr=0.5 wd=1e-03 logq_w=10 -> val HR@50=0.14%

  LogQ trial91 ep1 loss=8.1787

  LogQ trial91 ep2 loss=7.9172

  LogQ trial91 ep3 loss=7.8619

  LogQ trial  91/180 lr=3e-03 dr=0.0 wd=0e+00 logq_w=0.1 -> val HR@50=1.41%

  LogQ trial92 ep1 loss=8.4573

  LogQ trial92 ep2 loss=8.3673

  LogQ trial92 ep3 loss=8.3124

  LogQ trial  92/180 lr=3e-03 dr=0.0 wd=0e+00 logq_w=1 -> val HR@50=2.03%

  LogQ trial93 ep1 loss=24.0095

  LogQ trial93 ep2 loss=23.7229

  LogQ trial93 ep3 loss=23.7306

  LogQ trial  93/180 lr=3e-03 dr=0.0 wd=0e+00 logq_w=10 -> val HR@50=0.84%

  LogQ trial94 ep1 loss=8.1648

  LogQ trial94 ep2 loss=7.9380

  LogQ trial94 ep3 loss=7.8861

  LogQ trial  94/180 lr=3e-03 dr=0.0 wd=1e-04 logq_w=0.1 -> val HR@50=1.32%

  LogQ trial95 ep1 loss=8.4625

  LogQ trial95 ep2 loss=8.3820

  LogQ trial95 ep3 loss=8.3296

  LogQ trial  95/180 lr=3e-03 dr=0.0 wd=1e-04 logq_w=1 -> val HR@50=1.41%

  LogQ trial96 ep1 loss=24.0650

  LogQ trial96 ep2 loss=23.8295

  LogQ trial96 ep3 loss=23.8098

  LogQ trial  96/180 lr=3e-03 dr=0.0 wd=1e-04 logq_w=10 -> val HR@50=0.10%

  LogQ trial97 ep1 loss=8.3197

  LogQ trial97 ep2 loss=8.3211

  LogQ trial97 ep3 loss=8.3193

  LogQ trial  97/180 lr=3e-03 dr=0.0 wd=1e-03 logq_w=0.1 -> val HR@50=3.94%

  LogQ trial98 ep1 loss=8.4869

  LogQ trial98 ep2 loss=8.4342

  LogQ trial98 ep3 loss=8.4282

  LogQ trial  98/180 lr=3e-03 dr=0.0 wd=1e-03 logq_w=1 -> val HR@50=1.49%

  LogQ trial99 ep1 loss=24.3254

  LogQ trial99 ep2 loss=23.9569

  LogQ trial99 ep3 loss=23.8418

  LogQ trial  99/180 lr=3e-03 dr=0.0 wd=1e-03 logq_w=10 -> val HR@50=0.38%

  LogQ trial100 ep1 loss=8.2412

  LogQ trial100 ep2 loss=8.0572

  LogQ trial100 ep3 loss=7.9699

  LogQ trial 100/180 lr=3e-03 dr=0.1 wd=0e+00 logq_w=0.1 -> val HR@50=1.04%

  LogQ trial101 ep1 loss=8.4970

  LogQ trial101 ep2 loss=8.4399

  LogQ trial101 ep3 loss=8.4096

  LogQ trial 101/180 lr=3e-03 dr=0.1 wd=0e+00 logq_w=1 -> val HR@50=1.27%

  LogQ trial102 ep1 loss=24.2214

  LogQ trial102 ep2 loss=23.9238

  LogQ trial102 ep3 loss=23.9051

  LogQ trial 102/180 lr=3e-03 dr=0.1 wd=0e+00 logq_w=10 -> val HR@50=0.07%

  LogQ trial103 ep1 loss=8.2342

  LogQ trial103 ep2 loss=8.0771

  LogQ trial103 ep3 loss=8.0139

  LogQ trial 103/180 lr=3e-03 dr=0.1 wd=1e-04 logq_w=0.1 -> val HR@50=0.52%

  LogQ trial104 ep1 loss=8.4979

  LogQ trial104 ep2 loss=8.4460

  LogQ trial104 ep3 loss=8.4371

  LogQ trial 104/180 lr=3e-03 dr=0.1 wd=1e-04 logq_w=1 -> val HR@50=0.62%

  LogQ trial105 ep1 loss=24.3973

  LogQ trial105 ep2 loss=24.1244

  LogQ trial105 ep3 loss=24.0968

  LogQ trial 105/180 lr=3e-03 dr=0.1 wd=1e-04 logq_w=10 -> val HR@50=0.15%

  LogQ trial106 ep1 loss=8.3216

  LogQ trial106 ep2 loss=8.3204

  LogQ trial106 ep3 loss=8.3195

  LogQ trial 106/180 lr=3e-03 dr=0.1 wd=1e-03 logq_w=0.1 -> val HR@50=3.63%

  LogQ trial107 ep1 loss=8.5171

  LogQ trial107 ep2 loss=8.4684

  LogQ trial107 ep3 loss=8.4582

  LogQ trial 107/180 lr=3e-03 dr=0.1 wd=1e-03 logq_w=1 -> val HR@50=1.00%

  LogQ trial108 ep1 loss=24.4513

  LogQ trial108 ep2 loss=24.1384

  LogQ trial108 ep3 loss=23.9813

  LogQ trial 108/180 lr=3e-03 dr=0.1 wd=1e-03 logq_w=10 -> val HR@50=0.06%

  LogQ trial109 ep1 loss=8.2975

  LogQ trial109 ep2 loss=8.1349

  LogQ trial109 ep3 loss=8.0434

  LogQ trial 109/180 lr=3e-03 dr=0.2 wd=0e+00 logq_w=0.1 -> val HR@50=0.89%

  LogQ trial110 ep1 loss=8.5407

  LogQ trial110 ep2 loss=8.4628

  LogQ trial110 ep3 loss=8.4280

  LogQ trial 110/180 lr=3e-03 dr=0.2 wd=0e+00 logq_w=1 -> val HR@50=0.68%

  LogQ trial111 ep1 loss=24.4513

  LogQ trial111 ep2 loss=24.0721

  LogQ trial111 ep3 loss=23.9515

  LogQ trial 111/180 lr=3e-03 dr=0.2 wd=0e+00 logq_w=10 -> val HR@50=0.08%

  LogQ trial112 ep1 loss=8.2909

  LogQ trial112 ep2 loss=8.1432

  LogQ trial112 ep3 loss=8.0791

  LogQ trial 112/180 lr=3e-03 dr=0.2 wd=1e-04 logq_w=0.1 -> val HR@50=0.52%

  LogQ trial113 ep1 loss=8.5391

  LogQ trial113 ep2 loss=8.4668

  LogQ trial113 ep3 loss=8.4389

  LogQ trial 113/180 lr=3e-03 dr=0.2 wd=1e-04 logq_w=1 -> val HR@50=1.08%

  LogQ trial114 ep1 loss=24.5894

  LogQ trial114 ep2 loss=24.3208

  LogQ trial114 ep3 loss=24.2599

  LogQ trial 114/180 lr=3e-03 dr=0.2 wd=1e-04 logq_w=10 -> val HR@50=0.20%

  LogQ trial115 ep1 loss=8.3246

  LogQ trial115 ep2 loss=8.3245

  LogQ trial115 ep3 loss=8.3245

  LogQ trial 115/180 lr=3e-03 dr=0.2 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial116 ep1 loss=8.5605

  LogQ trial116 ep2 loss=8.4921

  LogQ trial116 ep3 loss=8.4789

  LogQ trial 116/180 lr=3e-03 dr=0.2 wd=1e-03 logq_w=1 -> val HR@50=2.37%

  LogQ trial117 ep1 loss=24.6067

  LogQ trial117 ep2 loss=24.1759

  LogQ trial117 ep3 loss=23.9672

  LogQ trial 117/180 lr=3e-03 dr=0.2 wd=1e-03 logq_w=10 -> val HR@50=0.15%

  LogQ trial118 ep1 loss=8.3158

  LogQ trial118 ep2 loss=8.1956

  LogQ trial118 ep3 loss=8.1147

  LogQ trial 118/180 lr=3e-03 dr=0.3 wd=0e+00 logq_w=0.1 -> val HR@50=0.54%

  LogQ trial119 ep1 loss=8.5909

  LogQ trial119 ep2 loss=8.4766

  LogQ trial119 ep3 loss=8.4396

  LogQ trial 119/180 lr=3e-03 dr=0.3 wd=0e+00 logq_w=1 -> val HR@50=0.83%

  LogQ trial120 ep1 loss=24.6210

  LogQ trial120 ep2 loss=24.1394

  LogQ trial120 ep3 loss=23.9393

  LogQ trial 120/180 lr=3e-03 dr=0.3 wd=0e+00 logq_w=10 -> val HR@50=0.10%

  LogQ trial121 ep1 loss=8.3167

  LogQ trial121 ep2 loss=8.1894

  LogQ trial121 ep3 loss=8.1173

  LogQ trial 121/180 lr=3e-03 dr=0.3 wd=1e-04 logq_w=0.1 -> val HR@50=0.34%

  LogQ trial122 ep1 loss=8.5831

  LogQ trial122 ep2 loss=8.4854

  LogQ trial122 ep3 loss=8.4504

  LogQ trial 122/180 lr=3e-03 dr=0.3 wd=1e-04 logq_w=1 -> val HR@50=0.54%

  LogQ trial123 ep1 loss=24.7407

  LogQ trial123 ep2 loss=24.4168

  LogQ trial123 ep3 loss=24.1984

  LogQ trial 123/180 lr=3e-03 dr=0.3 wd=1e-04 logq_w=10 -> val HR@50=0.23%

  LogQ trial124 ep1 loss=8.3247

  LogQ trial124 ep2 loss=8.3245

  LogQ trial124 ep3 loss=8.3245

  LogQ trial 124/180 lr=3e-03 dr=0.3 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial125 ep1 loss=8.6065

  LogQ trial125 ep2 loss=8.5537

  LogQ trial125 ep3 loss=8.5372

  LogQ trial 125/180 lr=3e-03 dr=0.3 wd=1e-03 logq_w=1 -> val HR@50=0.63%

  LogQ trial126 ep1 loss=24.7364

  LogQ trial126 ep2 loss=24.2874

  LogQ trial126 ep3 loss=24.0164

  LogQ trial 126/180 lr=3e-03 dr=0.3 wd=1e-03 logq_w=10 -> val HR@50=0.17%

  LogQ trial127 ep1 loss=8.3247

  LogQ trial127 ep2 loss=8.3163

  LogQ trial127 ep3 loss=8.2481

  LogQ trial 127/180 lr=3e-03 dr=0.5 wd=0e+00 logq_w=0.1 -> val HR@50=0.70%

  LogQ trial128 ep1 loss=8.6891

  LogQ trial128 ep2 loss=8.5449

  LogQ trial128 ep3 loss=8.4755

  LogQ trial 128/180 lr=3e-03 dr=0.5 wd=0e+00 logq_w=1 -> val HR@50=1.10%

  LogQ trial129 ep1 loss=24.9698

  LogQ trial129 ep2 loss=24.3230

  LogQ trial129 ep3 loss=24.0918

  LogQ trial 129/180 lr=3e-03 dr=0.5 wd=0e+00 logq_w=10 -> val HR@50=0.15%

  LogQ trial130 ep1 loss=8.3243

  LogQ trial130 ep2 loss=8.3200

  LogQ trial130 ep3 loss=8.3199

  LogQ trial 130/180 lr=3e-03 dr=0.5 wd=1e-04 logq_w=0.1 -> val HR@50=3.39%

  LogQ trial131 ep1 loss=8.6666

  LogQ trial131 ep2 loss=8.5328

  LogQ trial131 ep3 loss=8.4769

  LogQ trial 131/180 lr=3e-03 dr=0.5 wd=1e-04 logq_w=1 -> val HR@50=0.73%

  LogQ trial132 ep1 loss=24.9961

  LogQ trial132 ep2 loss=24.5535

  LogQ trial132 ep3 loss=24.3318

  LogQ trial 132/180 lr=3e-03 dr=0.5 wd=1e-04 logq_w=10 -> val HR@50=0.38%

  LogQ trial133 ep1 loss=8.3248

  LogQ trial133 ep2 loss=8.3245

  LogQ trial133 ep3 loss=8.3245

  LogQ trial 133/180 lr=3e-03 dr=0.5 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial134 ep1 loss=8.6847

  LogQ trial134 ep2 loss=8.5933

  LogQ trial134 ep3 loss=8.5734

  LogQ trial 134/180 lr=3e-03 dr=0.5 wd=1e-03 logq_w=1 -> val HR@50=1.24%

  LogQ trial135 ep1 loss=25.0856

  LogQ trial135 ep2 loss=24.4842

  LogQ trial135 ep3 loss=24.2177

  LogQ trial 135/180 lr=3e-03 dr=0.5 wd=1e-03 logq_w=10 -> val HR@50=0.06%

  LogQ trial136 ep1 loss=8.1605

  LogQ trial136 ep2 loss=7.9135

  LogQ trial136 ep3 loss=7.8619

  LogQ trial 136/180 lr=1e-02 dr=0.0 wd=0e+00 logq_w=0.1 -> val HR@50=1.75%

  LogQ trial137 ep1 loss=8.4484

  LogQ trial137 ep2 loss=8.3682

  LogQ trial137 ep3 loss=8.3148

  LogQ trial 137/180 lr=1e-02 dr=0.0 wd=0e+00 logq_w=1 -> val HR@50=1.83%

  LogQ trial138 ep1 loss=24.0154

  LogQ trial138 ep2 loss=23.7395

  LogQ trial138 ep3 loss=23.7358

  LogQ trial 138/180 lr=1e-02 dr=0.0 wd=0e+00 logq_w=10 -> val HR@50=0.15%

  LogQ trial139 ep1 loss=8.2066

  LogQ trial139 ep2 loss=8.0497

  LogQ trial139 ep3 loss=7.9980

  LogQ trial 139/180 lr=1e-02 dr=0.0 wd=1e-04 logq_w=0.1 -> val HR@50=0.45%

  LogQ trial140 ep1 loss=8.4665

  LogQ trial140 ep2 loss=8.4333

  LogQ trial140 ep3 loss=8.4269

  LogQ trial 140/180 lr=1e-02 dr=0.0 wd=1e-04 logq_w=1 -> val HR@50=1.37%

  LogQ trial141 ep1 loss=24.2208

  LogQ trial141 ep2 loss=23.9923

  LogQ trial141 ep3 loss=23.9534

  LogQ trial 141/180 lr=1e-02 dr=0.0 wd=1e-04 logq_w=10 -> val HR@50=0.24%

  LogQ trial142 ep1 loss=8.3210

  LogQ trial142 ep2 loss=8.3243

  LogQ trial142 ep3 loss=8.3245

  LogQ trial 142/180 lr=1e-02 dr=0.0 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial143 ep1 loss=8.5173

  LogQ trial143 ep2 loss=8.4604

  LogQ trial143 ep3 loss=8.4587

  LogQ trial 143/180 lr=1e-02 dr=0.0 wd=1e-03 logq_w=1 -> val HR@50=0.86%

  LogQ trial144 ep1 loss=24.4232

  LogQ trial144 ep2 loss=23.9619

  LogQ trial144 ep3 loss=23.9215

  LogQ trial 144/180 lr=1e-02 dr=0.0 wd=1e-03 logq_w=10 -> val HR@50=0.07%

  LogQ trial145 ep1 loss=8.2289

  LogQ trial145 ep2 loss=8.0382

  LogQ trial145 ep3 loss=7.9544

  LogQ trial 145/180 lr=1e-02 dr=0.1 wd=0e+00 logq_w=0.1 -> val HR@50=1.06%

  LogQ trial146 ep1 loss=8.4796

  LogQ trial146 ep2 loss=8.4305

  LogQ trial146 ep3 loss=8.4129

  LogQ trial 146/180 lr=1e-02 dr=0.1 wd=0e+00 logq_w=1 -> val HR@50=1.24%

  LogQ trial147 ep1 loss=24.2234

  LogQ trial147 ep2 loss=23.8875

  LogQ trial147 ep3 loss=23.8176

  LogQ trial 147/180 lr=1e-02 dr=0.1 wd=0e+00 logq_w=10 -> val HR@50=0.34%

  LogQ trial148 ep1 loss=8.3081

  LogQ trial148 ep2 loss=8.1435

  LogQ trial148 ep3 loss=8.1070

  LogQ trial 148/180 lr=1e-02 dr=0.1 wd=1e-04 logq_w=0.1 -> val HR@50=0.41%

  LogQ trial149 ep1 loss=8.4984

  LogQ trial149 ep2 loss=8.4502

  LogQ trial149 ep3 loss=8.4362

  LogQ trial 149/180 lr=1e-02 dr=0.1 wd=1e-04 logq_w=1 -> val HR@50=0.93%

  LogQ trial150 ep1 loss=24.4790

  LogQ trial150 ep2 loss=24.1113

  LogQ trial150 ep3 loss=24.0090

  LogQ trial 150/180 lr=1e-02 dr=0.1 wd=1e-04 logq_w=10 -> val HR@50=0.25%

  LogQ trial151 ep1 loss=8.3246

  LogQ trial151 ep2 loss=8.3245

  LogQ trial151 ep3 loss=8.3245

  LogQ trial 151/180 lr=1e-02 dr=0.1 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial152 ep1 loss=8.5353

  LogQ trial152 ep2 loss=8.4677

  LogQ trial152 ep3 loss=8.4551

  LogQ trial 152/180 lr=1e-02 dr=0.1 wd=1e-03 logq_w=1 -> val HR@50=1.06%

  LogQ trial153 ep1 loss=24.5025

  LogQ trial153 ep2 loss=24.0441

  LogQ trial153 ep3 loss=23.9257

  LogQ trial 153/180 lr=1e-02 dr=0.1 wd=1e-03 logq_w=10 -> val HR@50=0.24%

  LogQ trial154 ep1 loss=8.2803

  LogQ trial154 ep2 loss=8.1268

  LogQ trial154 ep3 loss=8.0528

  LogQ trial 154/180 lr=1e-02 dr=0.2 wd=0e+00 logq_w=0.1 -> val HR@50=0.87%

  LogQ trial155 ep1 loss=8.5052

  LogQ trial155 ep2 loss=8.4306

  LogQ trial155 ep3 loss=8.4268

  LogQ trial 155/180 lr=1e-02 dr=0.2 wd=0e+00 logq_w=1 -> val HR@50=1.20%

  LogQ trial156 ep1 loss=24.3698

  LogQ trial156 ep2 loss=23.9235

  LogQ trial156 ep3 loss=23.8682

  LogQ trial 156/180 lr=1e-02 dr=0.2 wd=0e+00 logq_w=10 -> val HR@50=0.06%

  LogQ trial157 ep1 loss=8.3220

  LogQ trial157 ep2 loss=8.3197

  LogQ trial157 ep3 loss=8.3193

  LogQ trial 157/180 lr=1e-02 dr=0.2 wd=1e-04 logq_w=0.1 -> val HR@50=3.97%

  LogQ trial158 ep1 loss=8.5214

  LogQ trial158 ep2 loss=8.4629

  LogQ trial158 ep3 loss=8.4589

  LogQ trial 158/180 lr=1e-02 dr=0.2 wd=1e-04 logq_w=1 -> val HR@50=1.72%

  LogQ trial159 ep1 loss=24.6210

  LogQ trial159 ep2 loss=24.1542

  LogQ trial159 ep3 loss=24.1019

  LogQ trial 159/180 lr=1e-02 dr=0.2 wd=1e-04 logq_w=10 -> val HR@50=0.13%

  LogQ trial160 ep1 loss=8.3246

  LogQ trial160 ep2 loss=8.3245

  LogQ trial160 ep3 loss=8.3245

  LogQ trial 160/180 lr=1e-02 dr=0.2 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial161 ep1 loss=8.5627

  LogQ trial161 ep2 loss=8.4819

  LogQ trial161 ep3 loss=8.4751

  LogQ trial 161/180 lr=1e-02 dr=0.2 wd=1e-03 logq_w=1 -> val HR@50=1.55%

  LogQ trial162 ep1 loss=24.6944

  LogQ trial162 ep2 loss=24.1572

  LogQ trial162 ep3 loss=24.0722

  LogQ trial 162/180 lr=1e-02 dr=0.2 wd=1e-03 logq_w=10 -> val HR@50=0.39%

  LogQ trial163 ep1 loss=8.3012

  LogQ trial163 ep2 loss=8.1600

  LogQ trial163 ep3 loss=8.0949

  LogQ trial 163/180 lr=1e-02 dr=0.3 wd=0e+00 logq_w=0.1 -> val HR@50=0.39%

  LogQ trial164 ep1 loss=8.5353

  LogQ trial164 ep2 loss=8.4405

  LogQ trial164 ep3 loss=8.4360

  LogQ trial 164/180 lr=1e-02 dr=0.3 wd=0e+00 logq_w=1 -> val HR@50=1.00%

  LogQ trial165 ep1 loss=24.4649

  LogQ trial165 ep2 loss=23.9502

  LogQ trial165 ep3 loss=23.9473

  LogQ trial 165/180 lr=1e-02 dr=0.3 wd=0e+00 logq_w=10 -> val HR@50=0.14%

  LogQ trial166 ep1 loss=8.3246

  LogQ trial166 ep2 loss=8.3245

  LogQ trial166 ep3 loss=8.3245

  LogQ trial 166/180 lr=1e-02 dr=0.3 wd=1e-04 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial167 ep1 loss=8.5550

  LogQ trial167 ep2 loss=8.4893

  LogQ trial167 ep3 loss=8.4840

  LogQ trial 167/180 lr=1e-02 dr=0.3 wd=1e-04 logq_w=1 -> val HR@50=1.14%

  LogQ trial168 ep1 loss=24.6253

  LogQ trial168 ep2 loss=24.1213

  LogQ trial168 ep3 loss=24.1214

  LogQ trial 168/180 lr=1e-02 dr=0.3 wd=1e-04 logq_w=10 -> val HR@50=0.35%

  LogQ trial169 ep1 loss=8.3246

  LogQ trial169 ep2 loss=8.3245

  LogQ trial169 ep3 loss=8.3245

  LogQ trial 169/180 lr=1e-02 dr=0.3 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial170 ep1 loss=8.5890

  LogQ trial170 ep2 loss=8.4964

  LogQ trial170 ep3 loss=8.4757

  LogQ trial 170/180 lr=1e-02 dr=0.3 wd=1e-03 logq_w=1 -> val HR@50=1.03%

  LogQ trial171 ep1 loss=24.7481

  LogQ trial171 ep2 loss=24.1662

  LogQ trial171 ep3 loss=24.0838

  LogQ trial 171/180 lr=1e-02 dr=0.3 wd=1e-03 logq_w=10 -> val HR@50=0.23%

  LogQ trial172 ep1 loss=8.3237

  LogQ trial172 ep2 loss=8.3050

  LogQ trial172 ep3 loss=8.2311

  LogQ trial 172/180 lr=1e-02 dr=0.5 wd=0e+00 logq_w=0.1 -> val HR@50=0.28%

  LogQ trial173 ep1 loss=8.6135

  LogQ trial173 ep2 loss=8.4744

  LogQ trial173 ep3 loss=8.4627

  LogQ trial 173/180 lr=1e-02 dr=0.5 wd=0e+00 logq_w=1 -> val HR@50=1.39%

  LogQ trial174 ep1 loss=24.6946

  LogQ trial174 ep2 loss=24.0889

  LogQ trial174 ep3 loss=24.0754

  LogQ trial 174/180 lr=1e-02 dr=0.5 wd=0e+00 logq_w=10 -> val HR@50=0.03%

  LogQ trial175 ep1 loss=8.3247

  LogQ trial175 ep2 loss=8.3245

  LogQ trial175 ep3 loss=8.3245

  LogQ trial 175/180 lr=1e-02 dr=0.5 wd=1e-04 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial176 ep1 loss=8.6286

  LogQ trial176 ep2 loss=8.5292

  LogQ trial176 ep3 loss=8.5189

  LogQ trial 176/180 lr=1e-02 dr=0.5 wd=1e-04 logq_w=1 -> val HR@50=0.79%

  LogQ trial177 ep1 loss=24.8827

  LogQ trial177 ep2 loss=24.3441

  LogQ trial177 ep3 loss=24.2662

  LogQ trial 177/180 lr=1e-02 dr=0.5 wd=1e-04 logq_w=10 -> val HR@50=0.32%

  LogQ trial178 ep1 loss=8.3248

  LogQ trial178 ep2 loss=8.3246

  LogQ trial178 ep3 loss=8.3246

  LogQ trial 178/180 lr=1e-02 dr=0.5 wd=1e-03 logq_w=0.1 -> val HR@50=0.00%

  LogQ trial179 ep1 loss=8.8952

  LogQ trial179 ep2 loss=8.8951

  LogQ trial179 ep3 loss=8.8949

  LogQ trial 179/180 lr=1e-02 dr=0.5 wd=1e-03 logq_w=1 -> val HR@50=0.00%

  LogQ trial180 ep1 loss=24.9696

  LogQ trial180 ep2 loss=24.3616

  LogQ trial180 ep3 loss=24.2942

  LogQ trial 180/180 lr=1e-02 dr=0.5 wd=1e-03 logq_w=10 -> val HR@50=0.18%

Best LogQ val HR@50=3.97% -> {'lr': 0.01, 'dropout': 0.2, 'weight_decay': 0.0001, 'logq_weight': 0.1, 'val_HR@50': 3.970712475359054}
Saved best hparams: best_hparams_yambda_logq.json
Saved leaderboard CSV: best_hparams_yambda_logq.leaderboard.csv

,trial,status,error,method,lr,dropout,weight_decay,logq_weight,tune_epochs,val_subset_size,...,val_TailRatio@10,val_Personalization@10,val_CatalogCoverage@50,val_TailCoverage@50,val_AvgPopularity@50,val_TailRatio@50,val_Personalization@50,val_count_overall,val_count_head,val_count_tail
156,157,ok,,LogQ,0.0100,0.2,0.0001,0.1,3,7102,...,0.000000,15.707139,0.365063,0.000000,5.917221,0.000000,9.335662,7102,3978,3124
96,97,ok,,LogQ,0.0030,0.0,0.0010,0.1,3,7102,...,0.000000,15.878230,0.352994,0.000000,5.920173,0.000000,9.348646,7102,3978,3124
78,79,ok,,LogQ,0.0010,0.3,0.0010,0.1,3,7102,...,0.000000,15.612997,0.362046,0.000000,5.917633,0.000000,9.311634,7102,3978,3124
105,106,ok,,LogQ,0.0030,0.1,0.0010,0.1,3,7102,...,0.000000,15.863663,0.359029,0.000000,5.895668,0.000000,9.200360,7102,3978,3124
21,22,ok,,LogQ,0.0001,0.2,0.0001,0.1,3,7102,...,0.004224,54.062251,2.591643,0.203651,5.638162,0.088144,47.746388,7102,3978,3124
33,34,ok,,LogQ,0.0001,0.3,0.0010,0.1,3,7102,...,0.000000,19.407906,0.356011,0.003771,5.764207,0.007885,15.160962,7102,3978,3124
129,130,ok,,LogQ,0.0030,0.5,0.0001,0.1,3,7102,...,0.039426,15.180919,0.310756,0.030170,5.594218,2.174035,8.277951,7102,3978,3124
18,19,ok,,LogQ,0.0001,0.2,0.0000,0.1,3,7102,...,0.004224,35.129135,1.650324,0.369588,5.591823,0.877499,34.187617,7102,3978,3124
30,31,ok,,LogQ,0.0001,0.3,0.0001,0.1,3,7102,...,0.019713,16.192404,0.340926,0.018857,5.448222,4.181921,13.969012,7102,3978,3124
52,53,ok,,LogQ,0.0010,0.0,0.0010,1.0,3,7102,...,0.000000,10.848883,0.325841,0.000000,5.695574,0.000000,8.280631,7102,3978,3124

## 10. Final training over seeds + head/tail sweep

In [13]:

HEAD_FRACTIONS = [0.001, 0.005, 0.01, 0.05, 0.20]

all_rows = []
all_test = []
all_sweep_rows = []

print("Using best_hp:", best_hp)

for seed in CFG["seeds"]:
    print("\n" + "=" * 80)
    print(f"LogQ seed {seed}")
    print("=" * 80)

    set_seed(seed)

    model = TwoTower(
        NUM_USERS, NUM_ITEMS, NUM_ARTISTS, NUM_ALBUMS,
        embed_dim=CFG["embed_dim"],
        artist_emb_dim=CFG["artist_emb_dim"],
        album_emb_dim=CFG["album_emb_dim"],
        hidden=CFG["tower_hidden"],
        dropout=best_hp["dropout"],
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=best_hp["lr"], weight_decay=best_hp["weight_decay"])

    best_val_hr50 = -1.0
    best_state = None

    for epoch in range(1, CFG["final_epochs"] + 1):
        model.train()
        total_loss, total_n = 0.0, 0
        pbar = tqdm(train_loader, desc=f"LogQ seed {seed} train {epoch}/{CFG['final_epochs']}", leave=False)

        for users_batch, items_batch in pbar:
            users_batch = users_batch.to(device, non_blocking=True)
            items_batch = items_batch.to(device, non_blocking=True)

            user_vecs = model.user_vec(users_batch)
            item_vecs = model.item_vec(items_batch)

            loss = logq_inbatch_softmax_loss(user_vecs, item_vecs, items_batch, logq_t, best_hp["logq_weight"])

            if not torch.isfinite(loss):
                raise RuntimeError(f"Non-finite loss at seed={seed}, epoch={epoch}: {loss.item()}")

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), CFG["grad_clip"])
            optimizer.step()

            bs = users_batch.size(0)
            total_loss += loss.item() * bs
            total_n += bs
            pbar.set_postfix(loss=f"{loss.item():.4f}")

        avg_loss = total_loss / max(total_n, 1)
        print(f"seed {seed} epoch {epoch}: train loss = {avg_loss:.4f}")

        val_metrics = evaluate_full_corpus(
            model=model,
            users=val_u,
            true_items=val_i,
            known_user_items=known_val,
            head_mask=head_mask,
            ks=CFG["eval_k"],
            item_freq=item_freq,
            user_batch_size=CFG["eval_batch_users"],
            item_batch_size=CFG["eval_item_batch"],
        )

        hr50 = val_metrics["overall"].get("HR@50", -1.0)
        if hr50 > best_val_hr50:
            best_val_hr50 = hr50
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            print(f"new best val HR@50 = {best_val_hr50:.4f}")

    assert best_state is not None
    model.load_state_dict(best_state)
    model.to(device)
    model.eval()

    test_metrics = evaluate_full_corpus(
        model=model,
        users=test_u,
        true_items=test_i,
        known_user_items=known_test,
        head_mask=head_mask,
        ks=CFG["eval_k"],
        item_freq=item_freq,
        user_batch_size=CFG["eval_batch_users"],
        item_batch_size=CFG["eval_item_batch"],
    )

    print("TEST METRICS")
    print_metrics(test_metrics)
    all_test.append(test_metrics)

    row = {
        "method": "LogQ",
        "seed": seed,
        "lr": best_hp["lr"],
        "dropout": best_hp["dropout"],
        "weight_decay": best_hp["weight_decay"],
        "logq_weight": best_hp["logq_weight"],
        "best_val_HR@50": best_val_hr50,
    }
    for split in ("overall", "head", "tail"):
        for key, value in test_metrics[split].items():
            row[f"test_{split}_{key}"] = value
    if "long_tail" in test_metrics:
        for key, value in test_metrics["long_tail"].items():
            row[f"test_{key}"] = value
    if "counts" in test_metrics:
        for key, value in test_metrics["counts"].items():
            row[f"test_count_{key}"] = value
    all_rows.append(row)

    sweep_rows_seed = evaluate_head_tail_sweep(
        model=model,
        method_name="LogQ",
        seed=seed,
        head_fractions=HEAD_FRACTIONS,
        test_u=test_u,
        test_i=test_i,
        known_test=known_test,
        item_freq=item_freq,
        ks=CFG["eval_k"],
    )
    all_sweep_rows.extend(sweep_rows_seed)

    del model
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

metrics_df = pd.DataFrame(all_rows)
sweep_df = pd.DataFrame(all_sweep_rows)
metrics_df

Using best_hp: {'lr': 0.01, 'dropout': 0.2, 'weight_decay': 0.0001, 'logq_weight': 0.1, 'val_HR@50': 3.970712475359054}

================================================================================
LogQ seed 0
================================================================================

seed 0 epoch 1: train loss = 8.3220

new best val HR@50 = 3.0836

seed 0 epoch 2: train loss = 8.3197

new best val HR@50 = 3.6469

seed 0 epoch 3: train loss = 8.3193

new best val HR@50 = 3.9707

seed 0 epoch 4: train loss = 8.3195

seed 0 epoch 5: train loss = 8.3193

new best val HR@50 = 3.9848

seed 0 epoch 6: train loss = 8.3193

new best val HR@50 = 4.0974

seed 0 epoch 7: train loss = 8.3193

new best val HR@50 = 4.1538

seed 0 epoch 8: train loss = 8.3192

seed 0 epoch 9: train loss = 8.3193

seed 0 epoch 10: train loss = 8.3192

seed 0 epoch 11: train loss = 8.3192

seed 0 epoch 12: train loss = 8.3193

seed 0 epoch 13: train loss = 8.3199

seed 0 epoch 14: train loss = 8.3194

seed 0 epoch 15: train loss = 8.3193

seed 0 epoch 16: train loss = 8.3194

seed 0 epoch 17: train loss = 8.3193

seed 0 epoch 18: train loss = 8.3196

seed 0 epoch 19: train loss = 8.3198

seed 0 epoch 20: train loss = 8.3198

TEST METRICS
counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.239087580963109, 'NDCG@10': 0.6422733342246604, 'HR@50': 3.534215713883413, 'NDCG@50': 1.1451338132968507}
[head] {'HR@10': 2.3133543638275498, 'NDCG@10': 1.1991128337706463, 'HR@50': 6.598317560462672, 'NDCG@50': 2.137944359104688}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12068185246643535, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460615339643753, 'TailRatio@10': 0.0, 'Personalization@10': 16.111732748839213, 'CatalogCoverage@50': 0.36506260371096694, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.935894098168618, 'TailRatio@50': 0.0, 'Personalization@50': 9.498883134129665}

================================================================================
LogQ | seed=0 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0273
test_tail_share: 0.9727

counts: {'overall': 7102, 'head': 194, 'tail': 6908}
[overall] {'HR@10': 1.239087580963109, 'NDCG@10': 0.6422733342246604, 'HR@50': 3.534215713883413, 'NDCG@50': 1.1451338132968507}
[head] {'HR@10': 45.36082474226804, 'NDCG@10': 23.512501132286282, 'HR@50': 100.0, 'NDCG@50': 36.2383956464045}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.8251302837290099, 'NDCG@50': 0.1595963501204057}
[long_tail] {'CatalogCoverage@10': 0.12068185246643535, 'TailCoverage@10': 0.0362406378352259, 'AvgPopularity@10': 6.460615339643753, 'TailRatio@10': 0.12954097437341594, 'Personalization@10': 16.111732748839213, 'CatalogCoverage@50': 0.36506260371096694, 'TailCoverage@50': 0.2657646774583233, 'AvgPopularity@50': 5.935894098168618, 'TailRatio@50': 38.4770487186708, 'Personalization@50': 9.498883134129665}

================================================================================
LogQ | seed=0 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0639
test_tail_share: 0.9361

counts: {'overall': 7102, 'head': 454, 'tail': 6648}
[overall] {'HR@10': 1.239087580963109, 'NDCG@10': 0.6422733342246604, 'HR@50': 3.534215713883413, 'NDCG@50': 1.1451338132968507}
[head] {'HR@10': 19.383259911894275, 'NDCG@10': 10.04719211379634, 'HR@50': 55.2863436123348, 'NDCG@50': 17.91352498245426}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12068185246643535, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460615339643753, 'TailRatio@10': 0.0, 'Personalization@10': 16.111732748839213, 'CatalogCoverage@50': 0.36506260371096694, 'TailCoverage@50': 0.015160703456640388, 'AvgPopularity@50': 5.935894098168618, 'TailRatio@50': 0.0047873838355392846, 'Personalization@50': 9.498883134129665}

================================================================================
LogQ | seed=0 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1036
test_tail_share: 0.8964

counts: {'overall': 7102, 'head': 736, 'tail': 6366}
[overall] {'HR@10': 1.239087580963109, 'NDCG@10': 0.6422733342246604, 'HR@50': 3.534215713883413, 'NDCG@50': 1.1451338132968507}
[head] {'HR@10': 11.956521739130435, 'NDCG@10': 6.197588613673286, 'HR@50': 34.10326086956522, 'NDCG@50': 11.049918942981298}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12068185246643535, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460615339643753, 'TailRatio@10': 0.0, 'Personalization@10': 16.111732748839213, 'CatalogCoverage@50': 0.36506260371096694, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.935894098168618, 'TailRatio@50': 0.0, 'Personalization@50': 9.498883134129665}

================================================================================
LogQ | seed=0 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2853
test_tail_share: 0.7147

counts: {'overall': 7102, 'head': 2026, 'tail': 5076}
[overall] {'HR@10': 1.239087580963109, 'NDCG@10': 0.6422733342246604, 'HR@50': 3.534215713883413, 'NDCG@50': 1.1451338132968507}
[head] {'HR@10': 4.343534057255676, 'NDCG@10': 2.2514438399129015, 'HR@50': 12.388943731490622, 'NDCG@50': 4.01418575618669}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12068185246643535, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460615339643753, 'TailRatio@10': 0.0, 'Personalization@10': 16.111732748839213, 'CatalogCoverage@50': 0.36506260371096694, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.935894098168618, 'TailRatio@50': 0.0, 'Personalization@50': 9.498883134129665}

================================================================================
LogQ | seed=0 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5356
test_tail_share: 0.4644

counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.239087580963109, 'NDCG@10': 0.6422733342246604, 'HR@50': 3.534215713883413, 'NDCG@50': 1.1451338132968507}
[head] {'HR@10': 2.3133543638275498, 'NDCG@10': 1.1991128337706463, 'HR@50': 6.598317560462672, 'NDCG@50': 2.137944359104688}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12068185246643535, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460615339643753, 'TailRatio@10': 0.0, 'Personalization@10': 16.111732748839213, 'CatalogCoverage@50': 0.36506260371096694, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.935894098168618, 'TailRatio@50': 0.0, 'Personalization@50': 9.498883134129665}

================================================================================
LogQ seed 1
================================================================================

seed 1 epoch 1: train loss = 8.3217

new best val HR@50 = 3.8017

seed 1 epoch 2: train loss = 8.3198

seed 1 epoch 3: train loss = 8.3195

seed 1 epoch 4: train loss = 8.3194

new best val HR@50 = 3.8299

seed 1 epoch 5: train loss = 8.3193

new best val HR@50 = 3.9144

seed 1 epoch 6: train loss = 8.3193

seed 1 epoch 7: train loss = 8.3192

new best val HR@50 = 3.9285

seed 1 epoch 8: train loss = 8.3193

new best val HR@50 = 4.0834

seed 1 epoch 9: train loss = 8.3193

seed 1 epoch 10: train loss = 8.3195

seed 1 epoch 11: train loss = 8.3193

seed 1 epoch 12: train loss = 8.3194

seed 1 epoch 13: train loss = 8.3194

seed 1 epoch 14: train loss = 8.3198

seed 1 epoch 15: train loss = 8.3196

seed 1 epoch 16: train loss = 8.3192

new best val HR@50 = 4.1256

seed 1 epoch 17: train loss = 8.3194

seed 1 epoch 18: train loss = 8.3192

seed 1 epoch 19: train loss = 8.3194

seed 1 epoch 20: train loss = 8.3193

TEST METRICS
counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.3376513658124471, 'NDCG@10': 0.6326724633655855, 'HR@50': 3.604618417347226, 'NDCG@50': 1.1244313384351474}
[head] {'HR@10': 2.4973711882229233, 'NDCG@10': 1.1811881795011536, 'HR@50': 6.729758149316509, 'NDCG@50': 2.099293208613674}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12369889877809623, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460302009501315, 'TailRatio@10': 0.0, 'Personalization@10': 16.008336647743103, 'CatalogCoverage@50': 0.35299441846432345, 'TailCoverage@50': 0.00754261577915221, 'AvgPopularity@50': 5.931932272390387, 'TailRatio@50': 0.010419600112644326, 'Personalization@50': 9.471083256981938}

================================================================================
LogQ | seed=1 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0273
test_tail_share: 0.9727

counts: {'overall': 7102, 'head': 194, 'tail': 6908}
[overall] {'HR@10': 1.3376513658124471, 'NDCG@10': 0.6326724633655855, 'HR@50': 3.604618417347226, 'NDCG@50': 1.1244313384351474}
[head] {'HR@10': 48.96907216494845, 'NDCG@10': 23.161030076404067, 'HR@50': 100.0, 'NDCG@50': 35.093982101270285}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.897510133178923, 'NDCG@50': 0.17045148203821406}
[long_tail] {'CatalogCoverage@10': 0.12369889877809623, 'TailCoverage@10': 0.030200531529354917, 'AvgPopularity@10': 6.460302009501315, 'TailRatio@10': 0.043649676147564063, 'Personalization@10': 16.008336647743103, 'CatalogCoverage@50': 0.35299441846432345, 'TailCoverage@50': 0.2536844648465813, 'AvgPopularity@50': 5.931932272390387, 'TailRatio@50': 38.4770487186708, 'Personalization@50': 9.471083256981938}

================================================================================
LogQ | seed=1 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0639
test_tail_share: 0.9361

counts: {'overall': 7102, 'head': 454, 'tail': 6648}
[overall] {'HR@10': 1.3376513658124471, 'NDCG@10': 0.6326724633655855, 'HR@50': 3.604618417347226, 'NDCG@50': 1.1244313384351474}
[head] {'HR@10': 20.92511013215859, 'NDCG@10': 9.897004041459004, 'HR@50': 56.38766519823789, 'NDCG@50': 17.589672611379775}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12369889877809623, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460302009501315, 'TailRatio@10': 0.0, 'Personalization@10': 16.008336647743103, 'CatalogCoverage@50': 0.35299441846432345, 'TailCoverage@50': 0.02425712553062462, 'AvgPopularity@50': 5.931932272390387, 'TailRatio@50': 0.013517319065052099, 'Personalization@50': 9.471083256981938}

================================================================================
LogQ | seed=1 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1036
test_tail_share: 0.8964

counts: {'overall': 7102, 'head': 736, 'tail': 6366}
[overall] {'HR@10': 1.3376513658124471, 'NDCG@10': 0.6326724633655855, 'HR@50': 3.604618417347226, 'NDCG@50': 1.1244313384351474}
[head] {'HR@10': 12.907608695652172, 'NDCG@10': 6.10494542774781, 'HR@50': 34.78260869565217, 'NDCG@50': 10.850151311910894}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12369889877809623, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460302009501315, 'TailRatio@10': 0.0, 'Personalization@10': 16.008336647743103, 'CatalogCoverage@50': 0.35299441846432345, 'TailCoverage@50': 0.012189918937039069, 'AvgPopularity@50': 5.931932272390387, 'TailRatio@50': 0.011264432554210082, 'Personalization@50': 9.471083256981938}

================================================================================
LogQ | seed=1 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2853
test_tail_share: 0.7147

counts: {'overall': 7102, 'head': 2026, 'tail': 5076}
[overall] {'HR@10': 1.3376513658124471, 'NDCG@10': 0.6326724633655855, 'HR@50': 3.604618417347226, 'NDCG@50': 1.1244313384351474}
[head] {'HR@10': 4.689042448173741, 'NDCG@10': 2.2177886647691945, 'HR@50': 12.635735439289238, 'NDCG@50': 3.9416146917899386}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12369889877809623, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460302009501315, 'TailRatio@10': 0.0, 'Personalization@10': 16.008336647743103, 'CatalogCoverage@50': 0.35299441846432345, 'TailCoverage@50': 0.009527439024390244, 'AvgPopularity@50': 5.931932272390387, 'TailRatio@50': 0.01098282174035483, 'Personalization@50': 9.471083256981938}

================================================================================
LogQ | seed=1 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5356
test_tail_share: 0.4644

counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.3376513658124471, 'NDCG@10': 0.6326724633655855, 'HR@50': 3.604618417347226, 'NDCG@50': 1.1244313384351474}
[head] {'HR@10': 2.4973711882229233, 'NDCG@10': 1.1811881795011536, 'HR@50': 6.729758149316509, 'NDCG@50': 2.099293208613674}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12369889877809623, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.460302009501315, 'TailRatio@10': 0.0, 'Personalization@10': 16.008336647743103, 'CatalogCoverage@50': 0.35299441846432345, 'TailCoverage@50': 0.00754261577915221, 'AvgPopularity@50': 5.931932272390387, 'TailRatio@50': 0.010419600112644326, 'Personalization@50': 9.471083256981938}

================================================================================
LogQ seed 2
================================================================================

seed 2 epoch 1: train loss = 8.3214

new best val HR@50 = 3.9566

seed 2 epoch 2: train loss = 8.3194

seed 2 epoch 3: train loss = 8.3194

seed 2 epoch 4: train loss = 8.3194

seed 2 epoch 5: train loss = 8.3192

new best val HR@50 = 4.2523

seed 2 epoch 6: train loss = 8.3191

seed 2 epoch 7: train loss = 8.3191

seed 2 epoch 8: train loss = 8.3191

seed 2 epoch 9: train loss = 8.3192

seed 2 epoch 10: train loss = 8.3193

seed 2 epoch 11: train loss = 8.3192

seed 2 epoch 12: train loss = 8.3193

seed 2 epoch 13: train loss = 8.3193

seed 2 epoch 14: train loss = 8.3192

seed 2 epoch 15: train loss = 8.3193

seed 2 epoch 16: train loss = 8.3193

seed 2 epoch 17: train loss = 8.3192

seed 2 epoch 18: train loss = 8.3195

seed 2 epoch 19: train loss = 8.3195

seed 2 epoch 20: train loss = 8.3193

TEST METRICS
counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.281329203041397, 'NDCG@10': 0.6508218532747071, 'HR@50': 3.491974091805125, 'NDCG@50': 1.1297294127841724}
[head] {'HR@10': 2.392218717139853, 'NDCG@10': 1.2150727660244398, 'HR@50': 6.5194532071503675, 'NDCG@50': 2.10918461871535}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.457457879370875, 'TailRatio@10': 0.0, 'Personalization@10': 16.061331908503963, 'CatalogCoverage@50': 0.34997737215266256, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.925947297937605, 'TailRatio@50': 0.0, 'Personalization@50': 9.496761435982759}

================================================================================
LogQ | seed=2 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0273
test_tail_share: 0.9727

counts: {'overall': 7102, 'head': 194, 'tail': 6908}
[overall] {'HR@10': 1.281329203041397, 'NDCG@10': 0.6508218532747071, 'HR@50': 3.491974091805125, 'NDCG@50': 1.1297294127841724}
[head] {'HR@10': 46.90721649484536, 'NDCG@10': 23.825447432767884, 'HR@50': 100.0, 'NDCG@50': 35.85988588515776}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.781702374059062, 'NDCG@50': 0.1543891760093494}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0362406378352259, 'AvgPopularity@10': 6.457457879370875, 'TailRatio@10': 0.19008729935229512, 'Personalization@10': 16.061331908503963, 'CatalogCoverage@50': 0.34997737215266256, 'TailCoverage@50': 0.2506644116936458, 'AvgPopularity@50': 5.925947297937605, 'TailRatio@50': 38.4770487186708, 'Personalization@50': 9.496761435982759}

================================================================================
LogQ | seed=2 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0639
test_tail_share: 0.9361

counts: {'overall': 7102, 'head': 454, 'tail': 6648}
[overall] {'HR@10': 1.281329203041397, 'NDCG@10': 0.6508218532747071, 'HR@50': 3.491974091805125, 'NDCG@50': 1.1297294127841724}
[head] {'HR@10': 20.044052863436125, 'NDCG@10': 10.180918065984516, 'HR@50': 54.62555066079295, 'NDCG@50': 17.672551298663418}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.457457879370875, 'TailRatio@10': 0.0, 'Personalization@10': 16.061331908503963, 'CatalogCoverage@50': 0.34997737215266256, 'TailCoverage@50': 0.02425712553062462, 'AvgPopularity@50': 5.925947297937605, 'TailRatio@50': 0.11179949310053507, 'Personalization@50': 9.496761435982759}

================================================================================
LogQ | seed=2 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1036
test_tail_share: 0.8964

counts: {'overall': 7102, 'head': 736, 'tail': 6366}
[overall] {'HR@10': 1.281329203041397, 'NDCG@10': 0.6508218532747071, 'HR@50': 3.491974091805125, 'NDCG@50': 1.1297294127841724}
[head] {'HR@10': 12.364130434782608, 'NDCG@10': 6.28007717657197, 'HR@50': 33.69565217391305, 'NDCG@50': 10.90127484999075}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.457457879370875, 'TailRatio@10': 0.0, 'Personalization@10': 16.061331908503963, 'CatalogCoverage@50': 0.34997737215266256, 'TailCoverage@50': 0.003047479734259767, 'AvgPopularity@50': 5.925947297937605, 'TailRatio@50': 0.0014080540692762602, 'Personalization@50': 9.496761435982759}

================================================================================
LogQ | seed=2 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2853
test_tail_share: 0.7147

counts: {'overall': 7102, 'head': 2026, 'tail': 5076}
[overall] {'HR@10': 1.281329203041397, 'NDCG@10': 0.6508218532747071, 'HR@50': 3.491974091805125, 'NDCG@50': 1.1297294127841724}
[head] {'HR@10': 4.491609081934847, 'NDCG@10': 2.281410070067606, 'HR@50': 12.240868706811451, 'NDCG@50': 3.960186717469493}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.457457879370875, 'TailRatio@10': 0.0, 'Personalization@10': 16.061331908503963, 'CatalogCoverage@50': 0.34997737215266256, 'TailCoverage@50': 0.0031758130081300817, 'AvgPopularity@50': 5.925947297937605, 'TailRatio@50': 0.0014080540692762602, 'Personalization@50': 9.496761435982759}

================================================================================
LogQ | seed=2 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5356
test_tail_share: 0.4644

counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.281329203041397, 'NDCG@10': 0.6508218532747071, 'HR@50': 3.491974091805125, 'NDCG@50': 1.1297294127841724}
[head] {'HR@10': 2.392218717139853, 'NDCG@10': 1.2150727660244398, 'HR@50': 6.5194532071503675, 'NDCG@50': 2.10918461871535}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.457457879370875, 'TailRatio@10': 0.0, 'Personalization@10': 16.061331908503963, 'CatalogCoverage@50': 0.34997737215266256, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.925947297937605, 'TailRatio@50': 0.0, 'Personalization@50': 9.496761435982759}

================================================================================
LogQ seed 3
================================================================================

seed 3 epoch 1: train loss = 8.3212

new best val HR@50 = 3.4920

seed 3 epoch 2: train loss = 8.3195

new best val HR@50 = 3.9426

seed 3 epoch 3: train loss = 8.3192

seed 3 epoch 4: train loss = 8.3194

seed 3 epoch 5: train loss = 8.3192

new best val HR@50 = 3.9848

seed 3 epoch 6: train loss = 8.3192

seed 3 epoch 7: train loss = 8.3193

seed 3 epoch 8: train loss = 8.3192

seed 3 epoch 9: train loss = 8.3193

seed 3 epoch 10: train loss = 8.3193

seed 3 epoch 11: train loss = 8.3194

seed 3 epoch 12: train loss = 8.3193

seed 3 epoch 13: train loss = 8.3196

seed 3 epoch 14: train loss = 8.3192

seed 3 epoch 15: train loss = 8.3193

new best val HR@50 = 4.0270

seed 3 epoch 16: train loss = 8.3193

seed 3 epoch 17: train loss = 8.3193

seed 3 epoch 18: train loss = 8.3192

seed 3 epoch 19: train loss = 8.3193

seed 3 epoch 20: train loss = 8.3193

new best val HR@50 = 4.0974

TEST METRICS
counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.309490284426922, 'NDCG@10': 0.59851870160039, 'HR@50': 3.689101661503802, 'NDCG@50': 1.1147146729126427}
[head] {'HR@10': 2.444794952681388, 'NDCG@10': 1.1174237168154493, 'HR@50': 6.887486855941114, 'NDCG@50': 2.081152367777494}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.438428110349795, 'TailRatio@10': 0.0, 'Personalization@10': 15.888102988100528, 'CatalogCoverage@50': 0.3469603258410016, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.898930141818185, 'TailRatio@50': 0.0, 'Personalization@50': 9.338111397560178}

================================================================================
LogQ | seed=3 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0273
test_tail_share: 0.9727

counts: {'overall': 7102, 'head': 194, 'tail': 6908}
[overall] {'HR@10': 1.309490284426922, 'NDCG@10': 0.59851870160039, 'HR@50': 3.689101661503802, 'NDCG@50': 1.1147146729126427}
[head] {'HR@10': 46.391752577319586, 'NDCG@10': 21.457545638845332, 'HR@50': 97.9381443298969, 'NDCG@50': 33.24737078753061}
[tail] {'HR@10': 0.04342790966994789, 'NDCG@10': 0.012726688597275, 'HR@50': 1.0422698320787493, 'NDCG@50': 0.21232102985591322}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.039260690988161394, 'AvgPopularity@10': 6.438428110349795, 'TailRatio@10': 1.4573359617009294, 'Personalization@10': 15.888102988100528, 'CatalogCoverage@50': 0.3469603258410016, 'TailCoverage@50': 0.24764435854071032, 'AvgPopularity@50': 5.898930141818185, 'TailRatio@50': 40.386651647423264, 'Personalization@50': 9.338111397560178}

================================================================================
LogQ | seed=3 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0639
test_tail_share: 0.9361

counts: {'overall': 7102, 'head': 454, 'tail': 6648}
[overall] {'HR@10': 1.309490284426922, 'NDCG@10': 0.59851870160039, 'HR@50': 3.689101661503802, 'NDCG@50': 1.1147146729126427}
[head] {'HR@10': 20.484581497797357, 'NDCG@10': 9.36273087833914, 'HR@50': 57.268722466960355, 'NDCG@50': 17.359207052504246}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.030084235860409148, 'NDCG@50': 0.0053585447034687015}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.006064281382656155, 'AvgPopularity@10': 6.438428110349795, 'TailRatio@10': 0.0028161081385525205, 'Personalization@10': 15.888102988100528, 'CatalogCoverage@50': 0.3469603258410016, 'TailCoverage@50': 0.0272892662219527, 'AvgPopularity@50': 5.898930141818185, 'TailRatio@50': 3.0042241622078287, 'Personalization@50': 9.338111397560178}

================================================================================
LogQ | seed=3 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1036
test_tail_share: 0.8964

counts: {'overall': 7102, 'head': 736, 'tail': 6366}
[overall] {'HR@10': 1.309490284426922, 'NDCG@10': 0.59851870160039, 'HR@50': 3.689101661503802, 'NDCG@50': 1.1147146729126427}
[head] {'HR@10': 12.635869565217392, 'NDCG@10': 5.77538018854072, 'HR@50': 35.59782608695652, 'NDCG@50': 10.7563907704152}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.003047479734259767, 'AvgPopularity@10': 6.438428110349795, 'TailRatio@10': 0.0014080540692762602, 'Personalization@10': 15.888102988100528, 'CatalogCoverage@50': 0.3469603258410016, 'TailCoverage@50': 0.012189918937039069, 'AvgPopularity@50': 5.898930141818185, 'TailRatio@50': 0.5936355956068713, 'Personalization@50': 9.338111397560178}

================================================================================
LogQ | seed=3 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2853
test_tail_share: 0.7147

counts: {'overall': 7102, 'head': 2026, 'tail': 5076}
[overall] {'HR@10': 1.309490284426922, 'NDCG@10': 0.59851870160039, 'HR@50': 3.689101661503802, 'NDCG@50': 1.1147146729126427}
[head] {'HR@10': 4.590325765054295, 'NDCG@10': 2.098065063556747, 'HR@50': 12.931885488647582, 'NDCG@50': 3.907553606626647}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.438428110349795, 'TailRatio@10': 0.0, 'Personalization@10': 15.888102988100528, 'CatalogCoverage@50': 0.3469603258410016, 'TailCoverage@50': 0.006351626016260163, 'AvgPopularity@50': 5.898930141818185, 'TailRatio@50': 0.007603491974091805, 'Personalization@50': 9.338111397560178}

================================================================================
LogQ | seed=3 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5356
test_tail_share: 0.4644

counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.309490284426922, 'NDCG@10': 0.59851870160039, 'HR@50': 3.689101661503802, 'NDCG@50': 1.1147146729126427}
[head] {'HR@10': 2.444794952681388, 'NDCG@10': 1.1174237168154493, 'HR@50': 6.887486855941114, 'NDCG@50': 2.081152367777494}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.12671594508975714, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.438428110349795, 'TailRatio@10': 0.0, 'Personalization@10': 15.888102988100528, 'CatalogCoverage@50': 0.3469603258410016, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.898930141818185, 'TailRatio@50': 0.0, 'Personalization@50': 9.338111397560178}

================================================================================
LogQ seed 4
================================================================================

seed 4 epoch 1: train loss = 8.3215

new best val HR@50 = 3.7595

seed 4 epoch 2: train loss = 8.3196

new best val HR@50 = 3.9989

seed 4 epoch 3: train loss = 8.3193

new best val HR@50 = 4.0411

seed 4 epoch 4: train loss = 8.3194

seed 4 epoch 5: train loss = 8.3193

new best val HR@50 = 4.0834

seed 4 epoch 6: train loss = 8.3192

seed 4 epoch 7: train loss = 8.3193

seed 4 epoch 8: train loss = 8.3193

seed 4 epoch 9: train loss = 8.3193

seed 4 epoch 10: train loss = 8.3198

seed 4 epoch 11: train loss = 8.3201

seed 4 epoch 12: train loss = 8.3202

seed 4 epoch 13: train loss = 8.3200

seed 4 epoch 14: train loss = 8.3203

seed 4 epoch 15: train loss = 8.3200

seed 4 epoch 16: train loss = 8.3205

seed 4 epoch 17: train loss = 8.3207

seed 4 epoch 18: train loss = 8.3204

seed 4 epoch 19: train loss = 8.3198

seed 4 epoch 20: train loss = 8.3197

TEST METRICS
counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.2954097437341594, 'NDCG@10': 0.6579864351133533, 'HR@50': 3.4356519290340746, 'NDCG@50': 1.1225083166847398}
[head] {'HR@10': 2.4185068349106205, 'NDCG@10': 1.2284489122437001, 'HR@50': 6.414300736067298, 'NDCG@50': 2.0957029613814466}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.13576708402473978, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.466013372133613, 'TailRatio@10': 0.0, 'Personalization@10': 16.092434813600498, 'CatalogCoverage@50': 0.3590285110876452, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.933582490096132, 'TailRatio@50': 0.0, 'Personalization@50': 9.47389793743576}

================================================================================
LogQ | seed=4 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0273
test_tail_share: 0.9727

counts: {'overall': 7102, 'head': 194, 'tail': 6908}
[overall] {'HR@10': 1.2954097437341594, 'NDCG@10': 0.6579864351133533, 'HR@50': 3.4356519290340746, 'NDCG@50': 1.1225083166847398}
[head] {'HR@10': 47.42268041237113, 'NDCG@10': 24.087730217397088, 'HR@50': 100.0, 'NDCG@50': 36.21026291536031}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.7237984944991315, 'NDCG@50': 0.13712551527433708}
[long_tail] {'CatalogCoverage@10': 0.13576708402473978, 'TailCoverage@10': 0.039260690988161394, 'AvgPopularity@10': 6.466013372133613, 'TailRatio@10': 0.07885102787947057, 'Personalization@10': 16.092434813600498, 'CatalogCoverage@50': 0.3590285110876452, 'TailCoverage@50': 0.2597245711524523, 'AvgPopularity@50': 5.933582490096132, 'TailRatio@50': 38.4770487186708, 'Personalization@50': 9.47389793743576}

================================================================================
LogQ | seed=4 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0639
test_tail_share: 0.9361

counts: {'overall': 7102, 'head': 454, 'tail': 6648}
[overall] {'HR@10': 1.2954097437341594, 'NDCG@10': 0.6579864351133533, 'HR@50': 3.4356519290340746, 'NDCG@50': 1.1225083166847398}
[head] {'HR@10': 20.26431718061674, 'NDCG@10': 10.292994850605805, 'HR@50': 53.74449339207048, 'NDCG@50': 17.55959045175115}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.13576708402473978, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.466013372133613, 'TailRatio@10': 0.0, 'Personalization@10': 16.092434813600498, 'CatalogCoverage@50': 0.3590285110876452, 'TailCoverage@50': 0.030321406913280776, 'AvgPopularity@50': 5.933582490096132, 'TailRatio@50': 0.04139678963672205, 'Personalization@50': 9.47389793743576}

================================================================================
LogQ | seed=4 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1036
test_tail_share: 0.8964

counts: {'overall': 7102, 'head': 736, 'tail': 6366}
[overall] {'HR@10': 1.2954097437341594, 'NDCG@10': 0.6579864351133533, 'HR@50': 3.4356519290340746, 'NDCG@50': 1.1225083166847398}
[head] {'HR@10': 12.5, 'NDCG@10': 6.349211497520428, 'HR@50': 33.15217391304348, 'NDCG@50': 10.831595197139976}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.13576708402473978, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.466013372133613, 'TailRatio@10': 0.0, 'Personalization@10': 16.092434813600498, 'CatalogCoverage@50': 0.3590285110876452, 'TailCoverage@50': 0.0091424392027793, 'AvgPopularity@50': 5.933582490096132, 'TailRatio@50': 0.0030977189524077726, 'Personalization@50': 9.47389793743576}

================================================================================
LogQ | seed=4 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2853
test_tail_share: 0.7147

counts: {'overall': 7102, 'head': 2026, 'tail': 5076}
[overall] {'HR@10': 1.2954097437341594, 'NDCG@10': 0.6579864351133533, 'HR@50': 3.4356519290340746, 'NDCG@50': 1.1225083166847398}
[head] {'HR@10': 4.54096742349457, 'NDCG@10': 2.3065250060093954, 'HR@50': 12.043435340572557, 'NDCG@50': 3.9348736747754307}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.13576708402473978, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.466013372133613, 'TailRatio@10': 0.0, 'Personalization@10': 16.092434813600498, 'CatalogCoverage@50': 0.3590285110876452, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.933582490096132, 'TailRatio@50': 0.0, 'Personalization@50': 9.47389793743576}

================================================================================
LogQ | seed=4 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5356
test_tail_share: 0.4644

counts: {'overall': 7102, 'head': 3804, 'tail': 3298}
[overall] {'HR@10': 1.2954097437341594, 'NDCG@10': 0.6579864351133533, 'HR@50': 3.4356519290340746, 'NDCG@50': 1.1225083166847398}
[head] {'HR@10': 2.4185068349106205, 'NDCG@10': 1.2284489122437001, 'HR@50': 6.414300736067298, 'NDCG@50': 2.0957029613814466}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.13576708402473978, 'TailCoverage@10': 0.0, 'AvgPopularity@10': 6.466013372133613, 'TailRatio@10': 0.0, 'Personalization@10': 16.092434813600498, 'CatalogCoverage@50': 0.3590285110876452, 'TailCoverage@50': 0.0, 'AvgPopularity@50': 5.933582490096132, 'TailRatio@50': 0.0, 'Personalization@50': 9.47389793743576}

,method,seed,lr,dropout,weight_decay,logq_weight,best_val_HR@50,test_overall_HR@10,test_overall_NDCG@10,test_overall_HR@50,...,test_TailRatio@10,test_Personalization@10,test_CatalogCoverage@50,test_TailCoverage@50,test_AvgPopularity@50,test_TailRatio@50,test_Personalization@50,test_count_overall,test_count_head,test_count_tail
0,LogQ,0,0.01,0.2,0.0001,0.1,4.153760,1.239088,0.642273,3.534216,...,0.0,16.111733,0.365063,0.000000,5.935894,0.00000,9.498883,7102,3804,3298
1,LogQ,1,0.01,0.2,0.0001,0.1,4.125598,1.337651,0.632672,3.604618,...,0.0,16.008337,0.352994,0.007543,5.931932,0.01042,9.471083,7102,3804,3298
2,LogQ,2,0.01,0.2,0.0001,0.1,4.252323,1.281329,0.650822,3.491974,...,0.0,16.061332,0.349977,0.000000,5.925947,0.00000,9.496761,7102,3804,3298
3,LogQ,3,0.01,0.2,0.0001,0.1,4.097437,1.309490,0.598519,3.689102,...,0.0,15.888103,0.346960,0.000000,5.898930,0.00000,9.338111,7102,3804,3298
4,LogQ,4,0.01,0.2,0.0001,0.1,4.083357,1.295410,0.657986,3.435652,...,0.0,16.092435,0.359029,0.000000,5.933582,0.00000,9.473898,7102,3804,3298

## 11. Compact final table

In [14]:

def make_final_summary_table(
    metrics_df: pd.DataFrame,
    sweep_df: pd.DataFrame,
    method_name: str,
    save_path: str | None = None,
) -> pd.DataFrame:
    """
    One compact final table: one row = method × head_fraction.
    Metrics are aggregated over seeds as mean ± std.
    """
    if len(sweep_df) == 0:
        raise ValueError("sweep_df is empty")

    selected_metrics = [
        "overall_HR@50",
        "overall_NDCG@50",
        "head_HR@50",
        "head_NDCG@50",
        "tail_HR@50",
        "tail_NDCG@50",
        "CatalogCoverage@50",
        "TailCoverage@50",
        "AvgPopularity@50",
        "TailRatio@50",
        "Personalization@50",
    ]

    rows = []

    for head_fraction, group in sweep_df.groupby("head_fraction"):
        group = group.copy()

        row = {
            "method": method_name,
            "head_share": f"{100 * float(head_fraction):.3f}%",
            "head_fraction": float(head_fraction),
            "num_seeds": group["seed"].nunique() if "seed" in group.columns else len(group),
            "num_head_items": int(group["num_head_items"].iloc[0]) if "num_head_items" in group.columns else np.nan,
            "num_tail_items": int(group["num_tail_items"].iloc[0]) if "num_tail_items" in group.columns else np.nan,
        }

        if "test_head_share" in group.columns:
            row["test_head_share"] = f"{100 * float(group['test_head_share'].mean()):.2f}%"

        if "test_tail_share" in group.columns:
            row["test_tail_share"] = f"{100 * float(group['test_tail_share'].mean()):.2f}%"

        if metrics_df is not None and len(metrics_df) > 0:
            for hp_col in ["lr", "dropout", "weight_decay", "logq_weight", "cb_beta"]:
                if hp_col in metrics_df.columns:
                    vals = metrics_df[hp_col].dropna().unique()
                    if len(vals) == 1:
                        row[hp_col] = vals[0]
                    elif len(vals) > 1:
                        row[hp_col] = ", ".join(map(str, vals))

            if "best_val_HR@50" in metrics_df.columns:
                vals = metrics_df["best_val_HR@50"].dropna().to_numpy(dtype=float)
                if len(vals) > 0:
                    mean = float(np.mean(vals))
                    std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
                    row["best_val_HR@50"] = f"{mean:.2f} ± {std:.2f}"

        for metric in selected_metrics:
            if metric not in group.columns:
                continue

            vals = group[metric].dropna().to_numpy(dtype=float)

            if len(vals) == 0:
                row[metric] = "nan"
                continue

            mean = float(np.mean(vals))
            std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0

            if "AvgPopularity" in metric:
                row[metric] = f"{mean:.4f} ± {std:.4f}"
            else:
                row[metric] = f"{mean:.2f} ± {std:.2f}"

        rows.append(row)

    summary_df = pd.DataFrame(rows).sort_values("head_fraction").reset_index(drop=True)

    first_cols = [
        "method",
        "head_share",
        "head_fraction",
        "num_seeds",
        "num_head_items",
        "num_tail_items",
        "test_head_share",
        "test_tail_share",
        "lr",
        "dropout",
        "weight_decay",
        "logq_weight",
        "cb_beta",
        "best_val_HR@50",
    ]

    metric_cols = selected_metrics
    ordered_cols = [c for c in first_cols + metric_cols if c in summary_df.columns]
    other_cols = [c for c in summary_df.columns if c not in ordered_cols]
    summary_df = summary_df[ordered_cols + other_cols]

    if save_path is not None:
        summary_df.to_csv(save_path, index=False)
        print(f"saved: {save_path}")

    return summary_df


summary_df = make_final_summary_table(metrics_df, sweep_df, method_name="LogQ", save_path="logq_summary.csv")
summary_df

saved: logq_summary.csv

,method,head_share,head_fraction,num_seeds,num_head_items,num_tail_items,test_head_share,test_tail_share,lr,dropout,...,overall_NDCG@50,head_HR@50,head_NDCG@50,tail_HR@50,tail_NDCG@50,CatalogCoverage@50,TailCoverage@50,AvgPopularity@50,TailRatio@50,Personalization@50
0,LogQ,0.100%,0.001,5,33,33112,2.73%,97.27%,0.01,0.2,...,1.13 ± 0.01,99.59 ± 0.92,35.33 ± 1.25,0.85 ± 0.12,0.17 ± 0.03,0.35 ± 0.01,0.26 ± 0.01,5.9253 ± 0.0152,38.86 ± 0.85,9.46 ± 0.07
1,LogQ,0.500%,0.005,5,165,32980,6.39%,93.61%,0.01,0.2,...,1.13 ± 0.01,55.46 ± 1.40,17.62 ± 0.20,0.01 ± 0.01,0.00 ± 0.00,0.35 ± 0.01,0.02 ± 0.01,5.9253 ± 0.0152,0.64 ± 1.33,9.46 ± 0.07
2,LogQ,1.000%,0.010,5,331,32814,10.36%,89.64%,0.01,0.2,...,1.13 ± 0.01,34.27 ± 0.95,10.88 ± 0.11,0.00 ± 0.00,0.00 ± 0.00,0.35 ± 0.01,0.01 ± 0.01,5.9253 ± 0.0152,0.12 ± 0.26,9.46 ± 0.07
3,LogQ,5.000%,0.050,5,1657,31488,28.53%,71.47%,0.01,0.2,...,1.13 ± 0.01,12.45 ± 0.35,3.95 ± 0.04,0.00 ± 0.00,0.00 ± 0.00,0.35 ± 0.01,0.00 ± 0.00,5.9253 ± 0.0152,0.00 ± 0.01,9.46 ± 0.07
4,LogQ,20.000%,0.200,5,6629,26516,53.56%,46.44%,0.01,0.2,...,1.13 ± 0.01,6.63 ± 0.18,2.10 ± 0.02,0.00 ± 0.00,0.00 ± 0.00,0.35 ± 0.01,0.00 ± 0.00,5.9253 ± 0.0152,0.00 ± 0.00,9.46 ± 0.07